syntax = "proto3";

package grpc.tradeapi.v1.assets;

import "google/api/annotations.proto";
import "google/type/date.proto";
import "google/type/decimal.proto";
import "google/type/interval.proto";
import "google/type/money.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/wrappers.proto";
import "grpc/gateway/protoc_gen_openapiv2/options/annotations.proto";

option go_package = "github.com/limeint/tradingapi/go/grpc/tradeapi/v1/assets";
option java_multiple_files = true;
option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  schemes: [
    HTTP,
    HTTPS
  ]
  info: {
    title: "REST"
    description: "Trading API"
  }
  security_definitions: {
    security: {
      key: "Authorization"
      value: {
        type: TYPE_API_KEY
        in: IN_HEADER
        name: "Authorization"
        description: "JWT authorization token"
      }
    }
  }
  responses: [
    {
      key: "default"
      value: {
        schema: {
          json_schema: {
            ref: "googletypeStatus"
          }
        }
      }
    },
    {
      key: "500"
      value: {
        description: "Internal service error. Try again later."
      }
    },
    {
      key: "503"
      value: {
        description: "The service is currently unavailable. Please try again later."
      }
    },
    {
      key: "429"
      value: {
        description: "Too many requests. The available limit is 200 requests per minute."
      }
    },
    {
      key: "401"
      value: {
        description: "Token has expired or the token is invalid"
      }
    },
    {
      key: "504"
      value: {
        description: "The deadline expired before the operation could be completed"
      }
    },
    {
      key: "404"
      value: {
        description: "Asset not found"
      }
    }
  ]
};

// Assets Service
service AssetsService {
  // Getting a list of available exchange names and MIC codes
  // HTTP request example:
  // GET /v1/exchanges
  // Authorization: <token>
  rpc Exchanges(ExchangesRequest) returns (ExchangesResponse) {
    option (google.api.http) = {
      get: "/v1/exchanges"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      security: [
        {
          security_requirement: {
            key: "Authorization"
          }
        }
      ]
    };
  };

  // Get the list of instruments available for trading, along with their descriptions
  // HTTP request example:
  // GET /v1/assets
  // Authorization: <token>
  rpc Assets(AssetsRequest) returns (AssetsResponse) {
    option deprecated = true;
    option (google.api.http) = {
      get: "/v1/assets"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      security: [
        {
          security_requirement: {
            key: "Authorization"
          }
        }
      ]
    };
  };

  // Get the list of all instruments, including indicative and archived ones, along with their descriptions
  // Example HTTP request:
  // GET /v1/assets/all?cursor=56658&only_disabled=true
  // Authorization: <token>
  rpc AllAssets(AllAssetsRequest) returns (AllAssetsResponse) {
    option (google.api.http) = {
      get: "/v1/assets/all"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      security: [
        {
          security_requirement: {
            key: "Authorization"
          }
        }
      ]
    };
  };

  // Getting information on a specific asset
  // HTTP request example:
  // GET /v1/assets/SBER@MISX?account_id=1440399
  // Authorization: <token>
  //
  // Parameters:
  // - symbol - passed in the URL path
  // - account_id - passed as a query parameter
  rpc GetAsset(GetAssetRequest) returns (GetAssetResponse) {
    option (google.api.http) = {
      get: "/v1/assets/{symbol}"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      security: [
        {
          security_requirement: {
            key: "Authorization"
          }
        }
      ]
      responses: {
        key: "400"
        value: {
          description: "Invalid symbol or account passed. The symbol must be in the form ticker@mic. Where ticker is, for example, SBER. And mic is, for example, MISX."
        }
      }
    };
  };

  // Getting trading parameters for an asset
  // HTTP request example:
  // GET /v1/assets/SBER@MISX/params?account_id=1440399
  // Authorization: <token>
  //
  // Parameters:
  // - symbol - passed in the URL path
  // - account_id - passed as a query parameter
  rpc GetAssetParams(GetAssetParamsRequest) returns (GetAssetParamsResponse) {
    option (google.api.http) = {
      get: "/v1/assets/{symbol}/params"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      security: [
        {
          security_requirement: {
            key: "Authorization"
          }
        }
      ]
      responses: {
        key: "400"
        value: {
          description: "Invalid symbol or account passed. The symbol must be in the form ticker@mic. Where ticker is, for example, SBER. And mic is, for example, MISX."
        }
      }
    };
  };

  // Getting the options chain for the underlying asset
  // HTTP request example:
  // GET /v1/assets/SBER@MISX/options
  // Authorization: <token>
  rpc OptionsChain(OptionsChainRequest) returns (OptionsChainResponse) {
    option (google.api.http) = {
      get: "/v1/assets/{underlying_symbol}/options"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      security: [
        {
          security_requirement: {
            key: "Authorization"
          }
        }
      ]
      responses: {
        key: "400"
        value: {
          description: "Invalid symbol passed. The symbol must be in the form ticker@mic. Where ticker is, for example, SBER. And mic is, for example, MISX."
        }
      }
    };
  };

  // Getting a trading schedule for an asset
  // HTTP request example:
  // GET /v1/assets/SBER@MISX/schedule
  // Authorization: <token>
  rpc Schedule(ScheduleRequest) returns (ScheduleResponse) {
    option (google.api.http) = {
      get: "/v1/assets/{symbol}/schedule"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      security: [
        {
          security_requirement: {
            key: "Authorization"
          }
        }
      ]
      responses: {
        key: "400"
        value: {
          description: "Invalid symbol passed. The symbol must be in the form ticker@mic. Where ticker is, for example, SBER. And mic is, for example, MISX."
        }
      }
    };
  };

  // Getting the time on the server
  // HTTP request example:
  // GET /v1/assets/clock
  // Authorization: <token>
  rpc Clock(ClockRequest) returns (ClockResponse) {
    option (google.api.http) = {
      get: "/v1/assets/clock"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      security: [
        {
          security_requirement: {
            key: "Authorization"
          }
        }
      ]
    };
  };

  // Get the composition of a stock market index by its symbol.
  rpc GetConstituents(GetConstituentsRequest) returns (GetConstituentsResponse) {
    option (google.api.http) = {
      get: "/v1/assets/{symbol}/constituents"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      security: [
        {
          security_requirement: {
            key: "Authorization"
          }
        }
      ]
    };
  };

}

// Request to obtain a list of available exchanges
message ExchangesRequest {
}

// List of available exchanges
message ExchangesResponse {
  // Exchange Information
  repeated Exchange exchanges = 1;
}

// Request to get a list of available assets
message AssetsRequest {
}

// List of available assets
message AssetsResponse {
  // Asset information
  repeated Asset assets = 1;
}

// Request to get a list of available assets
message AllAssetsRequest {
  // Cursor for pagination. Specifies the sec_id of the asset with which the list should begin.
  // For the first request, leave this field blank (value 0).
  // For subsequent requests, use the next_cursor value from the previous response.
  int64 cursor = 1;
  // Filtering by asset status: only active (non-archived) assets are selected
  // Default: false.
  bool only_active = 2;
  // Filtering by asset status: only inactive (archived) assets are selected
  // Default: false.
  bool only_disabled = 3;
}

// Response containing some of the available assets.
message AllAssetsResponse {
  // Part of the list of assets
  repeated Asset assets = 1;
  // Cursor for retrieving the next page. Contains the sec_id of the last asset in the current list.
  // Pass this value into the cursor field of the next request to retrieve the next piece of data.
  // If the value is 0 or missing, this is the last page.
  int64 next_cursor = 2;
}

// Request for information on a specific asset
message GetAssetRequest {
  // Symbol
  string symbol = 1;
  // The account ID for which the asset information will be retrieved.
  string account_id = 2;
}

// List of information about a specific asset
message GetAssetResponse {
  // Specific parameters for instrument type "Futures"
  message FutureDetails {
    // Futures contract expiration date and time.
    google.protobuf.Timestamp expiration_date = 1;
    // Contract size (multiplier) — the number of units of the underlying asset in one contract.
    google.type.Decimal contract_size = 2;
  }
  // Specific parameters for instrument type "Option"
  message OptionDetails {
    // Option contract expiration date and time.
    google.protobuf.Timestamp expiration_date = 1;
    // Contract size (multiplier) — the number of units of the underlying asset in one contract.
    google.type.Decimal contract_size = 2;
    // Option strike price.
    google.type.Decimal strike = 3;
  }
  // Specific parameters for instrument type "Bond"
  message BondDetails {
    // Current face value of one bond.
    google.type.Decimal bond_face_value = 1;
    // Symbolic currency code of the bond denomination (e.g., RUB, USD).
    string currency = 2;
  }
  // Trading mode code
  string board = 1;
  // Asset ID
  string id = 2;
  // Asset ticker
  string ticker = 3;
  // mic exchange ID
  string mic = 4;
  // Isin asset identifier
  string isin = 5;
  // Asset type
  string type = 6;
  // Asset name
  string name = 7;
  // Number of decimal places in the price
  int32 decimals = 10;
  // Minimum price step. To calculate the final price step: min_step/(10 decimals)
  int64 min_step = 11;
  // Number of pieces per lot
  google.type.Decimal lot_size = 9;
  // Futures expiration date
  google.type.Date expiration_date = 12 [deprecated = true];
  // The quote currency may not match the asset's trading mode currency.
  string quote_currency = 13;

  oneof asset_details {
    // Specific parameters for instrument type "Futures"
    FutureDetails future_details = 14;
    // Specific parameters for instrument type "Option"
    OptionDetails option_details = 15;
    // Specific parameters for instrument type "Bond"
    BondDetails bond_details = 16;
  }
}

// Request for asset trading parameters
message GetAssetParamsRequest {
  // Symbol
  string symbol = 1;
  // ID of the account for which trading parameters will be selected
  string account_id = 2;
}

// Asset trading parameters
message GetAssetParamsResponse {
  // Symbol
  string symbol = 1;
  // Account ID for which trading parameters are selected
  string account_id = 2;
  // Are trading operations available?
  // The old field is marked as deprecated.
  // Clients should migrate to is_tradeable.
  bool tradeable = 3 [deprecated = true];
  // Are operations available in Long?
  Longable longable = 4;
  // Are short operations available?
  Shortable shortable = 5;
  // Risk rate for the Long operation
  google.type.Decimal long_risk_rate = 6;
  // Amount of collateral to maintain a Long position
  google.type.Money long_collateral = 7 [deprecated = true];
  // Risk rate for a short transaction
  google.type.Decimal short_risk_rate = 8;
  // Collateral amount to maintain a Short position
  google.type.Money short_collateral = 9 [deprecated = true];
  // Initial requirements for how much free cash must be in the account to open a long position for FORTS accounts is equal to the exchange GO
  google.type.Money long_initial_margin = 10;
  // Initial requirements for how much free cash in the account must be available to open a short position for FORTS accounts equal to the exchange GO
  google.type.Money short_initial_margin = 11;
  // Are trading operations available? New field. Allows you to distinguish between false and "not set".
  google.protobuf.BoolValue is_tradable = 12;
  // Acceptable price. Helps determine whether orders with a negative price can be placed for a financial asset.
  PriceType price_type = 13;
  // Lot size of the instrument for trading operations. If the field is 0, the value is absent.
  int64 trade_lot_size = 14;
}

// Options chain request
message OptionsChainRequest {
  // The symbol of the option's underlying asset
  string underlying_symbol = 1;
  // Optional parameter. Relevant for options on futures by type (weekly, monthly).
  // If this parameter is not specified, options with the closest expiration date will be returned.
  string root = 2;
  // Optional filter by option expiration date.
  // If this parameter is not specified, options with the closest expiration date will be returned.
  google.type.Date expiration_date = 3;
}

// Options Chain Information
message OptionsChainResponse {
  // The symbol of the option's underlying asset
  string symbol = 1;
  // Option information
  repeated Option options = 2;
}

// Request to receive the asset schedule
message ScheduleRequest {
  // Symbol
  string symbol = 1;
}

// Asset Schedule
message ScheduleResponse {
  // Sessions
  message Sessions {
    // Session type
    string type = 1;
    // Session interval
    google.type.Interval interval = 2;
  }
  // Symbol
  string symbol = 1;
  // Asset Sessions
  repeated Sessions sessions = 2;
}

// Request to obtain the server time
message ClockRequest {
}

// Server Time
message ClockResponse {
  // Timestamp
  google.protobuf.Timestamp timestamp = 1;
}

// Exchange Information
message Exchange {
  // MIC Exchange ID
  string mic = 1;
  // Exchange Name
  string name = 2;
}

// Asset Information
message Asset {
  // Ticker@mic symbol
  string symbol = 1;
  // Asset ID
  string id = 2;
  // Asset ticker
  string ticker = 3;
  // mic exchange ID
  string mic = 4;
  // Isin asset identifier
  string isin = 5;
  // Asset type
  string type = 6;
  // Asset name
  string name = 7;
  // Is the asset archived or not?
  bool is_archived = 8;
}

// Option Information
message Option {
  // Option Type
  enum Type {
    // Unspecified value
    TYPE_UNSPECIFIED = 0;
    // Call
    TYPE_CALL = 1;
    // Put
    TYPE_PUT = 2;
  }
  // Symbol
  string symbol = 1;
  // Asset type
  Type type = 2;
  // Lot quantity of the underlying asset
  google.type.Decimal contract_size = 4;
  // Trading start date
  google.type.Date trade_first_day = 5;
  // Trading end date
  google.type.Date trade_last_day = 6;
  // Option strike price
  google.type.Decimal strike = 7;
  // Option multiplier
  google.type.Decimal multiplier = 9;
  // Expiration start date
  google.type.Date expiration_first_day = 10;
  // Expiration date
  google.type.Date expiration_last_day = 11;
}

// Are operations available in Long?
message Longable {
  // Status
  enum Status {
    // Not available
    NOT_AVAILABLE = 0;
    // Available
    AVAILABLE = 1;
    // Forbidden at the account level
    ACCOUNT_NOT_APPROVED = 2;
  }
  // Asset status
  Status value = 1;
  // How many days is the ban on Long transactions valid (if any)?
  int32 halted_days = 2;
}

// Are short operations available?
message Shortable {
  // Status
  enum Status {
    // Not available
    NOT_AVAILABLE = 0;
    // Available
    AVAILABLE = 1;
    // Indication that the paper is Hard To Borrow (if any)
    HTB = 2;
    // Forbidden at the account level
    ACCOUNT_NOT_APPROVED = 3;
    // Allowed in strategy
    AVAILABLE_STRATEGY = 4;
  }
  // Asset status
  Status value = 1;
  // How many days is the ban on short transactions valid (if any)?
  int32 halted_days = 2;
}

// Available price
enum PriceType {
  // Unknown
  UNKNOWN = 0;
  // Positive. Greater than zero
  POSITIVE = 1;
  // Non-negative. Greater than or equal to zero
  NON_NEGATIVE = 2;
  // Any
  ANY = 3;
}

// Request to get the index composition.
message GetConstituentsRequest {
  // Symbol code of the index (e.g.,"SPX@_SP", "NDX@_SCI")
  string symbol = 1;
  // Cursor for pagination. Specifies the sec_id of the asset with which the list should begin.
  // For the first request, leave this field blank (value 0).
  // For subsequent requests, use the next_cursor value from the previous response.
  int64 cursor = 2;
}

// Result of the index composition request.
message GetConstituentsResponse {
  // List of constituents (securities) included in the calculation base of the requested index.
  repeated Constituents constituents = 1;
  // Cursor for retrieving the next page. Contains the sec_id of the last asset in the current list.
  // Pass this value into the cursor field of the next request to retrieve the next piece of data.
  // If the value is 0 or missing, this is the last page
  int64 next_cursor = 2;
}

// Information about a constituent (security) included in the index
message Constituents {
  // Symbol code of the instrument
  string symbol = 1;
  // Full name of the issuing company
  string name = 2;
  // Global economic sector the company belongs to (e.g., "Technology", "Healthcare")
  string sector = 3;
  // Industry (sub-sector) of the company's activity (e.g., "Software - Application")
  string sub_sector = 4;
  // Unique company identifier in the US SEC database (Central Index Key)
  string cik = 5;
  // Index inclusion date
  google.type.Date index_inclusion_date = 6;
  // Weight of the instrument in the index
  google.type.Decimal weight = 7;
}

