syntax = "proto3";

package grpc.tradeapi.v1.corporateactions;

import "google/api/annotations.proto";
import "google/protobuf/wrappers.proto";
import "grpc/gateway/protoc_gen_openapiv2/options/annotations.proto";
import "google/type/decimal.proto";
import "google/type/date.proto";

option go_package = "github.com/limeint/tradingapi/go/grpc/tradeapi/v1/corporateactions";
option java_multiple_files = true;
option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  schemes: [
    HTTP,
    HTTPS
  ]
  info: {
    title: "REST"
    description: "Trading API"
  }
  security_definitions: {
    security: {
      key: "Authorization"
      value: {
        type: TYPE_API_KEY
        in: IN_HEADER
        name: "Authorization"
        description: "JWT Authorization Token"
      }
    }
  }
  responses: [
    {
      key: "default"
      value: {
        schema: {
          json_schema: {
            ref: "googletypeStatus"
          }
        }
      }
    },
    {
      key: "500"
      value: {
        description: "Internal service error. Please try again later."
      }
    },
    {
      key: "503"
      value: {
        description: "The service is currently unavailable. Please try again later."
      }
    },
    {
      key: "429"
      value: {
        description: "Request limit exceeded."
      }
    },
    {
      key: "401"
      value: {
        description: "Token has expired or the token is invalid"
      }
    },
    {
      key: "504"
      value: {
        description: "The deadline expired before the operation could be completed"
      }
    }
  ]
};

// Service providing information on corporate actions (dividends, splits)
service CorporateActionsService {
  // Get upcoming split events for an instrument
  rpc GetFutureSplits(GetFutureSplitsRequest) returns (GetFutureSplitsResponse) {
    option (google.api.http) = {
      get: "/v1/splits/future"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      security: [
        {
          security_requirement: {
            key: "Authorization"
          }
        }
      ]
    };
  };

  // Get the history split events for an instrument
  rpc GetPastSplits(GetPastSplitsRequest) returns (GetPastSplitsResponse) {
    option (google.api.http) = {
      get: "/v1/splits/past"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      security: [
        {
          security_requirement: {
            key: "Authorization"
          }
        }
      ]
    };
  };

  // Get a list of upcoming (future) dividend payments for an instrument
  rpc GetFutureDividends(GetFutureDividendsRequest) returns (GetFutureDividendsResponse) {
    option (google.api.http) = {
      get: "/v1/future-dividends"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      security: [
        {
          security_requirement: {
            key: "Authorization"
          }
        }
      ]
      responses: {
        key: "400"
        value: {
          description: "Invalid symbol format. Symbol must be in ticker@mic format. Where ticker is, for example, SBER, and mic is, for example, MISX"
        }
      }
    };
  };

  // Get historical data on paid dividends for an instrument
  rpc GetPastDividends(GetPastDividendsRequest) returns (GetPastDividendsResponse) {
    option (google.api.http) = {
      get: "/v1/past-dividends"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      security: [
        {
          security_requirement: {
            key: "Authorization"
          }
        }
      ]
      responses: {
        key: "400"
        value: {
          description: "Invalid symbol format. Symbol must be in ticker@mic format. Where ticker is, for example, SBER, and mic is, for example, MISX"
        }
      }
    };
  };

}

// Request upcoming split events for an instrument
message GetFutureSplitsRequest {
  // Symbol
  string symbol = 1;
  // Sorting direction by date: asc - from oldest to newest, desc - from newest to oldest
  SortDirection sort_direction = 2;
  // Limits the number of splits returned in the list
  int32 limit = 3;
  // Specifies the number of splits to skip before returning the result
  int32 offset = 4;
}

// Upcoming split events for an instrument
message GetFutureSplitsResponse {
  // Symbol
  string symbol = 1;
  // Pagination parameters
  Pagination pagination = 2;
  // Information about splits
  repeated SplitInfo splits = 3;
}

// Request history split events for an instrument
message GetPastSplitsRequest {
  // Symbol
  string symbol = 1;
  // Start of dates interval
  google.type.Date date_from = 2;
  // End of dates interval
  google.type.Date date_to = 3;
  // Sorting direction by date: asc - from oldest to newest, desc - from newest to oldest
  SortDirection sort_direction = 4;
  // Limits the number of splits returned in the list
  int32 limit = 5;
  // Specifies the number of splits to skip before returning the result
  int32 offset = 6;
}

// The history split events for an instrument
message GetPastSplitsResponse {
  // Symbol
  string symbol = 1;
  // Pagination parameters
  Pagination pagination = 2;
  // Information about splits
  repeated SplitInfo splits = 3;
}

// Information about a corporate action
message SplitInfo {
  // Effective date of the corporate action (execution date)
  google.type.Date exec_date = 1;
  // Number of securities before the conversion (numerator of the ratio)
  google.type.Decimal old_ratio = 2;
  // Number of securities after the conversion (denominator of the ratio)
  google.type.Decimal new_ratio = 3;
  // New lot size of the instrument after the execution of the corporate action
  google.protobuf.Int32Value new_lot = 4;
  // Conversion type (split / consolidation, etc.)
  ConvertationType convertation_type = 5;
}

// Possible conversion types
enum ConvertationType {
  // Unknown event/conversion type. Used by default
  CONVTYPE_UNKNOWN = 0;
  // Stock buyback. The purchase of its own shares by the issuing company
  BUYBACK = 1;
  // Call option exercised. Early redemption (recall) of a security initiated by the issuer
  CALL_OPTION_EXERCISED = 2;
  // Partial repayment of the face value (amortization) or scheduled drawing without a lottery
  DRAWINGS = 3;
  // Redemption by drawing (lottery). Early redemption of a part of a bond issue, where the bonds to be redeemed are selected by lottery
  DRAWINGS_BY_LOTTERY = 4;
  // Early conversion. Exchange of one type of security for another before the scheduled date (e.g., convertible bonds to shares)
  EARLY_CONVERSION = 5;
  // Maturity. Scheduled full repayment of a security at the end of its circulation period
  MATURITY = 6;
  // Ordinary (scheduled) conversion. A standard corporate action: split, consolidation, or scheduled exchange of securities
  ORDINARY = 7;
  // Put option exercised. Early repurchase of a security by the issuer at the request of the investor (holder)
  PUT_OPTION_EXERCISED = 8;
  // Tender offer. A public offer to shareholders to buy their securities (often during mergers/acquisitions)
  TENDER_OFFER = 9;
}

// Request to get a list of upcoming dividend payments for an instrument
message GetFutureDividendsRequest {
  // Instrument symbol
  string symbol = 1;
  // Date sorting direction: asc — from old to new, desc — from new to old
  SortDirection sort_direction = 2;
  // Limits the number of elements returned.
  int32 limit = 3;
  // Specifies the number of elements to skip before returning the result
  int32 offset = 4;
}

// List of upcoming dividend payments for an instrument with pagination
message GetFutureDividendsResponse {
  // Pagination information
  Pagination pagination = 1;
  // List of dividends
  repeated Dividend dividends = 2;
}

// Request to get historical data on paid dividends for an instrument
message GetPastDividendsRequest {
  // Instrument symbol
  string symbol = 1;
  // Date sorting direction: asc — from old to new, desc — from new to old
  SortDirection sort_direction = 2;
  // Start of the time interval
  google.type.Date date_from = 3;
  // End of the time interval
  google.type.Date date_to = 4;
  // Limits the number of elements returned.
  int32 limit = 5;
  // Specifies the number of elements to skip before returning the result
  int32 offset = 6;
}

// Historical data on paid dividends for an instrument with pagination
message GetPastDividendsResponse {
  // Pagination information
  Pagination pagination = 1;
  // List of dividends
  repeated Dividend dividends = 2;
}

// Information about a dividend payment
message Dividend {
  // Record date (registry closure date)
  google.type.Date date = 1;
  // Dividend amount per share
  google.type.Decimal amount = 2;
  // Dividend payment currency
  string currency = 3;
}

// Pagination parameters
message Pagination {
  // Total number of elements
  int32 total = 1;
  // Limits the number of elements returned.
  int32 limit = 2;
  // Specifies the number of elements to skip before returning the result
  int32 offset = 3;
  // Indicates whether a next data page exists.
  bool has_next = 4;
}

// Sort order
enum SortDirection {
  // Ascending
  ASC = 0;
  // Descending
  DESC = 1;
}

