syntax = "proto3";

package grpc.tradeapi.v1.orders;

import "google/api/annotations.proto";
import "google/protobuf/timestamp.proto";
import "google/type/decimal.proto";
import "grpc/tradeapi/v1/side.proto";
import "grpc/tradeapi/v1/trade.proto";
import "grpc/gateway/protoc_gen_openapiv2/options/annotations.proto";

option go_package = "github.com/limeint/tradingapi/go/grpc/tradeapi/v1/orders";
option java_multiple_files = true;
option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  schemes: [
    HTTP,
    HTTPS
  ]
  info: {
    title: "REST"
    description: "Trading API"
  }
  security_definitions: {
    security: {
      key: "Authorization"
      value: {
        type: TYPE_API_KEY
        in: IN_HEADER
        name: "Authorization"
        description: "JWT authorization token"
      }
    }
  }
  responses: [
    {
      key: "default"
      value: {
        schema: {
          json_schema: {
            ref: "googletypeStatus"
          }
        }
      }
    },
    {
      key: "500"
      value: {
        description: "Internal service error. Please try again later."
      }
    },
    {
      key: "503"
      value: {
        description: "The service is currently unavailable. Please try again later."
      }
    },
    {
      key: "429"
      value: {
        description: "Too many requests. The available limit is 200 requests per minute."
      }
    },
    {
      key: "401"
      value: {
        description: "Token has expired or the token is invalid"
      }
    },
    {
      key: "504"
      value: {
        description: "The deadline expired before the operation could be completed"
      }
    }
  ]
};

// Order Service
service OrdersService {
  // Placing an exchange order
  // HTTP request example:
  // POST /v1/accounts/A12345/orders
  // Content-Type: application/json
  // Authorization: <token>
  //
  // {
  //  "symbol": "SBER@MISX"
  //  "quantity": {
  //  "value": "10"
  //  }"
  //  "side": "SIDE_BUY"
  //  "type": "ORDER_TYPE_LIMIT"
  //  "time_in_force": "TIME_IN_FORCE_DAY"
  //  "limit_price": {
  //  "value": "150.50"
  //  }
  // }
  //
  // The account_id field is taken from URL-paths" the remaining fields are passed in the request body
  rpc PlaceOrder(Order) returns (OrderState) {
    option (google.api.http) = {
      post: "/v1/accounts/{account_id}/orders"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      security: [
        {
          security_requirement: {
            key: "Authorization"
          }
        }
      ]
      responses: [
        {
          key: "404"
          value: {
            description: "The account or asset was not found"
          }
        },
        {
          key: "400"
          value: {
            description: "Incorrectly passed trade parameters"
          }
        }
      ]
    };
  };

  // Cancel exchange order
  // HTTP request example:
  // DELETE /v1/accounts/A12345/orders/ORD789012
  // Authorization: <token>
  rpc CancelOrder(CancelOrderRequest) returns (OrderState) {
    option (google.api.http) = {
      delete: "/v1/accounts/{account_id}/orders/{order_id}"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      security: [
        {
          security_requirement: {
            key: "Authorization"
          }
        }
      ]
      responses: [
        {
          key: "404"
          value: {
            description: "Invoice or order not found"
          }
        },
        {
          key: "400"
          value: {
            description: "The request cannot be canceled because it has already been executed."
          }
        }
      ]
    };
  };

  // Getting a list of requests for an account
  // HTTP request example:
  // GET /v1/accounts/A12345/orders
  // Authorization: <token>
  rpc GetOrders(OrdersRequest) returns (OrdersResponse) {
    option (google.api.http) = {
      get: "/v1/accounts/{account_id}/orders"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      security: [
        {
          security_requirement: {
            key: "Authorization"
          }
        }
      ]
      responses: {
        key: "404"
        value: {
          description: "Invoice not found"
        }
      }
    };
  };

  // Get information about a specific order
  // HTTP request example:
  // GET /v1/accounts/A12345/orders/ORD789012
  // Authorization: <token>
  rpc GetOrder(GetOrderRequest) returns (OrderState) {
    option (google.api.http) = {
      get: "/v1/accounts/{account_id}/orders/{order_id}"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      security: [
        {
          security_requirement: {
            key: "Authorization"
          }
        }
      ]
      responses: {
        key: "404"
        value: {
          description: "Invoice or order not found"
        }
      }
    };
  };

  // Subscribe to your own orders and trades. Stream method
  rpc SubscribeOrderTrade(stream OrderTradeRequest) returns (stream OrderTradeResponse) {
    option deprecated = true;
  };

  // Subscribe to your own orders. Stream method
  rpc SubscribeOrders(SubscribeOrdersRequest) returns (stream SubscribeOrdersResponse);

  // Subscribe to your own trades. Stream method
  rpc SubscribeTrades(SubscribeTradesRequest) returns (stream SubscribeTradesResponse);

  // Issuing an SL/TP order
  // Example HTTP request:
  // POST /v1/accounts/A12345/sltp-orders
  // Content-Type: application/json
  // Authorization: <token>
  //
  // {
  //  "symbol": "SBER@MISX"
  //  "side": "SIDE_BUY"
  //  "quantity_sl": {
  //  "value": "10"
  //  }"
  //  "sl_price": {
  //  "value": "270.00"
  //  }"
  //  "limit_price": {
  //  "value": "269.50"
  //  }"
  //  "quantity_tp": {
  //  "value": "10"
  //  }"
  //  "tp_price": {
  //  "value": "295.50"
  //  }"
  //  "tp_guard_spread": {
  //  "value": "0.5" }"
  //  "tp_spread_measure": "TP_SPREAD_MEASURE_VALUE"
  //  "valid_before": "VALID_BEFORE_GOOD_TILL_DATE"
  //  "valid_expiry_time": "2026-12-31T23:59:59Z"
  //  "comment": "my SL/TP order"
  //  }
  //
  //  The account_id field is taken from the URL path, the remaining fields are passed in the request body
  rpc PlaceSLTPOrder(SLTPOrder) returns (OrderState) {
    option (google.api.http) = {
      post: "/v1/accounts/{account_id}/sltp-orders"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      security: [
        {
          security_requirement: {
            key: "Authorization"
          }
        }
      ]
      responses: [
        {
          key: "404"
          value: {
            description: "Account or asset was not found"
          }
        },
        {
          key: "400"
          value: {
            description: "Incorrectly transmitted trade parameters"
          }
        }
      ]
    };
  };

}

// Request to subscribe to your own orders and trades. Stream
message OrderTradeRequest {
  option deprecated = true;
  // Available actions
  enum Action {
    // Subscribe
    ACTION_SUBSCRIBE = 0;
    // Unsubscribe
    ACTION_UNSUBSCRIBE = 1;
  }
  // Subscription type
  enum DataType {
    // All: orders and trades
    DATA_TYPE_ALL = 0;
    // Orders
    DATA_TYPE_ORDERS = 1;
    // Trades
    DATA_TYPE_TRADES = 2;
  }
  // Changing subscription status: subscribe/unsubscribe
  Action action = 1;
  // Subscribe to requests/orders only or to all at once
  DataType data_type = 2;
  // Account ID
  string account_id = 3;
}

// List of your own orders and trades
message OrderTradeResponse {
  option deprecated = true;
  // Orders
  repeated OrderState orders = 1;
  // Trades
  repeated AccountTrade trades = 2;
}

// Request to subscribe to your own orders. Stream
message SubscribeOrdersRequest {
  // Account ID
  string account_id = 1;
}

// List of your own requests
message SubscribeOrdersResponse {
  // Orders
  repeated OrderState orders = 1;
}

// Request to subscribe to your own trades. Stream
message SubscribeTradesRequest {
  // Account ID
  string account_id = 1;
}

// List of your own trades
message SubscribeTradesResponse {
  // Trades
  repeated AccountTrade trades = 1;
}

// Request to receive a specific order
message GetOrderRequest {
  // Account ID
  string account_id = 1;
  // Order ID
  string order_id = 2;
}

// Order Type
enum OrderType {
  // Value not specified
  ORDER_TYPE_UNSPECIFIED = 0;
  // Market
  ORDER_TYPE_MARKET = 1;
  // Limit
  ORDER_TYPE_LIMIT = 2;
  // Market Stop Order
  ORDER_TYPE_STOP = 3;
  // Stop order limit
  ORDER_TYPE_STOP_LIMIT = 4;
  // Multi-leg request
  ORDER_TYPE_MULTI_LEG = 5;
}

// Order validity period
enum TimeInForce {
  // Value not specified
  TIME_IN_FORCE_UNSPECIFIED = 0;
  // Until the end of the day
  TIME_IN_FORCE_DAY = 1;
  // Good until canceled
  TIME_IN_FORCE_GOOD_TILL_CANCEL = 2;
  // Valid until crossing
  TIME_IN_FORCE_GOOD_TILL_CROSSING = 3;
  // Over-the-counter trading
  TIME_IN_FORCE_EXT = 4;
  // At the opening of the exchange
  TIME_IN_FORCE_ON_OPEN = 5;
  // At the close of the exchange
  TIME_IN_FORCE_ON_CLOSE = 6;
  // Fulfill immediately or cancel
  TIME_IN_FORCE_IOC = 7;
  // Fully fulfill or cancel
  TIME_IN_FORCE_FOK = 8;
}

// Stop order trigger condition
enum StopCondition {
  // Value not specified
  STOP_CONDITION_UNSPECIFIED = 0;
  // Trigger price is greater than the current price
  STOP_CONDITION_LAST_UP = 1;
  // Trigger price is less than the current price
  STOP_CONDITION_LAST_DOWN = 2;
}

// Order Information
message Order {
  // Account ID
  string account_id = 1;
  // Symbol
  string symbol = 2;
  // Quantity in pcs.
  google.type.Decimal quantity = 3;
  // Side (long or short)
  Side side = 4;
  // Order type
  OrderType type = 5;
  // Order validity period
  TimeInForce time_in_force = 6;
  // Required for limit and stop-limit orders
  google.type.Decimal limit_price = 7;
  // Required for stop market and stop limit orders
  google.type.Decimal stop_price = 8;
  // Required for stop market and stop limit orders
  StopCondition stop_condition = 9;
  // Required for multi-leg orders
  repeated Leg legs = 10;
  //  Unique request ID. Automatically generated if not submitted. (Maximum 20 characters)
  string client_order_id = 11;
  // The validity period of a conditional order. This is populated for orders with the ORDER_TYPE_STOP ORDER_TYPE_STOP_LIMIT type.
  ValidBefore valid_before = 12;
  // Order label. (maximum 128 characters)
  string comment = 13;
}

// Leg
message Leg {
  // Symbol
  string symbol = 1;
  // Quantity
  google.type.Decimal quantity = 2;
  // Side
  Side side = 3;
}

// Order Status
enum OrderStatus {
  // Unspecified value
  ORDER_STATUS_UNSPECIFIED = 0;
  // New Request
  ORDER_STATUS_NEW = 1;
  // Partially filled
  ORDER_STATUS_PARTIALLY_FILLED = 2;
  // Fulfilled
  ORDER_STATUS_FILLED = 3;
  // Valid for the day
  ORDER_STATUS_DONE_FOR_DAY = 4;
  // Cancelled
  ORDER_STATUS_CANCELED = 5;
  // Replaced with another
  ORDER_STATUS_REPLACED = 6;
  // Pending Cancel
  ORDER_STATUS_PENDING_CANCEL = 7;
  // Rejected
  ORDER_STATUS_REJECTED = 9;
  // Suspended
  ORDER_STATUS_SUSPENDED = 10;
  // Pending new
  ORDER_STATUS_PENDING_NEW = 11;
  // Expired
  ORDER_STATUS_EXPIRED = 13;
  // Error
  ORDER_STATUS_FAILED = 16;
  // Forwarding
  ORDER_STATUS_FORWARDING = 17;
  // Waiting
  ORDER_STATUS_WAIT = 18;
  // Rejected by broker
  ORDER_STATUS_DENIED_BY_BROKER = 19;
  // Rejected by the exchange
  ORDER_STATUS_REJECTED_BY_EXCHANGE = 20;
  // Watching
  ORDER_STATUS_WATCHING = 21;
  // Executed
  ORDER_STATUS_EXECUTED = 22;
  // Disabled
  ORDER_STATUS_DISABLED = 23;
  // Waiting for link
  ORDER_STATUS_LINK_WAIT = 24;
  // SL Guard Time
  ORDER_STATUS_SL_GUARD_TIME = 27;
  // Executed by SL
  ORDER_STATUS_SL_EXECUTED = 28;
  // SL Forwarding
  ORDER_STATUS_SL_FORWARDING = 29;
  // TP Guard Time
  ORDER_STATUS_TP_GUARD_TIME = 30;
  // Executed by TP
  ORDER_STATUS_TP_EXECUTED = 31;
  // TP correction
  ORDER_STATUS_TP_CORRECTION = 32;
  // TP Forwarding
  ORDER_STATUS_TP_FORWARDING = 33;
  // TP correction during guard time
  ORDER_STATUS_TP_CORR_GUARD_TIME = 34;
}

// Order status
message OrderState {
  // Order ID
  string order_id = 1;
  // Execution ID
  string exec_id = 2;
  // Order Status
  OrderStatus status = 3;
  // Request
  Order order = 4;
  // Date and time of order submission
  google.protobuf.Timestamp transact_at = 5;
  // Date and time of order acceptance
  google.protobuf.Timestamp accept_at = 6;
  // Date and time of order cancellation
  google.protobuf.Timestamp withdraw_at = 7;
  // Initial quantity (filled only for exchange orders)
  google.type.Decimal initial_quantity = 8;
  // Executed volume (filled only for exchange orders)
  google.type.Decimal executed_quantity = 9;
  // Remaining quantity (only filled in for exchange orders)
  google.type.Decimal remaining_quantity = 10;
  // SL/TP Order Information
  SLTPOrder sltp_order = 11;
  // ID of the exchange order generated as a result of a met condition or stop price trigger.
  string triggered_order_id = 12;
}

// Request to receive a list of trade orders
message OrdersRequest {
  // Account ID
  string account_id = 1;
}

// List of trade requests
message OrdersResponse {
  // Orders
  repeated OrderState orders = 1;
}

// Request to cancel a trade order
message CancelOrderRequest {
  // Account ID
  string account_id = 1;
  // Order ID
  string order_id = 2;
}

// Conditional order validity period
enum ValidBefore {
  // Value not specified
  VALID_BEFORE_UNSPECIFIED = 0;
  // Until the end of the trading day
  VALID_BEFORE_END_OF_DAY = 1;
  // Until cancellation
  VALID_BEFORE_GOOD_TILL_CANCEL = 2;
  // Before the specified date and time. This type is only supported when placing SL/TP orders.
  VALID_BEFORE_GOOD_TILL_DATE = 3;
}

// SL/TP Order Information
message SLTPOrder {
  // Account ID
  string account_id = 1;
  // Symbol
  string symbol = 2;
  // Side for both orders
  Side side = 3;
  // Quantity in units for SL
  google.type.Decimal quantity_sl = 4;
  // Price condition parameter for the SL part
  google.type.Decimal sl_price = 5;
  // If specified, after SL activation a limit order will be placed with this price.
  google.type.Decimal limit_price = 6;
  // Quantity in pieces for TP
  google.type.Decimal quantity_tp = 10;
  // Price condition parameter for the TP part
  google.type.Decimal tp_price = 11;
  // If specified, after TP activation, a limit order will be placed taking into account the protective spread.
  google.type.Decimal tp_guard_spread = 12;
  // Unit of measurement of the protective spread
  TPSpreadMeasure tp_spread_measure = 13;
  //  Unique request identifier. Automatically generated if not submitted. (Maximum 20 characters)
  string client_order_id = 20;
  //  Conditional order validity period. If left blank, VALID_BEFORE_GOOD_TILL_CANCEL is set by default.
  ValidBefore valid_before = 21;
  // SL/TP order expiration timestamp
  google.protobuf.Timestamp valid_expiry_time = 22;
  // Order label. (maximum 128 characters)
  string comment = 23;
}

// Unit of measurement of the protective spread for the TP execution price
enum TPSpreadMeasure {
  // Value not specified
  TP_SPREAD_MEASURE_UNDEFINED = 0;
  // in price units
  TP_SPREAD_MEASURE_VALUE = 1;
  //  as a percentage with maximum accuracy to hundredths of a percent
  TP_SPREAD_MEASURE_PERCENT = 2;
}

