syntax = "proto3";

package grpc.tradeapi.v1.reports;

import "google/api/annotations.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/wrappers.proto";
import "grpc/gateway/protoc_gen_openapiv2/options/annotations.proto";

option go_package = "github.com/your-organization/trade-api/go/grpc/tradeapi/v1/reports";
option java_multiple_files = true;
option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  schemes: [
    HTTP,
    HTTPS
  ]
  info: {
    title: "Trade API"
    description: "API for trading operations"
  }
  security_definitions: {
    security: {
      key: "Authorization"
      value: {
        type: TYPE_API_KEY
        in: IN_HEADER
        name: "Authorization"
        description: "JWT authorization token"
      }
    }
  }
  responses: [
    {
      key: "default"
      value: {
        schema: {
          json_schema: {
            ref: "googletypeStatus"
          }
        }
      }
    },
    {
      key: "500"
      value: {
        description: "Internal service error. Try again later."
      }
    },
    {
      key: "503"
      value: {
        description: "The service is currently unavailable. Try again later."
      }
    },
    {
      key: "429"
      value: {
        description: "Request limit exceeded."
      }
    },
    {
      key: "401"
      value: {
        description: "The token has expired or is invalid."
      }
    },
    {
      key: "504"
      value: {
        description: "The deadline was exceeded before the operation completed."
      }
    }
  ]
};

// Service for receiving custom reports.
service ReportsService {
  // Start generating an account report for the period
  // Example HTTP request:
  // POST /v1/report
  // Authorization: <token>
  rpc CreateAccountReport(CreateAccountReportRequest) returns (CreateAccountReportResponse) {
    option (google.api.http) = {
      post: "/v1/report"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      security: [
        {
          security_requirement: {
            key: "Authorization"
          }
        }
      ]
    };
  };

  // Get the account report generation result
  // Example HTTP request:
  // GET /v1/report/01KBMPQ3CEZ4BBCVGBW5JS8S8Y/info
  // Authorization: <token>
  rpc GetAccountReportInfo(GetAccountReportInfoRequest) returns (GetAccountReportInfoResponse) {
    option (google.api.http) = {
      get: "/v1/report/{report_id}/info"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      security: [
        {
          security_requirement: {
            key: "Authorization"
          }
        }
      ]
    };
  };

  // Subscribe to information about the results of generating an account report. Stream method
  rpc SubscribeAccountReportInfo(SubscribeAccountReportInfoRequest) returns (stream SubscribeAccountReportInfoResponse);

}

// Request to generate an account report for a period
message CreateAccountReportRequest {
  // Time interval. Maximum date interval - 92 days
  DateRange date_range = 1;
  // Report form
  ReportForm report_form = 2;
  // Account ID
  int64 account_id = 3;
}

// Information about the generated report
message CreateAccountReportResponse {
  // Report ID
  string report_id = 1;
}

// Request for report generation status
message GetAccountReportInfoRequest {
  // Report ID
  string report_id = 1;
}

// Information about the report generation status
message GetAccountReportInfoResponse {
  // Information about the report generation status
  AccountReportInfo info = 1;
}

// Request to subscribe to receive report generation status
message SubscribeAccountReportInfoRequest {
  // Report ID
  string report_id = 1;
}

// Information about the report generation status. Stream
message SubscribeAccountReportInfoResponse {
  // Information about the report generation status
  AccountReportInfo info = 1;
}

// Information about the report generation status
message AccountReportInfo {
  // Report ID
  string report_id = 1;
  // Report generation status
  ReportCreationStatus status = 2;
  // Report time interval. Taken from the report generation request
  DateRange date_range = 3;
  // Report form. Taken from the report generation request
  ReportForm report_form = 4;
  // Account ID. Taken from the report generation request
  int64 account_id = 5;
  // Link to download the report. Appears only if the report is successfully generated (ReportCreationStatus = SUCCESS). To download the report using this link, you must pass the Authorization header: Bearer <your_access_key>
  google.protobuf.StringValue url = 6;
}

// Time interval
message DateRange {
  // Time interval start date
  google.protobuf.Timestamp date_begin = 1;
  // End date of the time interval
  google.protobuf.Timestamp date_end = 2;
}

// Report form
enum ReportForm {
  // Not specified
  REPORT_FORM_UNKNOWN = 0;
  // Brief
  REPORT_FORM_SHORT = 1;
  // Full
  REPORT_FORM_LONG = 2;
}

// Report generation status
enum ReportCreationStatus {
  // Not found
  NOT_FOUND = 0;
  // Waiting to be generated
  PENDING = 1;
  // Generation started
  IN_PROGRESS = 2;
  // Generation completed successfully
  SUCCESS = 3;
  // Generation completed with error
  ERROR = 4;
}
