// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: grpc/tradeapi/v1/orders/orders_service.proto

package orders

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	v1 "github.com/your-organization/trade-api/go/grpc/tradeapi/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	decimal "google.golang.org/genproto/googleapis/type/decimal"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Order type
type OrderType int32

const (
	// Unspecified value
	OrderType_ORDER_TYPE_UNSPECIFIED OrderType = 0
	// Market
	OrderType_ORDER_TYPE_MARKET OrderType = 1
	// Limit
	OrderType_ORDER_TYPE_LIMIT OrderType = 2
	// Stop market order
	OrderType_ORDER_TYPE_STOP OrderType = 3
	// Stop limit order
	OrderType_ORDER_TYPE_STOP_LIMIT OrderType = 4
	// Multi leg order
	OrderType_ORDER_TYPE_MULTI_LEG OrderType = 5
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "ORDER_TYPE_UNSPECIFIED",
		1: "ORDER_TYPE_MARKET",
		2: "ORDER_TYPE_LIMIT",
		3: "ORDER_TYPE_STOP",
		4: "ORDER_TYPE_STOP_LIMIT",
		5: "ORDER_TYPE_MULTI_LEG",
	}
	OrderType_value = map[string]int32{
		"ORDER_TYPE_UNSPECIFIED": 0,
		"ORDER_TYPE_MARKET":      1,
		"ORDER_TYPE_LIMIT":       2,
		"ORDER_TYPE_STOP":        3,
		"ORDER_TYPE_STOP_LIMIT":  4,
		"ORDER_TYPE_MULTI_LEG":   5,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_tradeapi_v1_orders_orders_service_proto_enumTypes[0].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_grpc_tradeapi_v1_orders_orders_service_proto_enumTypes[0]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_orders_orders_service_proto_rawDescGZIP(), []int{0}
}

// Order validity period
type TimeInForce int32

const (
	// Unspecified value
	TimeInForce_TIME_IN_FORCE_UNSPECIFIED TimeInForce = 0
	// Until the end of the day
	TimeInForce_TIME_IN_FORCE_DAY TimeInForce = 1
	// Valid until canceled
	TimeInForce_TIME_IN_FORCE_GOOD_TILL_CANCEL TimeInForce = 2
	// Valid until crossing
	TimeInForce_TIME_IN_FORCE_GOOD_TILL_CROSSING TimeInForce = 3
	// OTC trading
	TimeInForce_TIME_IN_FORCE_EXT TimeInForce = 4
	// At market open
	TimeInForce_TIME_IN_FORCE_ON_OPEN TimeInForce = 5
	// At market close
	TimeInForce_TIME_IN_FORCE_ON_CLOSE TimeInForce = 6
	// Execute immediately or cancel
	TimeInForce_TIME_IN_FORCE_IOC TimeInForce = 7
	// Execute in full or cancel
	TimeInForce_TIME_IN_FORCE_FOK TimeInForce = 8
)

// Enum value maps for TimeInForce.
var (
	TimeInForce_name = map[int32]string{
		0: "TIME_IN_FORCE_UNSPECIFIED",
		1: "TIME_IN_FORCE_DAY",
		2: "TIME_IN_FORCE_GOOD_TILL_CANCEL",
		3: "TIME_IN_FORCE_GOOD_TILL_CROSSING",
		4: "TIME_IN_FORCE_EXT",
		5: "TIME_IN_FORCE_ON_OPEN",
		6: "TIME_IN_FORCE_ON_CLOSE",
		7: "TIME_IN_FORCE_IOC",
		8: "TIME_IN_FORCE_FOK",
	}
	TimeInForce_value = map[string]int32{
		"TIME_IN_FORCE_UNSPECIFIED":        0,
		"TIME_IN_FORCE_DAY":                1,
		"TIME_IN_FORCE_GOOD_TILL_CANCEL":   2,
		"TIME_IN_FORCE_GOOD_TILL_CROSSING": 3,
		"TIME_IN_FORCE_EXT":                4,
		"TIME_IN_FORCE_ON_OPEN":            5,
		"TIME_IN_FORCE_ON_CLOSE":           6,
		"TIME_IN_FORCE_IOC":                7,
		"TIME_IN_FORCE_FOK":                8,
	}
)

func (x TimeInForce) Enum() *TimeInForce {
	p := new(TimeInForce)
	*p = x
	return p
}

func (x TimeInForce) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeInForce) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_tradeapi_v1_orders_orders_service_proto_enumTypes[1].Descriptor()
}

func (TimeInForce) Type() protoreflect.EnumType {
	return &file_grpc_tradeapi_v1_orders_orders_service_proto_enumTypes[1]
}

func (x TimeInForce) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeInForce.Descriptor instead.
func (TimeInForce) EnumDescriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_orders_orders_service_proto_rawDescGZIP(), []int{1}
}

// Condition for triggering a stop order
type StopCondition int32

const (
	// Unspecified value
	StopCondition_STOP_CONDITION_UNSPECIFIED StopCondition = 0
	// The trigger price is higher than the current price
	StopCondition_STOP_CONDITION_LAST_UP StopCondition = 1
	// The trigger price is less than the current price
	StopCondition_STOP_CONDITION_LAST_DOWN StopCondition = 2
)

// Enum value maps for StopCondition.
var (
	StopCondition_name = map[int32]string{
		0: "STOP_CONDITION_UNSPECIFIED",
		1: "STOP_CONDITION_LAST_UP",
		2: "STOP_CONDITION_LAST_DOWN",
	}
	StopCondition_value = map[string]int32{
		"STOP_CONDITION_UNSPECIFIED": 0,
		"STOP_CONDITION_LAST_UP":     1,
		"STOP_CONDITION_LAST_DOWN":   2,
	}
)

func (x StopCondition) Enum() *StopCondition {
	p := new(StopCondition)
	*p = x
	return p
}

func (x StopCondition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StopCondition) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_tradeapi_v1_orders_orders_service_proto_enumTypes[2].Descriptor()
}

func (StopCondition) Type() protoreflect.EnumType {
	return &file_grpc_tradeapi_v1_orders_orders_service_proto_enumTypes[2]
}

func (x StopCondition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StopCondition.Descriptor instead.
func (StopCondition) EnumDescriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_orders_orders_service_proto_rawDescGZIP(), []int{2}
}

// Order status
type OrderStatus int32

const (
	// Undefined value
	OrderStatus_ORDER_STATUS_UNSPECIFIED OrderStatus = 0
	// New order
	OrderStatus_ORDER_STATUS_NEW OrderStatus = 1
	// Partially executed
	OrderStatus_ORDER_STATUS_PARTIALLY_FILLED OrderStatus = 2
	// Fulfilled
	OrderStatus_ORDER_STATUS_FILLED OrderStatus = 3
	// Done for the day
	OrderStatus_ORDER_STATUS_DONE_FOR_DAY OrderStatus = 4
	// Canceled
	OrderStatus_ORDER_STATUS_CANCELED OrderStatus = 5
	// Replaced with another
	OrderStatus_ORDER_STATUS_REPLACED OrderStatus = 6
	// Pending cancellation
	OrderStatus_ORDER_STATUS_PENDING_CANCEL OrderStatus = 7
	// Rejected
	OrderStatus_ORDER_STATUS_REJECTED OrderStatus = 9
	// Suspended
	OrderStatus_ORDER_STATUS_SUSPENDED OrderStatus = 10
	// Waiting for a new one
	OrderStatus_ORDER_STATUS_PENDING_NEW OrderStatus = 11
	// Expired
	OrderStatus_ORDER_STATUS_EXPIRED OrderStatus = 13
	// Error
	OrderStatus_ORDER_STATUS_FAILED OrderStatus = 16
	// Forwarding
	OrderStatus_ORDER_STATUS_FORWARDING OrderStatus = 17
	// Waiting
	OrderStatus_ORDER_STATUS_WAIT OrderStatus = 18
	// Rejected by broker
	OrderStatus_ORDER_STATUS_DENIED_BY_BROKER OrderStatus = 19
	// Rejected by the exchange
	OrderStatus_ORDER_STATUS_REJECTED_BY_EXCHANGE OrderStatus = 20
	// Watching
	OrderStatus_ORDER_STATUS_WATCHING OrderStatus = 21
	// Fulfilled
	OrderStatus_ORDER_STATUS_EXECUTED OrderStatus = 22
	// Disabled
	OrderStatus_ORDER_STATUS_DISABLED OrderStatus = 23
	// Waiting for link
	OrderStatus_ORDER_STATUS_LINK_WAIT OrderStatus = 24
	// Protective time SL
	OrderStatus_ORDER_STATUS_SL_GUARD_TIME OrderStatus = 27
	// Executed according to SL
	OrderStatus_ORDER_STATUS_SL_EXECUTED OrderStatus = 28
	// SL forwarding
	OrderStatus_ORDER_STATUS_SL_FORWARDING OrderStatus = 29
	// Protective time TP
	OrderStatus_ORDER_STATUS_TP_GUARD_TIME OrderStatus = 30
	// Executed according to TP
	OrderStatus_ORDER_STATUS_TP_EXECUTED OrderStatus = 31
	// TP correction
	OrderStatus_ORDER_STATUS_TP_CORRECTION OrderStatus = 32
	// TP forwarding
	OrderStatus_ORDER_STATUS_TP_FORWARDING OrderStatus = 33
	// TP correction during protective time
	OrderStatus_ORDER_STATUS_TP_CORR_GUARD_TIME OrderStatus = 34
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0:  "ORDER_STATUS_UNSPECIFIED",
		1:  "ORDER_STATUS_NEW",
		2:  "ORDER_STATUS_PARTIALLY_FILLED",
		3:  "ORDER_STATUS_FILLED",
		4:  "ORDER_STATUS_DONE_FOR_DAY",
		5:  "ORDER_STATUS_CANCELED",
		6:  "ORDER_STATUS_REPLACED",
		7:  "ORDER_STATUS_PENDING_CANCEL",
		9:  "ORDER_STATUS_REJECTED",
		10: "ORDER_STATUS_SUSPENDED",
		11: "ORDER_STATUS_PENDING_NEW",
		13: "ORDER_STATUS_EXPIRED",
		16: "ORDER_STATUS_FAILED",
		17: "ORDER_STATUS_FORWARDING",
		18: "ORDER_STATUS_WAIT",
		19: "ORDER_STATUS_DENIED_BY_BROKER",
		20: "ORDER_STATUS_REJECTED_BY_EXCHANGE",
		21: "ORDER_STATUS_WATCHING",
		22: "ORDER_STATUS_EXECUTED",
		23: "ORDER_STATUS_DISABLED",
		24: "ORDER_STATUS_LINK_WAIT",
		27: "ORDER_STATUS_SL_GUARD_TIME",
		28: "ORDER_STATUS_SL_EXECUTED",
		29: "ORDER_STATUS_SL_FORWARDING",
		30: "ORDER_STATUS_TP_GUARD_TIME",
		31: "ORDER_STATUS_TP_EXECUTED",
		32: "ORDER_STATUS_TP_CORRECTION",
		33: "ORDER_STATUS_TP_FORWARDING",
		34: "ORDER_STATUS_TP_CORR_GUARD_TIME",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED":          0,
		"ORDER_STATUS_NEW":                  1,
		"ORDER_STATUS_PARTIALLY_FILLED":     2,
		"ORDER_STATUS_FILLED":               3,
		"ORDER_STATUS_DONE_FOR_DAY":         4,
		"ORDER_STATUS_CANCELED":             5,
		"ORDER_STATUS_REPLACED":             6,
		"ORDER_STATUS_PENDING_CANCEL":       7,
		"ORDER_STATUS_REJECTED":             9,
		"ORDER_STATUS_SUSPENDED":            10,
		"ORDER_STATUS_PENDING_NEW":          11,
		"ORDER_STATUS_EXPIRED":              13,
		"ORDER_STATUS_FAILED":               16,
		"ORDER_STATUS_FORWARDING":           17,
		"ORDER_STATUS_WAIT":                 18,
		"ORDER_STATUS_DENIED_BY_BROKER":     19,
		"ORDER_STATUS_REJECTED_BY_EXCHANGE": 20,
		"ORDER_STATUS_WATCHING":             21,
		"ORDER_STATUS_EXECUTED":             22,
		"ORDER_STATUS_DISABLED":             23,
		"ORDER_STATUS_LINK_WAIT":            24,
		"ORDER_STATUS_SL_GUARD_TIME":        27,
		"ORDER_STATUS_SL_EXECUTED":          28,
		"ORDER_STATUS_SL_FORWARDING":        29,
		"ORDER_STATUS_TP_GUARD_TIME":        30,
		"ORDER_STATUS_TP_EXECUTED":          31,
		"ORDER_STATUS_TP_CORRECTION":        32,
		"ORDER_STATUS_TP_FORWARDING":        33,
		"ORDER_STATUS_TP_CORR_GUARD_TIME":   34,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_tradeapi_v1_orders_orders_service_proto_enumTypes[3].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_grpc_tradeapi_v1_orders_orders_service_proto_enumTypes[3]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_orders_orders_service_proto_rawDescGZIP(), []int{3}
}

// Validity period of the conditional order
type ValidBefore int32

const (
	// Unspecified value
	ValidBefore_VALID_BEFORE_UNSPECIFIED ValidBefore = 0
	// Until the end of the trading day
	ValidBefore_VALID_BEFORE_END_OF_DAY ValidBefore = 1
	// Before cancellation
	ValidBefore_VALID_BEFORE_GOOD_TILL_CANCEL ValidBefore = 2
	// Before the specified date and time. This type is supported only when placing SL/TP orders
	ValidBefore_VALID_BEFORE_GOOD_TILL_DATE ValidBefore = 3
)

// Enum value maps for ValidBefore.
var (
	ValidBefore_name = map[int32]string{
		0: "VALID_BEFORE_UNSPECIFIED",
		1: "VALID_BEFORE_END_OF_DAY",
		2: "VALID_BEFORE_GOOD_TILL_CANCEL",
		3: "VALID_BEFORE_GOOD_TILL_DATE",
	}
	ValidBefore_value = map[string]int32{
		"VALID_BEFORE_UNSPECIFIED":      0,
		"VALID_BEFORE_END_OF_DAY":       1,
		"VALID_BEFORE_GOOD_TILL_CANCEL": 2,
		"VALID_BEFORE_GOOD_TILL_DATE":   3,
	}
)

func (x ValidBefore) Enum() *ValidBefore {
	p := new(ValidBefore)
	*p = x
	return p
}

func (x ValidBefore) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidBefore) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_tradeapi_v1_orders_orders_service_proto_enumTypes[4].Descriptor()
}

func (ValidBefore) Type() protoreflect.EnumType {
	return &file_grpc_tradeapi_v1_orders_orders_service_proto_enumTypes[4]
}

func (x ValidBefore) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidBefore.Descriptor instead.
func (ValidBefore) EnumDescriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_orders_orders_service_proto_rawDescGZIP(), []int{4}
}

// Unit used to measure the take-profit protective spread
type TPSpreadMeasure int32

const (
	// Unspecified value
	TPSpreadMeasure_TP_SPREAD_MEASURE_UNDEFINED TPSpreadMeasure = 0
	// Price units
	TPSpreadMeasure_TP_SPREAD_MEASURE_VALUE TPSpreadMeasure = 1
	// Percent, with precision to one hundredth of a percent
	TPSpreadMeasure_TP_SPREAD_MEASURE_PERCENT TPSpreadMeasure = 2
)

// Enum value maps for TPSpreadMeasure.
var (
	TPSpreadMeasure_name = map[int32]string{
		0: "TP_SPREAD_MEASURE_UNDEFINED",
		1: "TP_SPREAD_MEASURE_VALUE",
		2: "TP_SPREAD_MEASURE_PERCENT",
	}
	TPSpreadMeasure_value = map[string]int32{
		"TP_SPREAD_MEASURE_UNDEFINED": 0,
		"TP_SPREAD_MEASURE_VALUE":     1,
		"TP_SPREAD_MEASURE_PERCENT":   2,
	}
)

func (x TPSpreadMeasure) Enum() *TPSpreadMeasure {
	p := new(TPSpreadMeasure)
	*p = x
	return p
}

func (x TPSpreadMeasure) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TPSpreadMeasure) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_tradeapi_v1_orders_orders_service_proto_enumTypes[5].Descriptor()
}

func (TPSpreadMeasure) Type() protoreflect.EnumType {
	return &file_grpc_tradeapi_v1_orders_orders_service_proto_enumTypes[5]
}

func (x TPSpreadMeasure) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TPSpreadMeasure.Descriptor instead.
func (TPSpreadMeasure) EnumDescriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_orders_orders_service_proto_rawDescGZIP(), []int{5}
}

// Available actions
type OrderTradeRequest_Action int32

const (
	// Subscribe
	OrderTradeRequest_ACTION_SUBSCRIBE OrderTradeRequest_Action = 0
	// Unsubscribe
	OrderTradeRequest_ACTION_UNSUBSCRIBE OrderTradeRequest_Action = 1
)

// Enum value maps for OrderTradeRequest_Action.
var (
	OrderTradeRequest_Action_name = map[int32]string{
		0: "ACTION_SUBSCRIBE",
		1: "ACTION_UNSUBSCRIBE",
	}
	OrderTradeRequest_Action_value = map[string]int32{
		"ACTION_SUBSCRIBE":   0,
		"ACTION_UNSUBSCRIBE": 1,
	}
)

func (x OrderTradeRequest_Action) Enum() *OrderTradeRequest_Action {
	p := new(OrderTradeRequest_Action)
	*p = x
	return p
}

func (x OrderTradeRequest_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderTradeRequest_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_tradeapi_v1_orders_orders_service_proto_enumTypes[6].Descriptor()
}

func (OrderTradeRequest_Action) Type() protoreflect.EnumType {
	return &file_grpc_tradeapi_v1_orders_orders_service_proto_enumTypes[6]
}

func (x OrderTradeRequest_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderTradeRequest_Action.Descriptor instead.
func (OrderTradeRequest_Action) EnumDescriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_orders_orders_service_proto_rawDescGZIP(), []int{0, 0}
}

// Subscription type
type OrderTradeRequest_DataType int32

const (
	// All orders and trades
	OrderTradeRequest_DATA_TYPE_ALL OrderTradeRequest_DataType = 0
	// Order
	OrderTradeRequest_DATA_TYPE_ORDERS OrderTradeRequest_DataType = 1
	// Trade
	OrderTradeRequest_DATA_TYPE_TRADES OrderTradeRequest_DataType = 2
)

// Enum value maps for OrderTradeRequest_DataType.
var (
	OrderTradeRequest_DataType_name = map[int32]string{
		0: "DATA_TYPE_ALL",
		1: "DATA_TYPE_ORDERS",
		2: "DATA_TYPE_TRADES",
	}
	OrderTradeRequest_DataType_value = map[string]int32{
		"DATA_TYPE_ALL":    0,
		"DATA_TYPE_ORDERS": 1,
		"DATA_TYPE_TRADES": 2,
	}
)

func (x OrderTradeRequest_DataType) Enum() *OrderTradeRequest_DataType {
	p := new(OrderTradeRequest_DataType)
	*p = x
	return p
}

func (x OrderTradeRequest_DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderTradeRequest_DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_tradeapi_v1_orders_orders_service_proto_enumTypes[7].Descriptor()
}

func (OrderTradeRequest_DataType) Type() protoreflect.EnumType {
	return &file_grpc_tradeapi_v1_orders_orders_service_proto_enumTypes[7]
}

func (x OrderTradeRequest_DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderTradeRequest_DataType.Descriptor instead.
func (OrderTradeRequest_DataType) EnumDescriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_orders_orders_service_proto_rawDescGZIP(), []int{0, 1}
}

// Request an account order-and-trade subscription. Stream
//
// Deprecated: Marked as deprecated in grpc/tradeapi/v1/orders/orders_service.proto.
type OrderTradeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Changing subscription status: subscribe/unsubscribe
	Action OrderTradeRequest_Action `protobuf:"varint,1,opt,name=action,proto3,enum=grpc.tradeapi.v1.orders.OrderTradeRequest_Action" json:"action,omitempty"`
	// Select orders, trades, or both
	DataType OrderTradeRequest_DataType `protobuf:"varint,2,opt,name=data_type,json=dataType,proto3,enum=grpc.tradeapi.v1.orders.OrderTradeRequest_DataType" json:"data_type,omitempty"`
	// Account ID
	AccountId     string `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderTradeRequest) Reset() {
	*x = OrderTradeRequest{}
	mi := &file_grpc_tradeapi_v1_orders_orders_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderTradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderTradeRequest) ProtoMessage() {}

func (x *OrderTradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_orders_orders_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderTradeRequest.ProtoReflect.Descriptor instead.
func (*OrderTradeRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_orders_orders_service_proto_rawDescGZIP(), []int{0}
}

func (x *OrderTradeRequest) GetAction() OrderTradeRequest_Action {
	if x != nil {
		return x.Action
	}
	return OrderTradeRequest_ACTION_SUBSCRIBE
}

func (x *OrderTradeRequest) GetDataType() OrderTradeRequest_DataType {
	if x != nil {
		return x.DataType
	}
	return OrderTradeRequest_DATA_TYPE_ALL
}

func (x *OrderTradeRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

// Account orders and trades
//
// Deprecated: Marked as deprecated in grpc/tradeapi/v1/orders/orders_service.proto.
type OrderTradeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Order
	Orders []*OrderState `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	// Trade
	Trades        []*v1.AccountTrade `protobuf:"bytes,2,rep,name=trades,proto3" json:"trades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderTradeResponse) Reset() {
	*x = OrderTradeResponse{}
	mi := &file_grpc_tradeapi_v1_orders_orders_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderTradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderTradeResponse) ProtoMessage() {}

func (x *OrderTradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_orders_orders_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderTradeResponse.ProtoReflect.Descriptor instead.
func (*OrderTradeResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_orders_orders_service_proto_rawDescGZIP(), []int{1}
}

func (x *OrderTradeResponse) GetOrders() []*OrderState {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *OrderTradeResponse) GetTrades() []*v1.AccountTrade {
	if x != nil {
		return x.Trades
	}
	return nil
}

// Request an account-order subscription. Stream
type SubscribeOrdersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Account ID
	AccountId     string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeOrdersRequest) Reset() {
	*x = SubscribeOrdersRequest{}
	mi := &file_grpc_tradeapi_v1_orders_orders_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeOrdersRequest) ProtoMessage() {}

func (x *SubscribeOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_orders_orders_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeOrdersRequest.ProtoReflect.Descriptor instead.
func (*SubscribeOrdersRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_orders_orders_service_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeOrdersRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

// List of the account's orders
type SubscribeOrdersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Order
	Orders        []*OrderState `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeOrdersResponse) Reset() {
	*x = SubscribeOrdersResponse{}
	mi := &file_grpc_tradeapi_v1_orders_orders_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeOrdersResponse) ProtoMessage() {}

func (x *SubscribeOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_orders_orders_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeOrdersResponse.ProtoReflect.Descriptor instead.
func (*SubscribeOrdersResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_orders_orders_service_proto_rawDescGZIP(), []int{3}
}

func (x *SubscribeOrdersResponse) GetOrders() []*OrderState {
	if x != nil {
		return x.Orders
	}
	return nil
}

// Request an account-trade subscription. Stream
type SubscribeTradesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Account ID
	AccountId     string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeTradesRequest) Reset() {
	*x = SubscribeTradesRequest{}
	mi := &file_grpc_tradeapi_v1_orders_orders_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeTradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeTradesRequest) ProtoMessage() {}

func (x *SubscribeTradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_orders_orders_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeTradesRequest.ProtoReflect.Descriptor instead.
func (*SubscribeTradesRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_orders_orders_service_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribeTradesRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

// List of own trades
type SubscribeTradesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Trade
	Trades        []*v1.AccountTrade `protobuf:"bytes,1,rep,name=trades,proto3" json:"trades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeTradesResponse) Reset() {
	*x = SubscribeTradesResponse{}
	mi := &file_grpc_tradeapi_v1_orders_orders_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeTradesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeTradesResponse) ProtoMessage() {}

func (x *SubscribeTradesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_orders_orders_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeTradesResponse.ProtoReflect.Descriptor instead.
func (*SubscribeTradesResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_orders_orders_service_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribeTradesResponse) GetTrades() []*v1.AccountTrade {
	if x != nil {
		return x.Trades
	}
	return nil
}

// Request for a specific order
type GetOrderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Account ID
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Order ID
	OrderId       string `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_grpc_tradeapi_v1_orders_orders_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_orders_orders_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_orders_orders_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrderRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

// Order information
type Order struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Account ID
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Instrument symbol
	Symbol string `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Quantity in units
	Quantity *decimal.Decimal `protobuf:"bytes,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// Side (long or short)
	Side v1.Side `protobuf:"varint,4,opt,name=side,proto3,enum=grpc.tradeapi.v1.Side" json:"side,omitempty"`
	// Order type
	Type OrderType `protobuf:"varint,5,opt,name=type,proto3,enum=grpc.tradeapi.v1.orders.OrderType" json:"type,omitempty"`
	// Order validity period
	TimeInForce TimeInForce `protobuf:"varint,6,opt,name=time_in_force,json=timeInForce,proto3,enum=grpc.tradeapi.v1.orders.TimeInForce" json:"time_in_force,omitempty"`
	// Required for limit and stop limit orders
	LimitPrice *decimal.Decimal `protobuf:"bytes,7,opt,name=limit_price,json=limitPrice,proto3" json:"limit_price,omitempty"`
	// Required for market stops and limit order stops
	StopPrice *decimal.Decimal `protobuf:"bytes,8,opt,name=stop_price,json=stopPrice,proto3" json:"stop_price,omitempty"`
	// Required for market stops and limit order stops
	StopCondition StopCondition `protobuf:"varint,9,opt,name=stop_condition,json=stopCondition,proto3,enum=grpc.tradeapi.v1.orders.StopCondition" json:"stop_condition,omitempty"`
	// Required for multi leg order
	Legs []*Leg `protobuf:"bytes,10,rep,name=legs,proto3" json:"legs,omitempty"`
	// Unique identifier of the order. Automatically generated if not sent. (maximum 20 characters)
	ClientOrderId string `protobuf:"bytes,11,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"`
	// Conditional-order validity, populated for ORDER_TYPE_STOP and ORDER_TYPE_STOP_LIMIT
	ValidBefore ValidBefore `protobuf:"varint,12,opt,name=valid_before,json=validBefore,proto3,enum=grpc.tradeapi.v1.orders.ValidBefore" json:"valid_before,omitempty"`
	// Order comment (maximum 128 characters)
	Comment       string `protobuf:"bytes,13,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_grpc_tradeapi_v1_orders_orders_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_orders_orders_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_orders_orders_service_proto_rawDescGZIP(), []int{7}
}

func (x *Order) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Order) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Order) GetQuantity() *decimal.Decimal {
	if x != nil {
		return x.Quantity
	}
	return nil
}

func (x *Order) GetSide() v1.Side {
	if x != nil {
		return x.Side
	}
	return v1.Side(0)
}

func (x *Order) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *Order) GetTimeInForce() TimeInForce {
	if x != nil {
		return x.TimeInForce
	}
	return TimeInForce_TIME_IN_FORCE_UNSPECIFIED
}

func (x *Order) GetLimitPrice() *decimal.Decimal {
	if x != nil {
		return x.LimitPrice
	}
	return nil
}

func (x *Order) GetStopPrice() *decimal.Decimal {
	if x != nil {
		return x.StopPrice
	}
	return nil
}

func (x *Order) GetStopCondition() StopCondition {
	if x != nil {
		return x.StopCondition
	}
	return StopCondition_STOP_CONDITION_UNSPECIFIED
}

func (x *Order) GetLegs() []*Leg {
	if x != nil {
		return x.Legs
	}
	return nil
}

func (x *Order) GetClientOrderId() string {
	if x != nil {
		return x.ClientOrderId
	}
	return ""
}

func (x *Order) GetValidBefore() ValidBefore {
	if x != nil {
		return x.ValidBefore
	}
	return ValidBefore_VALID_BEFORE_UNSPECIFIED
}

func (x *Order) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

// Multi-leg order leg
type Leg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Instrument symbol
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Quantity
	Quantity *decimal.Decimal `protobuf:"bytes,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// Side
	Side          v1.Side `protobuf:"varint,3,opt,name=side,proto3,enum=grpc.tradeapi.v1.Side" json:"side,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Leg) Reset() {
	*x = Leg{}
	mi := &file_grpc_tradeapi_v1_orders_orders_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Leg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Leg) ProtoMessage() {}

func (x *Leg) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_orders_orders_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Leg.ProtoReflect.Descriptor instead.
func (*Leg) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_orders_orders_service_proto_rawDescGZIP(), []int{8}
}

func (x *Leg) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Leg) GetQuantity() *decimal.Decimal {
	if x != nil {
		return x.Quantity
	}
	return nil
}

func (x *Leg) GetSide() v1.Side {
	if x != nil {
		return x.Side
	}
	return v1.Side(0)
}

// Order status
type OrderState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Order ID
	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// Execution ID
	ExecId string `protobuf:"bytes,2,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	// Order status
	Status OrderStatus `protobuf:"varint,3,opt,name=status,proto3,enum=grpc.tradeapi.v1.orders.OrderStatus" json:"status,omitempty"`
	// Order
	Order *Order `protobuf:"bytes,4,opt,name=order,proto3" json:"order,omitempty"`
	// Date and time of order
	TransactAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=transact_at,json=transactAt,proto3" json:"transact_at,omitempty"`
	// Date and time of order acceptance
	AcceptAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=accept_at,json=acceptAt,proto3" json:"accept_at,omitempty"`
	// Date and time of cancellation of the order
	WithdrawAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=withdraw_at,json=withdrawAt,proto3" json:"withdraw_at,omitempty"`
	// Initial quantity, populated only for exchange orders
	InitialQuantity *decimal.Decimal `protobuf:"bytes,8,opt,name=initial_quantity,json=initialQuantity,proto3" json:"initial_quantity,omitempty"`
	// Executed quantity, populated only for exchange orders
	ExecutedQuantity *decimal.Decimal `protobuf:"bytes,9,opt,name=executed_quantity,json=executedQuantity,proto3" json:"executed_quantity,omitempty"`
	// Remaining quantity, populated only for exchange orders
	RemainingQuantity *decimal.Decimal `protobuf:"bytes,10,opt,name=remaining_quantity,json=remainingQuantity,proto3" json:"remaining_quantity,omitempty"`
	// Information about SL/TP order
	SltpOrder *SLTPOrder `protobuf:"bytes,11,opt,name=sltp_order,json=sltpOrder,proto3" json:"sltp_order,omitempty"`
	// Identifier of an exchange order generated as a result of a condition being triggered or a stop price being reached.
	TriggeredOrderId string `protobuf:"bytes,12,opt,name=triggered_order_id,json=triggeredOrderId,proto3" json:"triggered_order_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OrderState) Reset() {
	*x = OrderState{}
	mi := &file_grpc_tradeapi_v1_orders_orders_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderState) ProtoMessage() {}

func (x *OrderState) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_orders_orders_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderState.ProtoReflect.Descriptor instead.
func (*OrderState) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_orders_orders_service_proto_rawDescGZIP(), []int{9}
}

func (x *OrderState) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderState) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *OrderState) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *OrderState) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *OrderState) GetTransactAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TransactAt
	}
	return nil
}

func (x *OrderState) GetAcceptAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AcceptAt
	}
	return nil
}

func (x *OrderState) GetWithdrawAt() *timestamppb.Timestamp {
	if x != nil {
		return x.WithdrawAt
	}
	return nil
}

func (x *OrderState) GetInitialQuantity() *decimal.Decimal {
	if x != nil {
		return x.InitialQuantity
	}
	return nil
}

func (x *OrderState) GetExecutedQuantity() *decimal.Decimal {
	if x != nil {
		return x.ExecutedQuantity
	}
	return nil
}

func (x *OrderState) GetRemainingQuantity() *decimal.Decimal {
	if x != nil {
		return x.RemainingQuantity
	}
	return nil
}

func (x *OrderState) GetSltpOrder() *SLTPOrder {
	if x != nil {
		return x.SltpOrder
	}
	return nil
}

func (x *OrderState) GetTriggeredOrderId() string {
	if x != nil {
		return x.TriggeredOrderId
	}
	return ""
}

// Request account orders
type OrdersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Account ID
	AccountId     string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrdersRequest) Reset() {
	*x = OrdersRequest{}
	mi := &file_grpc_tradeapi_v1_orders_orders_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdersRequest) ProtoMessage() {}

func (x *OrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_orders_orders_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdersRequest.ProtoReflect.Descriptor instead.
func (*OrdersRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_orders_orders_service_proto_rawDescGZIP(), []int{10}
}

func (x *OrdersRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

// Account orders
type OrdersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Order
	Orders        []*OrderState `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrdersResponse) Reset() {
	*x = OrdersResponse{}
	mi := &file_grpc_tradeapi_v1_orders_orders_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdersResponse) ProtoMessage() {}

func (x *OrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_orders_orders_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdersResponse.ProtoReflect.Descriptor instead.
func (*OrdersResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_orders_orders_service_proto_rawDescGZIP(), []int{11}
}

func (x *OrdersResponse) GetOrders() []*OrderState {
	if x != nil {
		return x.Orders
	}
	return nil
}

// Request order cancellation
type CancelOrderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Account ID
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Order ID
	OrderId       string `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_grpc_tradeapi_v1_orders_orders_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_orders_orders_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_orders_orders_service_proto_rawDescGZIP(), []int{12}
}

func (x *CancelOrderRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CancelOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

// Information about SL/TP order
type SLTPOrder struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Account ID
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Instrument symbol
	Symbol string `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Side for both orders
	Side v1.Side `protobuf:"varint,3,opt,name=side,proto3,enum=grpc.tradeapi.v1.Side" json:"side,omitempty"`
	// Stop-loss quantity in units
	QuantitySl *decimal.Decimal `protobuf:"bytes,4,opt,name=quantity_sl,json=quantitySl,proto3" json:"quantity_sl,omitempty"`
	// Price condition parameter for SL part
	SlPrice *decimal.Decimal `protobuf:"bytes,5,opt,name=sl_price,json=slPrice,proto3" json:"sl_price,omitempty"`
	// If specified, after SL activation a limit order will be placed with this price
	LimitPrice *decimal.Decimal `protobuf:"bytes,6,opt,name=limit_price,json=limitPrice,proto3" json:"limit_price,omitempty"`
	// Take-profit quantity in units
	QuantityTp *decimal.Decimal `protobuf:"bytes,10,opt,name=quantity_tp,json=quantityTp,proto3" json:"quantity_tp,omitempty"`
	// Price condition parameter for TP part
	TpPrice *decimal.Decimal `protobuf:"bytes,11,opt,name=tp_price,json=tpPrice,proto3" json:"tp_price,omitempty"`
	// If specified, after TP activation a limit order will be placed taking into account the protective spread
	TpGuardSpread *decimal.Decimal `protobuf:"bytes,12,opt,name=tp_guard_spread,json=tpGuardSpread,proto3" json:"tp_guard_spread,omitempty"`
	// Unit for measuring the value of the protective spread
	TpSpreadMeasure TPSpreadMeasure `protobuf:"varint,13,opt,name=tp_spread_measure,json=tpSpreadMeasure,proto3,enum=grpc.tradeapi.v1.orders.TPSpreadMeasure" json:"tp_spread_measure,omitempty"`
	// Unique identifier of the order. Automatically generated if not sent. (maximum 20 characters)
	ClientOrderId string `protobuf:"bytes,20,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"`
	// Conditional-order validity; defaults to VALID_BEFORE_GOOD_TILL_CANCEL when omitted
	ValidBefore ValidBefore `protobuf:"varint,21,opt,name=valid_before,json=validBefore,proto3,enum=grpc.tradeapi.v1.orders.ValidBefore" json:"valid_before,omitempty"`
	// SL/TP request termination timestamp
	ValidExpiryTime *timestamppb.Timestamp `protobuf:"bytes,22,opt,name=valid_expiry_time,json=validExpiryTime,proto3" json:"valid_expiry_time,omitempty"`
	// Order comment (maximum 128 characters)
	Comment       string `protobuf:"bytes,23,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SLTPOrder) Reset() {
	*x = SLTPOrder{}
	mi := &file_grpc_tradeapi_v1_orders_orders_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SLTPOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SLTPOrder) ProtoMessage() {}

func (x *SLTPOrder) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_orders_orders_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SLTPOrder.ProtoReflect.Descriptor instead.
func (*SLTPOrder) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_orders_orders_service_proto_rawDescGZIP(), []int{13}
}

func (x *SLTPOrder) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *SLTPOrder) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SLTPOrder) GetSide() v1.Side {
	if x != nil {
		return x.Side
	}
	return v1.Side(0)
}

func (x *SLTPOrder) GetQuantitySl() *decimal.Decimal {
	if x != nil {
		return x.QuantitySl
	}
	return nil
}

func (x *SLTPOrder) GetSlPrice() *decimal.Decimal {
	if x != nil {
		return x.SlPrice
	}
	return nil
}

func (x *SLTPOrder) GetLimitPrice() *decimal.Decimal {
	if x != nil {
		return x.LimitPrice
	}
	return nil
}

func (x *SLTPOrder) GetQuantityTp() *decimal.Decimal {
	if x != nil {
		return x.QuantityTp
	}
	return nil
}

func (x *SLTPOrder) GetTpPrice() *decimal.Decimal {
	if x != nil {
		return x.TpPrice
	}
	return nil
}

func (x *SLTPOrder) GetTpGuardSpread() *decimal.Decimal {
	if x != nil {
		return x.TpGuardSpread
	}
	return nil
}

func (x *SLTPOrder) GetTpSpreadMeasure() TPSpreadMeasure {
	if x != nil {
		return x.TpSpreadMeasure
	}
	return TPSpreadMeasure_TP_SPREAD_MEASURE_UNDEFINED
}

func (x *SLTPOrder) GetClientOrderId() string {
	if x != nil {
		return x.ClientOrderId
	}
	return ""
}

func (x *SLTPOrder) GetValidBefore() ValidBefore {
	if x != nil {
		return x.ValidBefore
	}
	return ValidBefore_VALID_BEFORE_UNSPECIFIED
}

func (x *SLTPOrder) GetValidExpiryTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidExpiryTime
	}
	return nil
}

func (x *SLTPOrder) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

var File_grpc_tradeapi_v1_orders_orders_service_proto protoreflect.FileDescriptor

const file_grpc_tradeapi_v1_orders_orders_service_proto_rawDesc = "" +
	"\n" +
	",grpc/tradeapi/v1/orders/orders_service.proto\x12\x17grpc.tradeapi.v1.orders\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/type/decimal.proto\x1a\x1bgrpc/tradeapi/v1/side.proto\x1a\x1cgrpc/tradeapi/v1/trade.proto\x1a;grpc/gateway/protoc_gen_openapiv2/options/annotations.proto\"\xd6\x02\n" +
	"\x11OrderTradeRequest\x12I\n" +
	"\x06action\x18\x01 \x01(\x0e21.grpc.tradeapi.v1.orders.OrderTradeRequest.ActionR\x06action\x12P\n" +
	"\tdata_type\x18\x02 \x01(\x0e23.grpc.tradeapi.v1.orders.OrderTradeRequest.DataTypeR\bdataType\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\"6\n" +
	"\x06Action\x12\x14\n" +
	"\x10ACTION_SUBSCRIBE\x10\x00\x12\x16\n" +
	"\x12ACTION_UNSUBSCRIBE\x10\x01\"I\n" +
	"\bDataType\x12\x11\n" +
	"\rDATA_TYPE_ALL\x10\x00\x12\x14\n" +
	"\x10DATA_TYPE_ORDERS\x10\x01\x12\x14\n" +
	"\x10DATA_TYPE_TRADES\x10\x02:\x02\x18\x01\"\x8d\x01\n" +
	"\x12OrderTradeResponse\x12;\n" +
	"\x06orders\x18\x01 \x03(\v2#.grpc.tradeapi.v1.orders.OrderStateR\x06orders\x126\n" +
	"\x06trades\x18\x02 \x03(\v2\x1e.grpc.tradeapi.v1.AccountTradeR\x06trades:\x02\x18\x01\"7\n" +
	"\x16SubscribeOrdersRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"V\n" +
	"\x17SubscribeOrdersResponse\x12;\n" +
	"\x06orders\x18\x01 \x03(\v2#.grpc.tradeapi.v1.orders.OrderStateR\x06orders\"7\n" +
	"\x16SubscribeTradesRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"Q\n" +
	"\x17SubscribeTradesResponse\x126\n" +
	"\x06trades\x18\x01 \x03(\v2\x1e.grpc.tradeapi.v1.AccountTradeR\x06trades\"K\n" +
	"\x0fGetOrderRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\"\x96\x05\n" +
	"\x05Order\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x120\n" +
	"\bquantity\x18\x03 \x01(\v2\x14.google.type.DecimalR\bquantity\x12*\n" +
	"\x04side\x18\x04 \x01(\x0e2\x16.grpc.tradeapi.v1.SideR\x04side\x126\n" +
	"\x04type\x18\x05 \x01(\x0e2\".grpc.tradeapi.v1.orders.OrderTypeR\x04type\x12H\n" +
	"\rtime_in_force\x18\x06 \x01(\x0e2$.grpc.tradeapi.v1.orders.TimeInForceR\vtimeInForce\x125\n" +
	"\vlimit_price\x18\a \x01(\v2\x14.google.type.DecimalR\n" +
	"limitPrice\x123\n" +
	"\n" +
	"stop_price\x18\b \x01(\v2\x14.google.type.DecimalR\tstopPrice\x12M\n" +
	"\x0estop_condition\x18\t \x01(\x0e2&.grpc.tradeapi.v1.orders.StopConditionR\rstopCondition\x120\n" +
	"\x04legs\x18\n" +
	" \x03(\v2\x1c.grpc.tradeapi.v1.orders.LegR\x04legs\x12&\n" +
	"\x0fclient_order_id\x18\v \x01(\tR\rclientOrderId\x12G\n" +
	"\fvalid_before\x18\f \x01(\x0e2$.grpc.tradeapi.v1.orders.ValidBeforeR\vvalidBefore\x12\x18\n" +
	"\acomment\x18\r \x01(\tR\acomment\"{\n" +
	"\x03Leg\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x120\n" +
	"\bquantity\x18\x02 \x01(\v2\x14.google.type.DecimalR\bquantity\x12*\n" +
	"\x04side\x18\x03 \x01(\x0e2\x16.grpc.tradeapi.v1.SideR\x04side\"\xa1\x05\n" +
	"\n" +
	"OrderState\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\aexec_id\x18\x02 \x01(\tR\x06execId\x12<\n" +
	"\x06status\x18\x03 \x01(\x0e2$.grpc.tradeapi.v1.orders.OrderStatusR\x06status\x124\n" +
	"\x05order\x18\x04 \x01(\v2\x1e.grpc.tradeapi.v1.orders.OrderR\x05order\x12;\n" +
	"\vtransact_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"transactAt\x127\n" +
	"\taccept_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bacceptAt\x12;\n" +
	"\vwithdraw_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"withdrawAt\x12?\n" +
	"\x10initial_quantity\x18\b \x01(\v2\x14.google.type.DecimalR\x0finitialQuantity\x12A\n" +
	"\x11executed_quantity\x18\t \x01(\v2\x14.google.type.DecimalR\x10executedQuantity\x12C\n" +
	"\x12remaining_quantity\x18\n" +
	" \x01(\v2\x14.google.type.DecimalR\x11remainingQuantity\x12A\n" +
	"\n" +
	"sltp_order\x18\v \x01(\v2\".grpc.tradeapi.v1.orders.SLTPOrderR\tsltpOrder\x12,\n" +
	"\x12triggered_order_id\x18\f \x01(\tR\x10triggeredOrderId\".\n" +
	"\rOrdersRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"M\n" +
	"\x0eOrdersResponse\x12;\n" +
	"\x06orders\x18\x01 \x03(\v2#.grpc.tradeapi.v1.orders.OrderStateR\x06orders\"N\n" +
	"\x12CancelOrderRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\"\xdc\x05\n" +
	"\tSLTPOrder\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12*\n" +
	"\x04side\x18\x03 \x01(\x0e2\x16.grpc.tradeapi.v1.SideR\x04side\x125\n" +
	"\vquantity_sl\x18\x04 \x01(\v2\x14.google.type.DecimalR\n" +
	"quantitySl\x12/\n" +
	"\bsl_price\x18\x05 \x01(\v2\x14.google.type.DecimalR\aslPrice\x125\n" +
	"\vlimit_price\x18\x06 \x01(\v2\x14.google.type.DecimalR\n" +
	"limitPrice\x125\n" +
	"\vquantity_tp\x18\n" +
	" \x01(\v2\x14.google.type.DecimalR\n" +
	"quantityTp\x12/\n" +
	"\btp_price\x18\v \x01(\v2\x14.google.type.DecimalR\atpPrice\x12<\n" +
	"\x0ftp_guard_spread\x18\f \x01(\v2\x14.google.type.DecimalR\rtpGuardSpread\x12T\n" +
	"\x11tp_spread_measure\x18\r \x01(\x0e2(.grpc.tradeapi.v1.orders.TPSpreadMeasureR\x0ftpSpreadMeasure\x12&\n" +
	"\x0fclient_order_id\x18\x14 \x01(\tR\rclientOrderId\x12G\n" +
	"\fvalid_before\x18\x15 \x01(\x0e2$.grpc.tradeapi.v1.orders.ValidBeforeR\vvalidBefore\x12F\n" +
	"\x11valid_expiry_time\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampR\x0fvalidExpiryTime\x12\x18\n" +
	"\acomment\x18\x17 \x01(\tR\acomment*\x9e\x01\n" +
	"\tOrderType\x12\x1a\n" +
	"\x16ORDER_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ORDER_TYPE_MARKET\x10\x01\x12\x14\n" +
	"\x10ORDER_TYPE_LIMIT\x10\x02\x12\x13\n" +
	"\x0fORDER_TYPE_STOP\x10\x03\x12\x19\n" +
	"\x15ORDER_TYPE_STOP_LIMIT\x10\x04\x12\x18\n" +
	"\x14ORDER_TYPE_MULTI_LEG\x10\x05*\x89\x02\n" +
	"\vTimeInForce\x12\x1d\n" +
	"\x19TIME_IN_FORCE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TIME_IN_FORCE_DAY\x10\x01\x12\"\n" +
	"\x1eTIME_IN_FORCE_GOOD_TILL_CANCEL\x10\x02\x12$\n" +
	" TIME_IN_FORCE_GOOD_TILL_CROSSING\x10\x03\x12\x15\n" +
	"\x11TIME_IN_FORCE_EXT\x10\x04\x12\x19\n" +
	"\x15TIME_IN_FORCE_ON_OPEN\x10\x05\x12\x1a\n" +
	"\x16TIME_IN_FORCE_ON_CLOSE\x10\x06\x12\x15\n" +
	"\x11TIME_IN_FORCE_IOC\x10\a\x12\x15\n" +
	"\x11TIME_IN_FORCE_FOK\x10\b*i\n" +
	"\rStopCondition\x12\x1e\n" +
	"\x1aSTOP_CONDITION_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16STOP_CONDITION_LAST_UP\x10\x01\x12\x1c\n" +
	"\x18STOP_CONDITION_LAST_DOWN\x10\x02*\xe7\x06\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ORDER_STATUS_NEW\x10\x01\x12!\n" +
	"\x1dORDER_STATUS_PARTIALLY_FILLED\x10\x02\x12\x17\n" +
	"\x13ORDER_STATUS_FILLED\x10\x03\x12\x1d\n" +
	"\x19ORDER_STATUS_DONE_FOR_DAY\x10\x04\x12\x19\n" +
	"\x15ORDER_STATUS_CANCELED\x10\x05\x12\x19\n" +
	"\x15ORDER_STATUS_REPLACED\x10\x06\x12\x1f\n" +
	"\x1bORDER_STATUS_PENDING_CANCEL\x10\a\x12\x19\n" +
	"\x15ORDER_STATUS_REJECTED\x10\t\x12\x1a\n" +
	"\x16ORDER_STATUS_SUSPENDED\x10\n" +
	"\x12\x1c\n" +
	"\x18ORDER_STATUS_PENDING_NEW\x10\v\x12\x18\n" +
	"\x14ORDER_STATUS_EXPIRED\x10\r\x12\x17\n" +
	"\x13ORDER_STATUS_FAILED\x10\x10\x12\x1b\n" +
	"\x17ORDER_STATUS_FORWARDING\x10\x11\x12\x15\n" +
	"\x11ORDER_STATUS_WAIT\x10\x12\x12!\n" +
	"\x1dORDER_STATUS_DENIED_BY_BROKER\x10\x13\x12%\n" +
	"!ORDER_STATUS_REJECTED_BY_EXCHANGE\x10\x14\x12\x19\n" +
	"\x15ORDER_STATUS_WATCHING\x10\x15\x12\x19\n" +
	"\x15ORDER_STATUS_EXECUTED\x10\x16\x12\x19\n" +
	"\x15ORDER_STATUS_DISABLED\x10\x17\x12\x1a\n" +
	"\x16ORDER_STATUS_LINK_WAIT\x10\x18\x12\x1e\n" +
	"\x1aORDER_STATUS_SL_GUARD_TIME\x10\x1b\x12\x1c\n" +
	"\x18ORDER_STATUS_SL_EXECUTED\x10\x1c\x12\x1e\n" +
	"\x1aORDER_STATUS_SL_FORWARDING\x10\x1d\x12\x1e\n" +
	"\x1aORDER_STATUS_TP_GUARD_TIME\x10\x1e\x12\x1c\n" +
	"\x18ORDER_STATUS_TP_EXECUTED\x10\x1f\x12\x1e\n" +
	"\x1aORDER_STATUS_TP_CORRECTION\x10 \x12\x1e\n" +
	"\x1aORDER_STATUS_TP_FORWARDING\x10!\x12#\n" +
	"\x1fORDER_STATUS_TP_CORR_GUARD_TIME\x10\"*\x8c\x01\n" +
	"\vValidBefore\x12\x1c\n" +
	"\x18VALID_BEFORE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17VALID_BEFORE_END_OF_DAY\x10\x01\x12!\n" +
	"\x1dVALID_BEFORE_GOOD_TILL_CANCEL\x10\x02\x12\x1f\n" +
	"\x1bVALID_BEFORE_GOOD_TILL_DATE\x10\x03*n\n" +
	"\x0fTPSpreadMeasure\x12\x1f\n" +
	"\x1bTP_SPREAD_MEASURE_UNDEFINED\x10\x00\x12\x1b\n" +
	"\x17TP_SPREAD_MEASURE_VALUE\x10\x01\x12\x1d\n" +
	"\x19TP_SPREAD_MEASURE_PERCENT\x10\x022\xa6\f\n" +
	"\rOrdersService\x12\xee\x01\n" +
	"\n" +
	"PlaceOrder\x12\x1e.grpc.tradeapi.v1.orders.Order\x1a#.grpc.tradeapi.v1.orders.OrderState\"\x9a\x01\x92AlJ#\n" +
	"\x03400\x12\x1c\n" +
	"\x1aInvalid trading parametersJ0\n" +
	"\x03404\x12)\n" +
	"'The account or instrument was not foundb\x13\n" +
	"\x11\n" +
	"\rAuthorization\x12\x00\x82\xd3\xe4\x93\x02%:\x01*\" /v1/accounts/{account_id}/orders\x12\xa5\x02\n" +
	"\vCancelOrder\x12+.grpc.tradeapi.v1.orders.CancelOrderRequest\x1a#.grpc.tradeapi.v1.orders.OrderState\"\xc3\x01\x92A\x8c\x01JH\n" +
	"\x03400\x12A\n" +
	"?The order cannot be canceled since it has already been executedJ+\n" +
	"\x03404\x12$\n" +
	"\"The account or order was not foundb\x13\n" +
	"\x11\n" +
	"\rAuthorization\x12\x00\x82\xd3\xe4\x93\x02-*+/v1/accounts/{account_id}/orders/{order_id}\x12\xbe\x01\n" +
	"\tGetOrders\x12&.grpc.tradeapi.v1.orders.OrdersRequest\x1a'.grpc.tradeapi.v1.orders.OrdersResponse\"`\x92A5J\x1e\n" +
	"\x03404\x12\x17\n" +
	"\x15Account was not foundb\x13\n" +
	"\x11\n" +
	"\rAuthorization\x12\x00\x82\xd3\xe4\x93\x02\"\x12 /v1/accounts/{account_id}/orders\x12\xd3\x01\n" +
	"\bGetOrder\x12(.grpc.tradeapi.v1.orders.GetOrderRequest\x1a#.grpc.tradeapi.v1.orders.OrderState\"x\x92ABJ+\n" +
	"\x03404\x12$\n" +
	"\"The account or order was not foundb\x13\n" +
	"\x11\n" +
	"\rAuthorization\x12\x00\x82\xd3\xe4\x93\x02-\x12+/v1/accounts/{account_id}/orders/{order_id}\x12w\n" +
	"\x13SubscribeOrderTrade\x12*.grpc.tradeapi.v1.orders.OrderTradeRequest\x1a+.grpc.tradeapi.v1.orders.OrderTradeResponse\"\x03\x88\x02\x01(\x010\x01\x12v\n" +
	"\x0fSubscribeOrders\x12/.grpc.tradeapi.v1.orders.SubscribeOrdersRequest\x1a0.grpc.tradeapi.v1.orders.SubscribeOrdersResponse0\x01\x12v\n" +
	"\x0fSubscribeTrades\x12/.grpc.tradeapi.v1.orders.SubscribeTradesRequest\x1a0.grpc.tradeapi.v1.orders.SubscribeTradesResponse0\x01\x12\xfb\x01\n" +
	"\x0ePlaceSLTPOrder\x12\".grpc.tradeapi.v1.orders.SLTPOrder\x1a#.grpc.tradeapi.v1.orders.OrderState\"\x9f\x01\x92AlJ#\n" +
	"\x03400\x12\x1c\n" +
	"\x1aInvalid trading parametersJ0\n" +
	"\x03404\x12)\n" +
	"'The account or instrument was not foundb\x13\n" +
	"\x11\n" +
	"\rAuthorization\x12\x00\x82\xd3\xe4\x93\x02*:\x01*\"%/v1/accounts/{account_id}/sltp-ordersB\x8e\x04\x92A\xc5\x03\x12'\n" +
	"\tTrade API\x12\x1aAPI for trading operations*\x02\x01\x02R-\n" +
	"\x03401\x12&\n" +
	"$The token has expired or is invalid.RK\n" +
	"\x03429\x12D\n" +
	"BToo many requests. The available limit is 200 requests per minute.R1\n" +
	"\x03500\x12*\n" +
	"(Internal service error. Try again later.R?\n" +
	"\x03503\x128\n" +
	"6The service is currently unavailable. Try again later.RB\n" +
	"\x03504\x12;\n" +
	"9The deadline was exceeded before the operation completed.R!\n" +
	"\adefault\x12\x16\x12\x14\n" +
	"\x12\x1a\x10googletypeStatusZ?\n" +
	"=\n" +
	"\rAuthorization\x12,\b\x02\x12\x17JWT authorization token\x1a\rAuthorization \x02P\x01ZAgithub.com/your-organization/trade-api/go/grpc/tradeapi/v1/ordersb\x06proto3"

var (
	file_grpc_tradeapi_v1_orders_orders_service_proto_rawDescOnce sync.Once
	file_grpc_tradeapi_v1_orders_orders_service_proto_rawDescData []byte
)

func file_grpc_tradeapi_v1_orders_orders_service_proto_rawDescGZIP() []byte {
	file_grpc_tradeapi_v1_orders_orders_service_proto_rawDescOnce.Do(func() {
		file_grpc_tradeapi_v1_orders_orders_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_tradeapi_v1_orders_orders_service_proto_rawDesc), len(file_grpc_tradeapi_v1_orders_orders_service_proto_rawDesc)))
	})
	return file_grpc_tradeapi_v1_orders_orders_service_proto_rawDescData
}

var file_grpc_tradeapi_v1_orders_orders_service_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_grpc_tradeapi_v1_orders_orders_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_grpc_tradeapi_v1_orders_orders_service_proto_goTypes = []any{
	(OrderType)(0),                  // 0: grpc.tradeapi.v1.orders.OrderType
	(TimeInForce)(0),                // 1: grpc.tradeapi.v1.orders.TimeInForce
	(StopCondition)(0),              // 2: grpc.tradeapi.v1.orders.StopCondition
	(OrderStatus)(0),                // 3: grpc.tradeapi.v1.orders.OrderStatus
	(ValidBefore)(0),                // 4: grpc.tradeapi.v1.orders.ValidBefore
	(TPSpreadMeasure)(0),            // 5: grpc.tradeapi.v1.orders.TPSpreadMeasure
	(OrderTradeRequest_Action)(0),   // 6: grpc.tradeapi.v1.orders.OrderTradeRequest.Action
	(OrderTradeRequest_DataType)(0), // 7: grpc.tradeapi.v1.orders.OrderTradeRequest.DataType
	(*OrderTradeRequest)(nil),       // 8: grpc.tradeapi.v1.orders.OrderTradeRequest
	(*OrderTradeResponse)(nil),      // 9: grpc.tradeapi.v1.orders.OrderTradeResponse
	(*SubscribeOrdersRequest)(nil),  // 10: grpc.tradeapi.v1.orders.SubscribeOrdersRequest
	(*SubscribeOrdersResponse)(nil), // 11: grpc.tradeapi.v1.orders.SubscribeOrdersResponse
	(*SubscribeTradesRequest)(nil),  // 12: grpc.tradeapi.v1.orders.SubscribeTradesRequest
	(*SubscribeTradesResponse)(nil), // 13: grpc.tradeapi.v1.orders.SubscribeTradesResponse
	(*GetOrderRequest)(nil),         // 14: grpc.tradeapi.v1.orders.GetOrderRequest
	(*Order)(nil),                   // 15: grpc.tradeapi.v1.orders.Order
	(*Leg)(nil),                     // 16: grpc.tradeapi.v1.orders.Leg
	(*OrderState)(nil),              // 17: grpc.tradeapi.v1.orders.OrderState
	(*OrdersRequest)(nil),           // 18: grpc.tradeapi.v1.orders.OrdersRequest
	(*OrdersResponse)(nil),          // 19: grpc.tradeapi.v1.orders.OrdersResponse
	(*CancelOrderRequest)(nil),      // 20: grpc.tradeapi.v1.orders.CancelOrderRequest
	(*SLTPOrder)(nil),               // 21: grpc.tradeapi.v1.orders.SLTPOrder
	(*v1.AccountTrade)(nil),         // 22: grpc.tradeapi.v1.AccountTrade
	(*decimal.Decimal)(nil),         // 23: google.type.Decimal
	(v1.Side)(0),                    // 24: grpc.tradeapi.v1.Side
	(*timestamppb.Timestamp)(nil),   // 25: google.protobuf.Timestamp
}
var file_grpc_tradeapi_v1_orders_orders_service_proto_depIdxs = []int32{
	6,  // 0: grpc.tradeapi.v1.orders.OrderTradeRequest.action:type_name -> grpc.tradeapi.v1.orders.OrderTradeRequest.Action
	7,  // 1: grpc.tradeapi.v1.orders.OrderTradeRequest.data_type:type_name -> grpc.tradeapi.v1.orders.OrderTradeRequest.DataType
	17, // 2: grpc.tradeapi.v1.orders.OrderTradeResponse.orders:type_name -> grpc.tradeapi.v1.orders.OrderState
	22, // 3: grpc.tradeapi.v1.orders.OrderTradeResponse.trades:type_name -> grpc.tradeapi.v1.AccountTrade
	17, // 4: grpc.tradeapi.v1.orders.SubscribeOrdersResponse.orders:type_name -> grpc.tradeapi.v1.orders.OrderState
	22, // 5: grpc.tradeapi.v1.orders.SubscribeTradesResponse.trades:type_name -> grpc.tradeapi.v1.AccountTrade
	23, // 6: grpc.tradeapi.v1.orders.Order.quantity:type_name -> google.type.Decimal
	24, // 7: grpc.tradeapi.v1.orders.Order.side:type_name -> grpc.tradeapi.v1.Side
	0,  // 8: grpc.tradeapi.v1.orders.Order.type:type_name -> grpc.tradeapi.v1.orders.OrderType
	1,  // 9: grpc.tradeapi.v1.orders.Order.time_in_force:type_name -> grpc.tradeapi.v1.orders.TimeInForce
	23, // 10: grpc.tradeapi.v1.orders.Order.limit_price:type_name -> google.type.Decimal
	23, // 11: grpc.tradeapi.v1.orders.Order.stop_price:type_name -> google.type.Decimal
	2,  // 12: grpc.tradeapi.v1.orders.Order.stop_condition:type_name -> grpc.tradeapi.v1.orders.StopCondition
	16, // 13: grpc.tradeapi.v1.orders.Order.legs:type_name -> grpc.tradeapi.v1.orders.Leg
	4,  // 14: grpc.tradeapi.v1.orders.Order.valid_before:type_name -> grpc.tradeapi.v1.orders.ValidBefore
	23, // 15: grpc.tradeapi.v1.orders.Leg.quantity:type_name -> google.type.Decimal
	24, // 16: grpc.tradeapi.v1.orders.Leg.side:type_name -> grpc.tradeapi.v1.Side
	3,  // 17: grpc.tradeapi.v1.orders.OrderState.status:type_name -> grpc.tradeapi.v1.orders.OrderStatus
	15, // 18: grpc.tradeapi.v1.orders.OrderState.order:type_name -> grpc.tradeapi.v1.orders.Order
	25, // 19: grpc.tradeapi.v1.orders.OrderState.transact_at:type_name -> google.protobuf.Timestamp
	25, // 20: grpc.tradeapi.v1.orders.OrderState.accept_at:type_name -> google.protobuf.Timestamp
	25, // 21: grpc.tradeapi.v1.orders.OrderState.withdraw_at:type_name -> google.protobuf.Timestamp
	23, // 22: grpc.tradeapi.v1.orders.OrderState.initial_quantity:type_name -> google.type.Decimal
	23, // 23: grpc.tradeapi.v1.orders.OrderState.executed_quantity:type_name -> google.type.Decimal
	23, // 24: grpc.tradeapi.v1.orders.OrderState.remaining_quantity:type_name -> google.type.Decimal
	21, // 25: grpc.tradeapi.v1.orders.OrderState.sltp_order:type_name -> grpc.tradeapi.v1.orders.SLTPOrder
	17, // 26: grpc.tradeapi.v1.orders.OrdersResponse.orders:type_name -> grpc.tradeapi.v1.orders.OrderState
	24, // 27: grpc.tradeapi.v1.orders.SLTPOrder.side:type_name -> grpc.tradeapi.v1.Side
	23, // 28: grpc.tradeapi.v1.orders.SLTPOrder.quantity_sl:type_name -> google.type.Decimal
	23, // 29: grpc.tradeapi.v1.orders.SLTPOrder.sl_price:type_name -> google.type.Decimal
	23, // 30: grpc.tradeapi.v1.orders.SLTPOrder.limit_price:type_name -> google.type.Decimal
	23, // 31: grpc.tradeapi.v1.orders.SLTPOrder.quantity_tp:type_name -> google.type.Decimal
	23, // 32: grpc.tradeapi.v1.orders.SLTPOrder.tp_price:type_name -> google.type.Decimal
	23, // 33: grpc.tradeapi.v1.orders.SLTPOrder.tp_guard_spread:type_name -> google.type.Decimal
	5,  // 34: grpc.tradeapi.v1.orders.SLTPOrder.tp_spread_measure:type_name -> grpc.tradeapi.v1.orders.TPSpreadMeasure
	4,  // 35: grpc.tradeapi.v1.orders.SLTPOrder.valid_before:type_name -> grpc.tradeapi.v1.orders.ValidBefore
	25, // 36: grpc.tradeapi.v1.orders.SLTPOrder.valid_expiry_time:type_name -> google.protobuf.Timestamp
	15, // 37: grpc.tradeapi.v1.orders.OrdersService.PlaceOrder:input_type -> grpc.tradeapi.v1.orders.Order
	20, // 38: grpc.tradeapi.v1.orders.OrdersService.CancelOrder:input_type -> grpc.tradeapi.v1.orders.CancelOrderRequest
	18, // 39: grpc.tradeapi.v1.orders.OrdersService.GetOrders:input_type -> grpc.tradeapi.v1.orders.OrdersRequest
	14, // 40: grpc.tradeapi.v1.orders.OrdersService.GetOrder:input_type -> grpc.tradeapi.v1.orders.GetOrderRequest
	8,  // 41: grpc.tradeapi.v1.orders.OrdersService.SubscribeOrderTrade:input_type -> grpc.tradeapi.v1.orders.OrderTradeRequest
	10, // 42: grpc.tradeapi.v1.orders.OrdersService.SubscribeOrders:input_type -> grpc.tradeapi.v1.orders.SubscribeOrdersRequest
	12, // 43: grpc.tradeapi.v1.orders.OrdersService.SubscribeTrades:input_type -> grpc.tradeapi.v1.orders.SubscribeTradesRequest
	21, // 44: grpc.tradeapi.v1.orders.OrdersService.PlaceSLTPOrder:input_type -> grpc.tradeapi.v1.orders.SLTPOrder
	17, // 45: grpc.tradeapi.v1.orders.OrdersService.PlaceOrder:output_type -> grpc.tradeapi.v1.orders.OrderState
	17, // 46: grpc.tradeapi.v1.orders.OrdersService.CancelOrder:output_type -> grpc.tradeapi.v1.orders.OrderState
	19, // 47: grpc.tradeapi.v1.orders.OrdersService.GetOrders:output_type -> grpc.tradeapi.v1.orders.OrdersResponse
	17, // 48: grpc.tradeapi.v1.orders.OrdersService.GetOrder:output_type -> grpc.tradeapi.v1.orders.OrderState
	9,  // 49: grpc.tradeapi.v1.orders.OrdersService.SubscribeOrderTrade:output_type -> grpc.tradeapi.v1.orders.OrderTradeResponse
	11, // 50: grpc.tradeapi.v1.orders.OrdersService.SubscribeOrders:output_type -> grpc.tradeapi.v1.orders.SubscribeOrdersResponse
	13, // 51: grpc.tradeapi.v1.orders.OrdersService.SubscribeTrades:output_type -> grpc.tradeapi.v1.orders.SubscribeTradesResponse
	17, // 52: grpc.tradeapi.v1.orders.OrdersService.PlaceSLTPOrder:output_type -> grpc.tradeapi.v1.orders.OrderState
	45, // [45:53] is the sub-list for method output_type
	37, // [37:45] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_grpc_tradeapi_v1_orders_orders_service_proto_init() }
func file_grpc_tradeapi_v1_orders_orders_service_proto_init() {
	if File_grpc_tradeapi_v1_orders_orders_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_tradeapi_v1_orders_orders_service_proto_rawDesc), len(file_grpc_tradeapi_v1_orders_orders_service_proto_rawDesc)),
			NumEnums:      8,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_tradeapi_v1_orders_orders_service_proto_goTypes,
		DependencyIndexes: file_grpc_tradeapi_v1_orders_orders_service_proto_depIdxs,
		EnumInfos:         file_grpc_tradeapi_v1_orders_orders_service_proto_enumTypes,
		MessageInfos:      file_grpc_tradeapi_v1_orders_orders_service_proto_msgTypes,
	}.Build()
	File_grpc_tradeapi_v1_orders_orders_service_proto = out.File
	file_grpc_tradeapi_v1_orders_orders_service_proto_goTypes = nil
	file_grpc_tradeapi_v1_orders_orders_service_proto_depIdxs = nil
}
