// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: grpc/tradeapi/v1/reports/reports_service.proto

package reports

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReportsService_CreateAccountReport_FullMethodName        = "/grpc.tradeapi.v1.reports.ReportsService/CreateAccountReport"
	ReportsService_GetAccountReportInfo_FullMethodName       = "/grpc.tradeapi.v1.reports.ReportsService/GetAccountReportInfo"
	ReportsService_SubscribeAccountReportInfo_FullMethodName = "/grpc.tradeapi.v1.reports.ReportsService/SubscribeAccountReportInfo"
)

// ReportsServiceClient is the client API for ReportsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for receiving custom reports.
type ReportsServiceClient interface {
	// Start generating an account report for the period
	// Example HTTP request:
	// POST /v1/report
	// Authorization: <token>
	CreateAccountReport(ctx context.Context, in *CreateAccountReportRequest, opts ...grpc.CallOption) (*CreateAccountReportResponse, error)
	// Get the account report generation result
	// Example HTTP request:
	// GET /v1/report/01KBMPQ3CEZ4BBCVGBW5JS8S8Y/info
	// Authorization: <token>
	GetAccountReportInfo(ctx context.Context, in *GetAccountReportInfoRequest, opts ...grpc.CallOption) (*GetAccountReportInfoResponse, error)
	// Subscribe to information about the results of generating an account report. Stream method
	SubscribeAccountReportInfo(ctx context.Context, in *SubscribeAccountReportInfoRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeAccountReportInfoResponse], error)
}

type reportsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReportsServiceClient(cc grpc.ClientConnInterface) ReportsServiceClient {
	return &reportsServiceClient{cc}
}

func (c *reportsServiceClient) CreateAccountReport(ctx context.Context, in *CreateAccountReportRequest, opts ...grpc.CallOption) (*CreateAccountReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAccountReportResponse)
	err := c.cc.Invoke(ctx, ReportsService_CreateAccountReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportsServiceClient) GetAccountReportInfo(ctx context.Context, in *GetAccountReportInfoRequest, opts ...grpc.CallOption) (*GetAccountReportInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccountReportInfoResponse)
	err := c.cc.Invoke(ctx, ReportsService_GetAccountReportInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportsServiceClient) SubscribeAccountReportInfo(ctx context.Context, in *SubscribeAccountReportInfoRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeAccountReportInfoResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ReportsService_ServiceDesc.Streams[0], ReportsService_SubscribeAccountReportInfo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeAccountReportInfoRequest, SubscribeAccountReportInfoResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReportsService_SubscribeAccountReportInfoClient = grpc.ServerStreamingClient[SubscribeAccountReportInfoResponse]

// ReportsServiceServer is the server API for ReportsService service.
// All implementations must embed UnimplementedReportsServiceServer
// for forward compatibility.
//
// Service for receiving custom reports.
type ReportsServiceServer interface {
	// Start generating an account report for the period
	// Example HTTP request:
	// POST /v1/report
	// Authorization: <token>
	CreateAccountReport(context.Context, *CreateAccountReportRequest) (*CreateAccountReportResponse, error)
	// Get the account report generation result
	// Example HTTP request:
	// GET /v1/report/01KBMPQ3CEZ4BBCVGBW5JS8S8Y/info
	// Authorization: <token>
	GetAccountReportInfo(context.Context, *GetAccountReportInfoRequest) (*GetAccountReportInfoResponse, error)
	// Subscribe to information about the results of generating an account report. Stream method
	SubscribeAccountReportInfo(*SubscribeAccountReportInfoRequest, grpc.ServerStreamingServer[SubscribeAccountReportInfoResponse]) error
	mustEmbedUnimplementedReportsServiceServer()
}

// UnimplementedReportsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReportsServiceServer struct{}

func (UnimplementedReportsServiceServer) CreateAccountReport(context.Context, *CreateAccountReportRequest) (*CreateAccountReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccountReport not implemented")
}
func (UnimplementedReportsServiceServer) GetAccountReportInfo(context.Context, *GetAccountReportInfoRequest) (*GetAccountReportInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountReportInfo not implemented")
}
func (UnimplementedReportsServiceServer) SubscribeAccountReportInfo(*SubscribeAccountReportInfoRequest, grpc.ServerStreamingServer[SubscribeAccountReportInfoResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeAccountReportInfo not implemented")
}
func (UnimplementedReportsServiceServer) mustEmbedUnimplementedReportsServiceServer() {}
func (UnimplementedReportsServiceServer) testEmbeddedByValue()                        {}

// UnsafeReportsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReportsServiceServer will
// result in compilation errors.
type UnsafeReportsServiceServer interface {
	mustEmbedUnimplementedReportsServiceServer()
}

func RegisterReportsServiceServer(s grpc.ServiceRegistrar, srv ReportsServiceServer) {
	// If the following call pancis, it indicates UnimplementedReportsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReportsService_ServiceDesc, srv)
}

func _ReportsService_CreateAccountReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportsServiceServer).CreateAccountReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReportsService_CreateAccountReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportsServiceServer).CreateAccountReport(ctx, req.(*CreateAccountReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportsService_GetAccountReportInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountReportInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportsServiceServer).GetAccountReportInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReportsService_GetAccountReportInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportsServiceServer).GetAccountReportInfo(ctx, req.(*GetAccountReportInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportsService_SubscribeAccountReportInfo_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeAccountReportInfoRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ReportsServiceServer).SubscribeAccountReportInfo(m, &grpc.GenericServerStream[SubscribeAccountReportInfoRequest, SubscribeAccountReportInfoResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReportsService_SubscribeAccountReportInfoServer = grpc.ServerStreamingServer[SubscribeAccountReportInfoResponse]

// ReportsService_ServiceDesc is the grpc.ServiceDesc for ReportsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReportsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.tradeapi.v1.reports.ReportsService",
	HandlerType: (*ReportsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccountReport",
			Handler:    _ReportsService_CreateAccountReport_Handler,
		},
		{
			MethodName: "GetAccountReportInfo",
			Handler:    _ReportsService_GetAccountReportInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeAccountReportInfo",
			Handler:       _ReportsService_SubscribeAccountReportInfo_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grpc/tradeapi/v1/reports/reports_service.proto",
}
