// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: grpc/tradeapi/v1/marketdata/marketdata_service.proto

package marketdata

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	v1 "github.com/your-organization/trade-api/go/grpc/tradeapi/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	decimal "google.golang.org/genproto/googleapis/type/decimal"
	interval "google.golang.org/genproto/googleapis/type/interval"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Available bar timeframes
type TimeFrame int32

const (
	// Timeframe not specified
	TimeFrame_TIME_FRAME_UNSPECIFIED TimeFrame = 0
	// 1 minute. Data depth 7 days.
	TimeFrame_TIME_FRAME_M1 TimeFrame = 1
	// 5 minutes. Data depth 30 days.
	TimeFrame_TIME_FRAME_M5 TimeFrame = 5
	// 15 minutes. Data depth 30 days.
	TimeFrame_TIME_FRAME_M15 TimeFrame = 9
	// 30 minutes. Data depth 30 days.
	TimeFrame_TIME_FRAME_M30 TimeFrame = 11
	// 1 hour. Data depth 30 days.
	TimeFrame_TIME_FRAME_H1 TimeFrame = 12
	// 2 hours. Data depth 30 days.
	TimeFrame_TIME_FRAME_H2 TimeFrame = 13
	// 4 hours. Data depth 30 days.
	TimeFrame_TIME_FRAME_H4 TimeFrame = 15
	// 8 hours. Data depth 30 days.
	TimeFrame_TIME_FRAME_H8 TimeFrame = 17
	// Day. Data depth 365 days.
	TimeFrame_TIME_FRAME_D TimeFrame = 19
	// Week. Data depth 365*5 days.
	TimeFrame_TIME_FRAME_W TimeFrame = 20
	// Month. Data depth 365*5 days.
	TimeFrame_TIME_FRAME_MN TimeFrame = 21
	// Quarter. Data depth 365*5 days.
	TimeFrame_TIME_FRAME_QR TimeFrame = 22
)

// Enum value maps for TimeFrame.
var (
	TimeFrame_name = map[int32]string{
		0:  "TIME_FRAME_UNSPECIFIED",
		1:  "TIME_FRAME_M1",
		5:  "TIME_FRAME_M5",
		9:  "TIME_FRAME_M15",
		11: "TIME_FRAME_M30",
		12: "TIME_FRAME_H1",
		13: "TIME_FRAME_H2",
		15: "TIME_FRAME_H4",
		17: "TIME_FRAME_H8",
		19: "TIME_FRAME_D",
		20: "TIME_FRAME_W",
		21: "TIME_FRAME_MN",
		22: "TIME_FRAME_QR",
	}
	TimeFrame_value = map[string]int32{
		"TIME_FRAME_UNSPECIFIED": 0,
		"TIME_FRAME_M1":          1,
		"TIME_FRAME_M5":          5,
		"TIME_FRAME_M15":         9,
		"TIME_FRAME_M30":         11,
		"TIME_FRAME_H1":          12,
		"TIME_FRAME_H2":          13,
		"TIME_FRAME_H4":          15,
		"TIME_FRAME_H8":          17,
		"TIME_FRAME_D":           19,
		"TIME_FRAME_W":           20,
		"TIME_FRAME_MN":          21,
		"TIME_FRAME_QR":          22,
	}
)

func (x TimeFrame) Enum() *TimeFrame {
	p := new(TimeFrame)
	*p = x
	return p
}

func (x TimeFrame) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeFrame) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_enumTypes[0].Descriptor()
}

func (TimeFrame) Type() protoreflect.EnumType {
	return &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_enumTypes[0]
}

func (x TimeFrame) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeFrame.Descriptor instead.
func (TimeFrame) EnumDescriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_rawDescGZIP(), []int{0}
}

// Action
type OrderBook_Row_Action int32

const (
	// Action not specified
	OrderBook_Row_ACTION_UNSPECIFIED OrderBook_Row_Action = 0
	// Delete
	OrderBook_Row_ACTION_REMOVE OrderBook_Row_Action = 1
	// Add
	OrderBook_Row_ACTION_ADD OrderBook_Row_Action = 2
	// Update
	OrderBook_Row_ACTION_UPDATE OrderBook_Row_Action = 3
)

// Enum value maps for OrderBook_Row_Action.
var (
	OrderBook_Row_Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_REMOVE",
		2: "ACTION_ADD",
		3: "ACTION_UPDATE",
	}
	OrderBook_Row_Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_REMOVE":      1,
		"ACTION_ADD":         2,
		"ACTION_UPDATE":      3,
	}
)

func (x OrderBook_Row_Action) Enum() *OrderBook_Row_Action {
	p := new(OrderBook_Row_Action)
	*p = x
	return p
}

func (x OrderBook_Row_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderBook_Row_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_enumTypes[1].Descriptor()
}

func (OrderBook_Row_Action) Type() protoreflect.EnumType {
	return &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_enumTypes[1]
}

func (x OrderBook_Row_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderBook_Row_Action.Descriptor instead.
func (OrderBook_Row_Action) EnumDescriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_rawDescGZIP(), []int{16, 0, 0}
}

// Action
type StreamOrderBook_Row_Action int32

const (
	// Action not specified
	StreamOrderBook_Row_ACTION_UNSPECIFIED StreamOrderBook_Row_Action = 0
	// Delete
	StreamOrderBook_Row_ACTION_REMOVE StreamOrderBook_Row_Action = 1
	// Add
	StreamOrderBook_Row_ACTION_ADD StreamOrderBook_Row_Action = 2
	// Update
	StreamOrderBook_Row_ACTION_UPDATE StreamOrderBook_Row_Action = 3
)

// Enum value maps for StreamOrderBook_Row_Action.
var (
	StreamOrderBook_Row_Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_REMOVE",
		2: "ACTION_ADD",
		3: "ACTION_UPDATE",
	}
	StreamOrderBook_Row_Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_REMOVE":      1,
		"ACTION_ADD":         2,
		"ACTION_UPDATE":      3,
	}
)

func (x StreamOrderBook_Row_Action) Enum() *StreamOrderBook_Row_Action {
	p := new(StreamOrderBook_Row_Action)
	*p = x
	return p
}

func (x StreamOrderBook_Row_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamOrderBook_Row_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_enumTypes[2].Descriptor()
}

func (StreamOrderBook_Row_Action) Type() protoreflect.EnumType {
	return &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_enumTypes[2]
}

func (x StreamOrderBook_Row_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamOrderBook_Row_Action.Descriptor instead.
func (StreamOrderBook_Row_Action) EnumDescriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_rawDescGZIP(), []int{19, 0, 0}
}

// Request historical bars for an instrument
type BarsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Instrument symbol
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Required timeframe
	Timeframe TimeFrame `protobuf:"varint,2,opt,name=timeframe,proto3,enum=grpc.tradeapi.v1.marketdata.TimeFrame" json:"timeframe,omitempty"`
	// Start and end of the requested period
	Interval      *interval.Interval `protobuf:"bytes,3,opt,name=interval,proto3" json:"interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BarsRequest) Reset() {
	*x = BarsRequest{}
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BarsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BarsRequest) ProtoMessage() {}

func (x *BarsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BarsRequest.ProtoReflect.Descriptor instead.
func (*BarsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_rawDescGZIP(), []int{0}
}

func (x *BarsRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *BarsRequest) GetTimeframe() TimeFrame {
	if x != nil {
		return x.Timeframe
	}
	return TimeFrame_TIME_FRAME_UNSPECIFIED
}

func (x *BarsRequest) GetInterval() *interval.Interval {
	if x != nil {
		return x.Interval
	}
	return nil
}

// List of aggregated bars
type BarsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Instrument symbol
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Aggregated bars
	Bars          []*Bar `protobuf:"bytes,2,rep,name=bars,proto3" json:"bars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BarsResponse) Reset() {
	*x = BarsResponse{}
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BarsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BarsResponse) ProtoMessage() {}

func (x *BarsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BarsResponse.ProtoReflect.Descriptor instead.
func (*BarsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_rawDescGZIP(), []int{1}
}

func (x *BarsResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *BarsResponse) GetBars() []*Bar {
	if x != nil {
		return x.Bars
	}
	return nil
}

// Request to receive the latest quote for an instrument
type QuoteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Instrument symbol
	Symbol        string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteRequest) Reset() {
	*x = QuoteRequest{}
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteRequest) ProtoMessage() {}

func (x *QuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteRequest.ProtoReflect.Descriptor instead.
func (*QuoteRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_rawDescGZIP(), []int{2}
}

func (x *QuoteRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// Latest quote for the instrument
type QuoteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Instrument symbol
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Last trade price
	Quote         *Quote `protobuf:"bytes,2,opt,name=quote,proto3" json:"quote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteResponse) Reset() {
	*x = QuoteResponse{}
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteResponse) ProtoMessage() {}

func (x *QuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteResponse.ProtoReflect.Descriptor instead.
func (*QuoteResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_rawDescGZIP(), []int{3}
}

func (x *QuoteResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *QuoteResponse) GetQuote() *Quote {
	if x != nil {
		return x.Quote
	}
	return nil
}

// Request the current order book for an instrument
type OrderBookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Instrument symbol
	Symbol        string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBookRequest) Reset() {
	*x = OrderBookRequest{}
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBookRequest) ProtoMessage() {}

func (x *OrderBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBookRequest.ProtoReflect.Descriptor instead.
func (*OrderBookRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_rawDescGZIP(), []int{4}
}

func (x *OrderBookRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// Current order book by instrument
type OrderBookResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Instrument symbol
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Order book
	Orderbook     *OrderBook `protobuf:"bytes,2,opt,name=orderbook,proto3" json:"orderbook,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBookResponse) Reset() {
	*x = OrderBookResponse{}
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBookResponse) ProtoMessage() {}

func (x *OrderBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBookResponse.ProtoReflect.Descriptor instead.
func (*OrderBookResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_rawDescGZIP(), []int{5}
}

func (x *OrderBookResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OrderBookResponse) GetOrderbook() *OrderBook {
	if x != nil {
		return x.Orderbook
	}
	return nil
}

// Request recent trades for an instrument
type LatestTradesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Instrument symbol
	Symbol        string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatestTradesRequest) Reset() {
	*x = LatestTradesRequest{}
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatestTradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestTradesRequest) ProtoMessage() {}

func (x *LatestTradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestTradesRequest.ProtoReflect.Descriptor instead.
func (*LatestTradesRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_rawDescGZIP(), []int{6}
}

func (x *LatestTradesRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// Recent trades for an instrument
type LatestTradesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Instrument symbol
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Recent trades
	Trades        []*Trade `protobuf:"bytes,2,rep,name=trades,proto3" json:"trades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatestTradesResponse) Reset() {
	*x = LatestTradesResponse{}
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatestTradesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestTradesResponse) ProtoMessage() {}

func (x *LatestTradesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestTradesResponse.ProtoReflect.Descriptor instead.
func (*LatestTradesResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_rawDescGZIP(), []int{7}
}

func (x *LatestTradesResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *LatestTradesResponse) GetTrades() []*Trade {
	if x != nil {
		return x.Trades
	}
	return nil
}

// Request to subscribe to quotes for an instrument. Stream
type SubscribeQuoteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of instrument symbols
	Symbols       []string `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeQuoteRequest) Reset() {
	*x = SubscribeQuoteRequest{}
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeQuoteRequest) ProtoMessage() {}

func (x *SubscribeQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeQuoteRequest.ProtoReflect.Descriptor instead.
func (*SubscribeQuoteRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_rawDescGZIP(), []int{8}
}

func (x *SubscribeQuoteRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

// Quotes by instrument. Stream
type SubscribeQuoteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of quotes
	Quote []*Quote `protobuf:"bytes,1,rep,name=quote,proto3" json:"quote,omitempty"`
	// Stream service error
	Error         *StreamError `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeQuoteResponse) Reset() {
	*x = SubscribeQuoteResponse{}
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeQuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeQuoteResponse) ProtoMessage() {}

func (x *SubscribeQuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeQuoteResponse.ProtoReflect.Descriptor instead.
func (*SubscribeQuoteResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_rawDescGZIP(), []int{9}
}

func (x *SubscribeQuoteResponse) GetQuote() []*Quote {
	if x != nil {
		return x.Quote
	}
	return nil
}

func (x *SubscribeQuoteResponse) GetError() *StreamError {
	if x != nil {
		return x.Error
	}
	return nil
}

// Request for subscription to order book by instrument. Stream
type SubscribeOrderBookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Instrument symbol
	Symbol        string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeOrderBookRequest) Reset() {
	*x = SubscribeOrderBookRequest{}
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeOrderBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeOrderBookRequest) ProtoMessage() {}

func (x *SubscribeOrderBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeOrderBookRequest.ProtoReflect.Descriptor instead.
func (*SubscribeOrderBookRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_rawDescGZIP(), []int{10}
}

func (x *SubscribeOrderBookRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// Instrument order book stream
type SubscribeOrderBookResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of order book streams
	OrderBook     []*StreamOrderBook `protobuf:"bytes,1,rep,name=order_book,json=orderBook,proto3" json:"order_book,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeOrderBookResponse) Reset() {
	*x = SubscribeOrderBookResponse{}
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeOrderBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeOrderBookResponse) ProtoMessage() {}

func (x *SubscribeOrderBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeOrderBookResponse.ProtoReflect.Descriptor instead.
func (*SubscribeOrderBookResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_rawDescGZIP(), []int{11}
}

func (x *SubscribeOrderBookResponse) GetOrderBook() []*StreamOrderBook {
	if x != nil {
		return x.OrderBook
	}
	return nil
}

// Request an aggregated-bar subscription. Stream
type SubscribeBarsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Instrument symbol
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Required timeframe
	Timeframe     TimeFrame `protobuf:"varint,2,opt,name=timeframe,proto3,enum=grpc.tradeapi.v1.marketdata.TimeFrame" json:"timeframe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeBarsRequest) Reset() {
	*x = SubscribeBarsRequest{}
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeBarsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeBarsRequest) ProtoMessage() {}

func (x *SubscribeBarsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeBarsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeBarsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_rawDescGZIP(), []int{12}
}

func (x *SubscribeBarsRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SubscribeBarsRequest) GetTimeframe() TimeFrame {
	if x != nil {
		return x.Timeframe
	}
	return TimeFrame_TIME_FRAME_UNSPECIFIED
}

// Aggregated bars. Stream
type SubscribeBarsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Instrument symbol
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Aggregated bars
	Bars          []*Bar `protobuf:"bytes,2,rep,name=bars,proto3" json:"bars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeBarsResponse) Reset() {
	*x = SubscribeBarsResponse{}
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeBarsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeBarsResponse) ProtoMessage() {}

func (x *SubscribeBarsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeBarsResponse.ProtoReflect.Descriptor instead.
func (*SubscribeBarsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_rawDescGZIP(), []int{13}
}

func (x *SubscribeBarsResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SubscribeBarsResponse) GetBars() []*Bar {
	if x != nil {
		return x.Bars
	}
	return nil
}

// Aggregated bar information
type Bar struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Opening price
	Open *decimal.Decimal `protobuf:"bytes,2,opt,name=open,proto3" json:"open,omitempty"`
	// High price
	High *decimal.Decimal `protobuf:"bytes,3,opt,name=high,proto3" json:"high,omitempty"`
	// Low price
	Low *decimal.Decimal `protobuf:"bytes,4,opt,name=low,proto3" json:"low,omitempty"`
	// Closing price
	Close *decimal.Decimal `protobuf:"bytes,5,opt,name=close,proto3" json:"close,omitempty"`
	// Trading volume for the bar, in units
	Volume        *decimal.Decimal `protobuf:"bytes,6,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bar) Reset() {
	*x = Bar{}
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bar) ProtoMessage() {}

func (x *Bar) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bar.ProtoReflect.Descriptor instead.
func (*Bar) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_rawDescGZIP(), []int{14}
}

func (x *Bar) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Bar) GetOpen() *decimal.Decimal {
	if x != nil {
		return x.Open
	}
	return nil
}

func (x *Bar) GetHigh() *decimal.Decimal {
	if x != nil {
		return x.High
	}
	return nil
}

func (x *Bar) GetLow() *decimal.Decimal {
	if x != nil {
		return x.Low
	}
	return nil
}

func (x *Bar) GetClose() *decimal.Decimal {
	if x != nil {
		return x.Close
	}
	return nil
}

func (x *Bar) GetVolume() *decimal.Decimal {
	if x != nil {
		return x.Volume
	}
	return nil
}

// Quote information
type Quote struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Instrument symbol
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Timestamp
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Ask. 0 if there is no active ask
	Ask *decimal.Decimal `protobuf:"bytes,3,opt,name=ask,proto3" json:"ask,omitempty"`
	// Ask size
	AskSize *decimal.Decimal `protobuf:"bytes,4,opt,name=ask_size,json=askSize,proto3" json:"ask_size,omitempty"`
	// Bid. 0 if there is no active bid
	Bid *decimal.Decimal `protobuf:"bytes,5,opt,name=bid,proto3" json:"bid,omitempty"`
	// Bid size
	BidSize *decimal.Decimal `protobuf:"bytes,6,opt,name=bid_size,json=bidSize,proto3" json:"bid_size,omitempty"`
	// Last trade price
	Last *decimal.Decimal `protobuf:"bytes,7,opt,name=last,proto3" json:"last,omitempty"`
	// Last trade size
	LastSize *decimal.Decimal `protobuf:"bytes,8,opt,name=last_size,json=lastSize,proto3" json:"last_size,omitempty"`
	// Daily trade volume
	Volume *decimal.Decimal `protobuf:"bytes,9,opt,name=volume,proto3" json:"volume,omitempty"`
	// Daily trade turnover
	Turnover *decimal.Decimal `protobuf:"bytes,10,opt,name=turnover,proto3" json:"turnover,omitempty"`
	// Opening price. Daytime
	Open *decimal.Decimal `protobuf:"bytes,11,opt,name=open,proto3" json:"open,omitempty"`
	// Maximum price. Daytime
	High *decimal.Decimal `protobuf:"bytes,12,opt,name=high,proto3" json:"high,omitempty"`
	// Minimum price. Daytime
	Low *decimal.Decimal `protobuf:"bytes,13,opt,name=low,proto3" json:"low,omitempty"`
	// Closing price. Daytime
	Close *decimal.Decimal `protobuf:"bytes,14,opt,name=close,proto3" json:"close,omitempty"`
	// Price change (last minus close)
	Change *decimal.Decimal `protobuf:"bytes,15,opt,name=change,proto3" json:"change,omitempty"`
	// Open interest. The total number of open (active) derivative contracts.
	OpenInterest *decimal.Decimal `protobuf:"bytes,16,opt,name=open_interest,json=openInterest,proto3" json:"open_interest,omitempty"`
	// Types that are valid to be assigned to Additions:
	//
	//	*Quote_Option_
	Additions     isQuote_Additions `protobuf_oneof:"additions"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quote) Reset() {
	*x = Quote{}
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quote) ProtoMessage() {}

func (x *Quote) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quote.ProtoReflect.Descriptor instead.
func (*Quote) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_rawDescGZIP(), []int{15}
}

func (x *Quote) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Quote) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Quote) GetAsk() *decimal.Decimal {
	if x != nil {
		return x.Ask
	}
	return nil
}

func (x *Quote) GetAskSize() *decimal.Decimal {
	if x != nil {
		return x.AskSize
	}
	return nil
}

func (x *Quote) GetBid() *decimal.Decimal {
	if x != nil {
		return x.Bid
	}
	return nil
}

func (x *Quote) GetBidSize() *decimal.Decimal {
	if x != nil {
		return x.BidSize
	}
	return nil
}

func (x *Quote) GetLast() *decimal.Decimal {
	if x != nil {
		return x.Last
	}
	return nil
}

func (x *Quote) GetLastSize() *decimal.Decimal {
	if x != nil {
		return x.LastSize
	}
	return nil
}

func (x *Quote) GetVolume() *decimal.Decimal {
	if x != nil {
		return x.Volume
	}
	return nil
}

func (x *Quote) GetTurnover() *decimal.Decimal {
	if x != nil {
		return x.Turnover
	}
	return nil
}

func (x *Quote) GetOpen() *decimal.Decimal {
	if x != nil {
		return x.Open
	}
	return nil
}

func (x *Quote) GetHigh() *decimal.Decimal {
	if x != nil {
		return x.High
	}
	return nil
}

func (x *Quote) GetLow() *decimal.Decimal {
	if x != nil {
		return x.Low
	}
	return nil
}

func (x *Quote) GetClose() *decimal.Decimal {
	if x != nil {
		return x.Close
	}
	return nil
}

func (x *Quote) GetChange() *decimal.Decimal {
	if x != nil {
		return x.Change
	}
	return nil
}

func (x *Quote) GetOpenInterest() *decimal.Decimal {
	if x != nil {
		return x.OpenInterest
	}
	return nil
}

func (x *Quote) GetAdditions() isQuote_Additions {
	if x != nil {
		return x.Additions
	}
	return nil
}

func (x *Quote) GetOption() *Quote_Option {
	if x != nil {
		if x, ok := x.Additions.(*Quote_Option_); ok {
			return x.Option
		}
	}
	return nil
}

type isQuote_Additions interface {
	isQuote_Additions()
}

type Quote_Option_ struct {
	// Option Information
	Option *Quote_Option `protobuf:"bytes,50,opt,name=option,proto3,oneof"`
}

func (*Quote_Option_) isQuote_Additions() {}

// Order book information
type OrderBook struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Order book levels
	Rows          []*OrderBook_Row `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBook) Reset() {
	*x = OrderBook{}
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBook) ProtoMessage() {}

func (x *OrderBook) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBook.ProtoReflect.Descriptor instead.
func (*OrderBook) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_rawDescGZIP(), []int{16}
}

func (x *OrderBook) GetRows() []*OrderBook_Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

// Trade information
type Trade struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Trade ID sent by the exchange
	TradeId string `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	// Market Participant ID
	Mpid string `protobuf:"bytes,2,opt,name=mpid,proto3" json:"mpid,omitempty"`
	// Timestamp
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Trade price
	Price *decimal.Decimal `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	// Trade size
	Size *decimal.Decimal `protobuf:"bytes,5,opt,name=size,proto3" json:"size,omitempty"`
	// Trade side (buy or sell)
	Side v1.Side `protobuf:"varint,6,opt,name=side,proto3,enum=grpc.tradeapi.v1.Side" json:"side,omitempty"`
	// Open interest at the time of the trade.
	OpenInterest  *decimal.Decimal `protobuf:"bytes,7,opt,name=open_interest,json=openInterest,proto3" json:"open_interest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_rawDescGZIP(), []int{17}
}

func (x *Trade) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *Trade) GetMpid() string {
	if x != nil {
		return x.Mpid
	}
	return ""
}

func (x *Trade) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Trade) GetPrice() *decimal.Decimal {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *Trade) GetSize() *decimal.Decimal {
	if x != nil {
		return x.Size
	}
	return nil
}

func (x *Trade) GetSide() v1.Side {
	if x != nil {
		return x.Side
	}
	return v1.Side(0)
}

func (x *Trade) GetOpenInterest() *decimal.Decimal {
	if x != nil {
		return x.OpenInterest
	}
	return nil
}

// Stream service error
type StreamError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Error code
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// Description of the error
	Description   string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamError) Reset() {
	*x = StreamError{}
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamError) ProtoMessage() {}

func (x *StreamError) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamError.ProtoReflect.Descriptor instead.
func (*StreamError) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_rawDescGZIP(), []int{18}
}

func (x *StreamError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StreamError) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Instrument order book stream
type StreamOrderBook struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Instrument symbol
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Order book levels
	Rows          []*StreamOrderBook_Row `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamOrderBook) Reset() {
	*x = StreamOrderBook{}
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOrderBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOrderBook) ProtoMessage() {}

func (x *StreamOrderBook) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOrderBook.ProtoReflect.Descriptor instead.
func (*StreamOrderBook) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_rawDescGZIP(), []int{19}
}

func (x *StreamOrderBook) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *StreamOrderBook) GetRows() []*StreamOrderBook_Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

// Request recent trades for an instrument. Stream
type SubscribeLatestTradesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Instrument symbol
	Symbol        string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeLatestTradesRequest) Reset() {
	*x = SubscribeLatestTradesRequest{}
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeLatestTradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeLatestTradesRequest) ProtoMessage() {}

func (x *SubscribeLatestTradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeLatestTradesRequest.ProtoReflect.Descriptor instead.
func (*SubscribeLatestTradesRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_rawDescGZIP(), []int{20}
}

func (x *SubscribeLatestTradesRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// Recent trades for an instrument. Stream
type SubscribeLatestTradesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Instrument symbol
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// List of trades
	Trades        []*Trade `protobuf:"bytes,2,rep,name=trades,proto3" json:"trades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeLatestTradesResponse) Reset() {
	*x = SubscribeLatestTradesResponse{}
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeLatestTradesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeLatestTradesResponse) ProtoMessage() {}

func (x *SubscribeLatestTradesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeLatestTradesResponse.ProtoReflect.Descriptor instead.
func (*SubscribeLatestTradesResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_rawDescGZIP(), []int{21}
}

func (x *SubscribeLatestTradesResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SubscribeLatestTradesResponse) GetTrades() []*Trade {
	if x != nil {
		return x.Trades
	}
	return nil
}

// Option Information
type Quote_Option struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Open Interest
	OpenInterest *decimal.Decimal `protobuf:"bytes,1,opt,name=open_interest,json=openInterest,proto3" json:"open_interest,omitempty"`
	// Implied volatility
	ImpliedVolatility *decimal.Decimal `protobuf:"bytes,2,opt,name=implied_volatility,json=impliedVolatility,proto3" json:"implied_volatility,omitempty"`
	// Theoretical price
	TheoreticalPrice *decimal.Decimal `protobuf:"bytes,3,opt,name=theoretical_price,json=theoreticalPrice,proto3" json:"theoretical_price,omitempty"`
	// Delta
	Delta *decimal.Decimal `protobuf:"bytes,4,opt,name=delta,proto3" json:"delta,omitempty"`
	// Gamma
	Gamma *decimal.Decimal `protobuf:"bytes,5,opt,name=gamma,proto3" json:"gamma,omitempty"`
	// Theta
	Theta *decimal.Decimal `protobuf:"bytes,6,opt,name=theta,proto3" json:"theta,omitempty"`
	// Vega
	Vega *decimal.Decimal `protobuf:"bytes,7,opt,name=vega,proto3" json:"vega,omitempty"`
	// Rho
	Rho           *decimal.Decimal `protobuf:"bytes,8,opt,name=rho,proto3" json:"rho,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quote_Option) Reset() {
	*x = Quote_Option{}
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quote_Option) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quote_Option) ProtoMessage() {}

func (x *Quote_Option) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quote_Option.ProtoReflect.Descriptor instead.
func (*Quote_Option) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_rawDescGZIP(), []int{15, 0}
}

func (x *Quote_Option) GetOpenInterest() *decimal.Decimal {
	if x != nil {
		return x.OpenInterest
	}
	return nil
}

func (x *Quote_Option) GetImpliedVolatility() *decimal.Decimal {
	if x != nil {
		return x.ImpliedVolatility
	}
	return nil
}

func (x *Quote_Option) GetTheoreticalPrice() *decimal.Decimal {
	if x != nil {
		return x.TheoreticalPrice
	}
	return nil
}

func (x *Quote_Option) GetDelta() *decimal.Decimal {
	if x != nil {
		return x.Delta
	}
	return nil
}

func (x *Quote_Option) GetGamma() *decimal.Decimal {
	if x != nil {
		return x.Gamma
	}
	return nil
}

func (x *Quote_Option) GetTheta() *decimal.Decimal {
	if x != nil {
		return x.Theta
	}
	return nil
}

func (x *Quote_Option) GetVega() *decimal.Decimal {
	if x != nil {
		return x.Vega
	}
	return nil
}

func (x *Quote_Option) GetRho() *decimal.Decimal {
	if x != nil {
		return x.Rho
	}
	return nil
}

// Information about the level in the order book (line)
type OrderBook_Row struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Price
	Price *decimal.Decimal `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	// Types that are valid to be assigned to Side:
	//
	//	*OrderBook_Row_SellSize
	//	*OrderBook_Row_BuySize
	Side isOrderBook_Row_Side `protobuf_oneof:"side"`
	// Action
	Action OrderBook_Row_Action `protobuf:"varint,4,opt,name=action,proto3,enum=grpc.tradeapi.v1.marketdata.OrderBook_Row_Action" json:"action,omitempty"`
	// Market Participant ID
	Mpid string `protobuf:"bytes,5,opt,name=mpid,proto3" json:"mpid,omitempty"`
	// Timestamp
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBook_Row) Reset() {
	*x = OrderBook_Row{}
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBook_Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBook_Row) ProtoMessage() {}

func (x *OrderBook_Row) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBook_Row.ProtoReflect.Descriptor instead.
func (*OrderBook_Row) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_rawDescGZIP(), []int{16, 0}
}

func (x *OrderBook_Row) GetPrice() *decimal.Decimal {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *OrderBook_Row) GetSide() isOrderBook_Row_Side {
	if x != nil {
		return x.Side
	}
	return nil
}

func (x *OrderBook_Row) GetSellSize() *decimal.Decimal {
	if x != nil {
		if x, ok := x.Side.(*OrderBook_Row_SellSize); ok {
			return x.SellSize
		}
	}
	return nil
}

func (x *OrderBook_Row) GetBuySize() *decimal.Decimal {
	if x != nil {
		if x, ok := x.Side.(*OrderBook_Row_BuySize); ok {
			return x.BuySize
		}
	}
	return nil
}

func (x *OrderBook_Row) GetAction() OrderBook_Row_Action {
	if x != nil {
		return x.Action
	}
	return OrderBook_Row_ACTION_UNSPECIFIED
}

func (x *OrderBook_Row) GetMpid() string {
	if x != nil {
		return x.Mpid
	}
	return ""
}

func (x *OrderBook_Row) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type isOrderBook_Row_Side interface {
	isOrderBook_Row_Side()
}

type OrderBook_Row_SellSize struct {
	// Sell size
	SellSize *decimal.Decimal `protobuf:"bytes,2,opt,name=sell_size,json=sellSize,proto3,oneof"`
}

type OrderBook_Row_BuySize struct {
	// Buy size
	BuySize *decimal.Decimal `protobuf:"bytes,3,opt,name=buy_size,json=buySize,proto3,oneof"`
}

func (*OrderBook_Row_SellSize) isOrderBook_Row_Side() {}

func (*OrderBook_Row_BuySize) isOrderBook_Row_Side() {}

// Information about the level in the order book (line)
type StreamOrderBook_Row struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Price
	Price *decimal.Decimal `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	// Types that are valid to be assigned to Side:
	//
	//	*StreamOrderBook_Row_SellSize
	//	*StreamOrderBook_Row_BuySize
	Side isStreamOrderBook_Row_Side `protobuf_oneof:"side"`
	// Action
	Action StreamOrderBook_Row_Action `protobuf:"varint,4,opt,name=action,proto3,enum=grpc.tradeapi.v1.marketdata.StreamOrderBook_Row_Action" json:"action,omitempty"`
	// Market Participant ID
	Mpid string `protobuf:"bytes,5,opt,name=mpid,proto3" json:"mpid,omitempty"`
	// Timestamp
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamOrderBook_Row) Reset() {
	*x = StreamOrderBook_Row{}
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOrderBook_Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOrderBook_Row) ProtoMessage() {}

func (x *StreamOrderBook_Row) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOrderBook_Row.ProtoReflect.Descriptor instead.
func (*StreamOrderBook_Row) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_rawDescGZIP(), []int{19, 0}
}

func (x *StreamOrderBook_Row) GetPrice() *decimal.Decimal {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *StreamOrderBook_Row) GetSide() isStreamOrderBook_Row_Side {
	if x != nil {
		return x.Side
	}
	return nil
}

func (x *StreamOrderBook_Row) GetSellSize() *decimal.Decimal {
	if x != nil {
		if x, ok := x.Side.(*StreamOrderBook_Row_SellSize); ok {
			return x.SellSize
		}
	}
	return nil
}

func (x *StreamOrderBook_Row) GetBuySize() *decimal.Decimal {
	if x != nil {
		if x, ok := x.Side.(*StreamOrderBook_Row_BuySize); ok {
			return x.BuySize
		}
	}
	return nil
}

func (x *StreamOrderBook_Row) GetAction() StreamOrderBook_Row_Action {
	if x != nil {
		return x.Action
	}
	return StreamOrderBook_Row_ACTION_UNSPECIFIED
}

func (x *StreamOrderBook_Row) GetMpid() string {
	if x != nil {
		return x.Mpid
	}
	return ""
}

func (x *StreamOrderBook_Row) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type isStreamOrderBook_Row_Side interface {
	isStreamOrderBook_Row_Side()
}

type StreamOrderBook_Row_SellSize struct {
	// Sell size
	SellSize *decimal.Decimal `protobuf:"bytes,2,opt,name=sell_size,json=sellSize,proto3,oneof"`
}

type StreamOrderBook_Row_BuySize struct {
	// Buy size
	BuySize *decimal.Decimal `protobuf:"bytes,3,opt,name=buy_size,json=buySize,proto3,oneof"`
}

func (*StreamOrderBook_Row_SellSize) isStreamOrderBook_Row_Side() {}

func (*StreamOrderBook_Row_BuySize) isStreamOrderBook_Row_Side() {}

var File_grpc_tradeapi_v1_marketdata_marketdata_service_proto protoreflect.FileDescriptor

const file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_rawDesc = "" +
	"\n" +
	"4grpc/tradeapi/v1/marketdata/marketdata_service.proto\x12\x1bgrpc.tradeapi.v1.marketdata\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/type/decimal.proto\x1a\x1agoogle/type/interval.proto\x1a\x1bgrpc/tradeapi/v1/side.proto\x1a;grpc/gateway/protoc_gen_openapiv2/options/annotations.proto\"\x9e\x01\n" +
	"\vBarsRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12D\n" +
	"\ttimeframe\x18\x02 \x01(\x0e2&.grpc.tradeapi.v1.marketdata.TimeFrameR\ttimeframe\x121\n" +
	"\binterval\x18\x03 \x01(\v2\x15.google.type.IntervalR\binterval\"\\\n" +
	"\fBarsResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x124\n" +
	"\x04bars\x18\x02 \x03(\v2 .grpc.tradeapi.v1.marketdata.BarR\x04bars\"&\n" +
	"\fQuoteRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"a\n" +
	"\rQuoteResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x128\n" +
	"\x05quote\x18\x02 \x01(\v2\".grpc.tradeapi.v1.marketdata.QuoteR\x05quote\"*\n" +
	"\x10OrderBookRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"q\n" +
	"\x11OrderBookResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12D\n" +
	"\torderbook\x18\x02 \x01(\v2&.grpc.tradeapi.v1.marketdata.OrderBookR\torderbook\"-\n" +
	"\x13LatestTradesRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"j\n" +
	"\x14LatestTradesResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12:\n" +
	"\x06trades\x18\x02 \x03(\v2\".grpc.tradeapi.v1.marketdata.TradeR\x06trades\"1\n" +
	"\x15SubscribeQuoteRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\"\x92\x01\n" +
	"\x16SubscribeQuoteResponse\x128\n" +
	"\x05quote\x18\x01 \x03(\v2\".grpc.tradeapi.v1.marketdata.QuoteR\x05quote\x12>\n" +
	"\x05error\x18\x02 \x01(\v2(.grpc.tradeapi.v1.marketdata.StreamErrorR\x05error\"3\n" +
	"\x19SubscribeOrderBookRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"i\n" +
	"\x1aSubscribeOrderBookResponse\x12K\n" +
	"\n" +
	"order_book\x18\x01 \x03(\v2,.grpc.tradeapi.v1.marketdata.StreamOrderBookR\torderBook\"t\n" +
	"\x14SubscribeBarsRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12D\n" +
	"\ttimeframe\x18\x02 \x01(\x0e2&.grpc.tradeapi.v1.marketdata.TimeFrameR\ttimeframe\"e\n" +
	"\x15SubscribeBarsResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x124\n" +
	"\x04bars\x18\x02 \x03(\v2 .grpc.tradeapi.v1.marketdata.BarR\x04bars\"\x95\x02\n" +
	"\x03Bar\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12(\n" +
	"\x04open\x18\x02 \x01(\v2\x14.google.type.DecimalR\x04open\x12(\n" +
	"\x04high\x18\x03 \x01(\v2\x14.google.type.DecimalR\x04high\x12&\n" +
	"\x03low\x18\x04 \x01(\v2\x14.google.type.DecimalR\x03low\x12*\n" +
	"\x05close\x18\x05 \x01(\v2\x14.google.type.DecimalR\x05close\x12,\n" +
	"\x06volume\x18\x06 \x01(\v2\x14.google.type.DecimalR\x06volume\"\xcf\t\n" +
	"\x05Quote\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12&\n" +
	"\x03ask\x18\x03 \x01(\v2\x14.google.type.DecimalR\x03ask\x12/\n" +
	"\bask_size\x18\x04 \x01(\v2\x14.google.type.DecimalR\aaskSize\x12&\n" +
	"\x03bid\x18\x05 \x01(\v2\x14.google.type.DecimalR\x03bid\x12/\n" +
	"\bbid_size\x18\x06 \x01(\v2\x14.google.type.DecimalR\abidSize\x12(\n" +
	"\x04last\x18\a \x01(\v2\x14.google.type.DecimalR\x04last\x121\n" +
	"\tlast_size\x18\b \x01(\v2\x14.google.type.DecimalR\blastSize\x12,\n" +
	"\x06volume\x18\t \x01(\v2\x14.google.type.DecimalR\x06volume\x120\n" +
	"\bturnover\x18\n" +
	" \x01(\v2\x14.google.type.DecimalR\bturnover\x12(\n" +
	"\x04open\x18\v \x01(\v2\x14.google.type.DecimalR\x04open\x12(\n" +
	"\x04high\x18\f \x01(\v2\x14.google.type.DecimalR\x04high\x12&\n" +
	"\x03low\x18\r \x01(\v2\x14.google.type.DecimalR\x03low\x12*\n" +
	"\x05close\x18\x0e \x01(\v2\x14.google.type.DecimalR\x05close\x12,\n" +
	"\x06change\x18\x0f \x01(\v2\x14.google.type.DecimalR\x06change\x129\n" +
	"\ropen_interest\x18\x10 \x01(\v2\x14.google.type.DecimalR\fopenInterest\x12C\n" +
	"\x06option\x182 \x01(\v2).grpc.tradeapi.v1.marketdata.Quote.OptionH\x00R\x06option\x1a\xa1\x03\n" +
	"\x06Option\x129\n" +
	"\ropen_interest\x18\x01 \x01(\v2\x14.google.type.DecimalR\fopenInterest\x12C\n" +
	"\x12implied_volatility\x18\x02 \x01(\v2\x14.google.type.DecimalR\x11impliedVolatility\x12A\n" +
	"\x11theoretical_price\x18\x03 \x01(\v2\x14.google.type.DecimalR\x10theoreticalPrice\x12*\n" +
	"\x05delta\x18\x04 \x01(\v2\x14.google.type.DecimalR\x05delta\x12*\n" +
	"\x05gamma\x18\x05 \x01(\v2\x14.google.type.DecimalR\x05gamma\x12*\n" +
	"\x05theta\x18\x06 \x01(\v2\x14.google.type.DecimalR\x05theta\x12(\n" +
	"\x04vega\x18\a \x01(\v2\x14.google.type.DecimalR\x04vega\x12&\n" +
	"\x03rho\x18\b \x01(\v2\x14.google.type.DecimalR\x03rhoB\v\n" +
	"\tadditions\"\xe0\x03\n" +
	"\tOrderBook\x12>\n" +
	"\x04rows\x18\x01 \x03(\v2*.grpc.tradeapi.v1.marketdata.OrderBook.RowR\x04rows\x1a\x92\x03\n" +
	"\x03Row\x12*\n" +
	"\x05price\x18\x01 \x01(\v2\x14.google.type.DecimalR\x05price\x123\n" +
	"\tsell_size\x18\x02 \x01(\v2\x14.google.type.DecimalH\x00R\bsellSize\x121\n" +
	"\bbuy_size\x18\x03 \x01(\v2\x14.google.type.DecimalH\x00R\abuySize\x12I\n" +
	"\x06action\x18\x04 \x01(\x0e21.grpc.tradeapi.v1.marketdata.OrderBook.Row.ActionR\x06action\x12\x12\n" +
	"\x04mpid\x18\x05 \x01(\tR\x04mpid\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"V\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rACTION_REMOVE\x10\x01\x12\x0e\n" +
	"\n" +
	"ACTION_ADD\x10\x02\x12\x11\n" +
	"\rACTION_UPDATE\x10\x03B\x06\n" +
	"\x04side\"\xad\x02\n" +
	"\x05Trade\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\tR\atradeId\x12\x12\n" +
	"\x04mpid\x18\x02 \x01(\tR\x04mpid\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12*\n" +
	"\x05price\x18\x04 \x01(\v2\x14.google.type.DecimalR\x05price\x12(\n" +
	"\x04size\x18\x05 \x01(\v2\x14.google.type.DecimalR\x04size\x12*\n" +
	"\x04side\x18\x06 \x01(\x0e2\x16.grpc.tradeapi.v1.SideR\x04side\x129\n" +
	"\ropen_interest\x18\a \x01(\v2\x14.google.type.DecimalR\fopenInterest\"C\n" +
	"\vStreamError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\x8a\x04\n" +
	"\x0fStreamOrderBook\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12D\n" +
	"\x04rows\x18\x02 \x03(\v20.grpc.tradeapi.v1.marketdata.StreamOrderBook.RowR\x04rows\x1a\x98\x03\n" +
	"\x03Row\x12*\n" +
	"\x05price\x18\x01 \x01(\v2\x14.google.type.DecimalR\x05price\x123\n" +
	"\tsell_size\x18\x02 \x01(\v2\x14.google.type.DecimalH\x00R\bsellSize\x121\n" +
	"\bbuy_size\x18\x03 \x01(\v2\x14.google.type.DecimalH\x00R\abuySize\x12O\n" +
	"\x06action\x18\x04 \x01(\x0e27.grpc.tradeapi.v1.marketdata.StreamOrderBook.Row.ActionR\x06action\x12\x12\n" +
	"\x04mpid\x18\x05 \x01(\tR\x04mpid\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"V\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rACTION_REMOVE\x10\x01\x12\x0e\n" +
	"\n" +
	"ACTION_ADD\x10\x02\x12\x11\n" +
	"\rACTION_UPDATE\x10\x03B\x06\n" +
	"\x04side\"6\n" +
	"\x1cSubscribeLatestTradesRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"s\n" +
	"\x1dSubscribeLatestTradesResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12:\n" +
	"\x06trades\x18\x02 \x03(\v2\".grpc.tradeapi.v1.marketdata.TradeR\x06trades*\x8b\x02\n" +
	"\tTimeFrame\x12\x1a\n" +
	"\x16TIME_FRAME_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rTIME_FRAME_M1\x10\x01\x12\x11\n" +
	"\rTIME_FRAME_M5\x10\x05\x12\x12\n" +
	"\x0eTIME_FRAME_M15\x10\t\x12\x12\n" +
	"\x0eTIME_FRAME_M30\x10\v\x12\x11\n" +
	"\rTIME_FRAME_H1\x10\f\x12\x11\n" +
	"\rTIME_FRAME_H2\x10\r\x12\x11\n" +
	"\rTIME_FRAME_H4\x10\x0f\x12\x11\n" +
	"\rTIME_FRAME_H8\x10\x11\x12\x10\n" +
	"\fTIME_FRAME_D\x10\x13\x12\x10\n" +
	"\fTIME_FRAME_W\x10\x14\x12\x11\n" +
	"\rTIME_FRAME_MN\x10\x15\x12\x11\n" +
	"\rTIME_FRAME_QR\x10\x162\xc5\n" +
	"\n" +
	"\x11MarketDataService\x12\xff\x01\n" +
	"\x04Bars\x12(.grpc.tradeapi.v1.marketdata.BarsRequest\x1a).grpc.tradeapi.v1.marketdata.BarsResponse\"\xa1\x01\x92AyJb\n" +
	"\x03400\x12[\n" +
	"YInvalid symbol or interval. The symbol must use ticker@mic format, for example SBER@MISX.b\x13\n" +
	"\x11\n" +
	"\rAuthorization\x12\x00\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/instruments/{symbol}/bars\x12\xaa\x01\n" +
	"\tLastQuote\x12).grpc.tradeapi.v1.marketdata.QuoteRequest\x1a*.grpc.tradeapi.v1.marketdata.QuoteResponse\"F\x92A\x15b\x13\n" +
	"\x11\n" +
	"\rAuthorization\x12\x00\x82\xd3\xe4\x93\x02(\x12&/v1/instruments/{symbol}/quotes/latest\x12\xae\x01\n" +
	"\tOrderBook\x12-.grpc.tradeapi.v1.marketdata.OrderBookRequest\x1a..grpc.tradeapi.v1.marketdata.OrderBookResponse\"B\x92A\x15b\x13\n" +
	"\x11\n" +
	"\rAuthorization\x12\x00\x82\xd3\xe4\x93\x02$\x12\"/v1/instruments/{symbol}/orderbook\x12\xbb\x01\n" +
	"\fLatestTrades\x120.grpc.tradeapi.v1.marketdata.LatestTradesRequest\x1a1.grpc.tradeapi.v1.marketdata.LatestTradesResponse\"F\x92A\x15b\x13\n" +
	"\x11\n" +
	"\rAuthorization\x12\x00\x82\xd3\xe4\x93\x02(\x12&/v1/instruments/{symbol}/trades/latest\x12{\n" +
	"\x0eSubscribeQuote\x122.grpc.tradeapi.v1.marketdata.SubscribeQuoteRequest\x1a3.grpc.tradeapi.v1.marketdata.SubscribeQuoteResponse0\x01\x12\x87\x01\n" +
	"\x12SubscribeOrderBook\x126.grpc.tradeapi.v1.marketdata.SubscribeOrderBookRequest\x1a7.grpc.tradeapi.v1.marketdata.SubscribeOrderBookResponse0\x01\x12\x90\x01\n" +
	"\x15SubscribeLatestTrades\x129.grpc.tradeapi.v1.marketdata.SubscribeLatestTradesRequest\x1a:.grpc.tradeapi.v1.marketdata.SubscribeLatestTradesResponse0\x01\x12x\n" +
	"\rSubscribeBars\x121.grpc.tradeapi.v1.marketdata.SubscribeBarsRequest\x1a2.grpc.tradeapi.v1.marketdata.SubscribeBarsResponse0\x01B\x89\x05\x92A\xbc\x04\x12'\n" +
	"\tTrade API\x12\x1aAPI for trading operations*\x02\x01\x02RV\n" +
	"\x03400\x12O\n" +
	"MInvalid symbol. The symbol must use ticker@mic format, for example SBER@MISX.R-\n" +
	"\x03401\x12&\n" +
	"$The token has expired or is invalid.R\x1d\n" +
	"\x03404\x12\x16\n" +
	"\x14Instrument not foundRK\n" +
	"\x03429\x12D\n" +
	"BToo many requests. The available limit is 200 requests per minute.R1\n" +
	"\x03500\x12*\n" +
	"(Internal service error. Try again later.R?\n" +
	"\x03503\x128\n" +
	"6The service is currently unavailable. Try again later.RB\n" +
	"\x03504\x12;\n" +
	"9The deadline was exceeded before the operation completed.R!\n" +
	"\adefault\x12\x16\x12\x14\n" +
	"\x12\x1a\x10googletypeStatusZ?\n" +
	"=\n" +
	"\rAuthorization\x12,\b\x02\x12\x17JWT authorization token\x1a\rAuthorization \x02P\x01ZEgithub.com/your-organization/trade-api/go/grpc/tradeapi/v1/marketdatab\x06proto3"

var (
	file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_rawDescOnce sync.Once
	file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_rawDescData []byte
)

func file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_rawDescGZIP() []byte {
	file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_rawDescOnce.Do(func() {
		file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_rawDesc), len(file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_rawDesc)))
	})
	return file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_rawDescData
}

var file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_goTypes = []any{
	(TimeFrame)(0),                        // 0: grpc.tradeapi.v1.marketdata.TimeFrame
	(OrderBook_Row_Action)(0),             // 1: grpc.tradeapi.v1.marketdata.OrderBook.Row.Action
	(StreamOrderBook_Row_Action)(0),       // 2: grpc.tradeapi.v1.marketdata.StreamOrderBook.Row.Action
	(*BarsRequest)(nil),                   // 3: grpc.tradeapi.v1.marketdata.BarsRequest
	(*BarsResponse)(nil),                  // 4: grpc.tradeapi.v1.marketdata.BarsResponse
	(*QuoteRequest)(nil),                  // 5: grpc.tradeapi.v1.marketdata.QuoteRequest
	(*QuoteResponse)(nil),                 // 6: grpc.tradeapi.v1.marketdata.QuoteResponse
	(*OrderBookRequest)(nil),              // 7: grpc.tradeapi.v1.marketdata.OrderBookRequest
	(*OrderBookResponse)(nil),             // 8: grpc.tradeapi.v1.marketdata.OrderBookResponse
	(*LatestTradesRequest)(nil),           // 9: grpc.tradeapi.v1.marketdata.LatestTradesRequest
	(*LatestTradesResponse)(nil),          // 10: grpc.tradeapi.v1.marketdata.LatestTradesResponse
	(*SubscribeQuoteRequest)(nil),         // 11: grpc.tradeapi.v1.marketdata.SubscribeQuoteRequest
	(*SubscribeQuoteResponse)(nil),        // 12: grpc.tradeapi.v1.marketdata.SubscribeQuoteResponse
	(*SubscribeOrderBookRequest)(nil),     // 13: grpc.tradeapi.v1.marketdata.SubscribeOrderBookRequest
	(*SubscribeOrderBookResponse)(nil),    // 14: grpc.tradeapi.v1.marketdata.SubscribeOrderBookResponse
	(*SubscribeBarsRequest)(nil),          // 15: grpc.tradeapi.v1.marketdata.SubscribeBarsRequest
	(*SubscribeBarsResponse)(nil),         // 16: grpc.tradeapi.v1.marketdata.SubscribeBarsResponse
	(*Bar)(nil),                           // 17: grpc.tradeapi.v1.marketdata.Bar
	(*Quote)(nil),                         // 18: grpc.tradeapi.v1.marketdata.Quote
	(*OrderBook)(nil),                     // 19: grpc.tradeapi.v1.marketdata.OrderBook
	(*Trade)(nil),                         // 20: grpc.tradeapi.v1.marketdata.Trade
	(*StreamError)(nil),                   // 21: grpc.tradeapi.v1.marketdata.StreamError
	(*StreamOrderBook)(nil),               // 22: grpc.tradeapi.v1.marketdata.StreamOrderBook
	(*SubscribeLatestTradesRequest)(nil),  // 23: grpc.tradeapi.v1.marketdata.SubscribeLatestTradesRequest
	(*SubscribeLatestTradesResponse)(nil), // 24: grpc.tradeapi.v1.marketdata.SubscribeLatestTradesResponse
	(*Quote_Option)(nil),                  // 25: grpc.tradeapi.v1.marketdata.Quote.Option
	(*OrderBook_Row)(nil),                 // 26: grpc.tradeapi.v1.marketdata.OrderBook.Row
	(*StreamOrderBook_Row)(nil),           // 27: grpc.tradeapi.v1.marketdata.StreamOrderBook.Row
	(*interval.Interval)(nil),             // 28: google.type.Interval
	(*timestamppb.Timestamp)(nil),         // 29: google.protobuf.Timestamp
	(*decimal.Decimal)(nil),               // 30: google.type.Decimal
	(v1.Side)(0),                          // 31: grpc.tradeapi.v1.Side
}
var file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_depIdxs = []int32{
	0,  // 0: grpc.tradeapi.v1.marketdata.BarsRequest.timeframe:type_name -> grpc.tradeapi.v1.marketdata.TimeFrame
	28, // 1: grpc.tradeapi.v1.marketdata.BarsRequest.interval:type_name -> google.type.Interval
	17, // 2: grpc.tradeapi.v1.marketdata.BarsResponse.bars:type_name -> grpc.tradeapi.v1.marketdata.Bar
	18, // 3: grpc.tradeapi.v1.marketdata.QuoteResponse.quote:type_name -> grpc.tradeapi.v1.marketdata.Quote
	19, // 4: grpc.tradeapi.v1.marketdata.OrderBookResponse.orderbook:type_name -> grpc.tradeapi.v1.marketdata.OrderBook
	20, // 5: grpc.tradeapi.v1.marketdata.LatestTradesResponse.trades:type_name -> grpc.tradeapi.v1.marketdata.Trade
	18, // 6: grpc.tradeapi.v1.marketdata.SubscribeQuoteResponse.quote:type_name -> grpc.tradeapi.v1.marketdata.Quote
	21, // 7: grpc.tradeapi.v1.marketdata.SubscribeQuoteResponse.error:type_name -> grpc.tradeapi.v1.marketdata.StreamError
	22, // 8: grpc.tradeapi.v1.marketdata.SubscribeOrderBookResponse.order_book:type_name -> grpc.tradeapi.v1.marketdata.StreamOrderBook
	0,  // 9: grpc.tradeapi.v1.marketdata.SubscribeBarsRequest.timeframe:type_name -> grpc.tradeapi.v1.marketdata.TimeFrame
	17, // 10: grpc.tradeapi.v1.marketdata.SubscribeBarsResponse.bars:type_name -> grpc.tradeapi.v1.marketdata.Bar
	29, // 11: grpc.tradeapi.v1.marketdata.Bar.timestamp:type_name -> google.protobuf.Timestamp
	30, // 12: grpc.tradeapi.v1.marketdata.Bar.open:type_name -> google.type.Decimal
	30, // 13: grpc.tradeapi.v1.marketdata.Bar.high:type_name -> google.type.Decimal
	30, // 14: grpc.tradeapi.v1.marketdata.Bar.low:type_name -> google.type.Decimal
	30, // 15: grpc.tradeapi.v1.marketdata.Bar.close:type_name -> google.type.Decimal
	30, // 16: grpc.tradeapi.v1.marketdata.Bar.volume:type_name -> google.type.Decimal
	29, // 17: grpc.tradeapi.v1.marketdata.Quote.timestamp:type_name -> google.protobuf.Timestamp
	30, // 18: grpc.tradeapi.v1.marketdata.Quote.ask:type_name -> google.type.Decimal
	30, // 19: grpc.tradeapi.v1.marketdata.Quote.ask_size:type_name -> google.type.Decimal
	30, // 20: grpc.tradeapi.v1.marketdata.Quote.bid:type_name -> google.type.Decimal
	30, // 21: grpc.tradeapi.v1.marketdata.Quote.bid_size:type_name -> google.type.Decimal
	30, // 22: grpc.tradeapi.v1.marketdata.Quote.last:type_name -> google.type.Decimal
	30, // 23: grpc.tradeapi.v1.marketdata.Quote.last_size:type_name -> google.type.Decimal
	30, // 24: grpc.tradeapi.v1.marketdata.Quote.volume:type_name -> google.type.Decimal
	30, // 25: grpc.tradeapi.v1.marketdata.Quote.turnover:type_name -> google.type.Decimal
	30, // 26: grpc.tradeapi.v1.marketdata.Quote.open:type_name -> google.type.Decimal
	30, // 27: grpc.tradeapi.v1.marketdata.Quote.high:type_name -> google.type.Decimal
	30, // 28: grpc.tradeapi.v1.marketdata.Quote.low:type_name -> google.type.Decimal
	30, // 29: grpc.tradeapi.v1.marketdata.Quote.close:type_name -> google.type.Decimal
	30, // 30: grpc.tradeapi.v1.marketdata.Quote.change:type_name -> google.type.Decimal
	30, // 31: grpc.tradeapi.v1.marketdata.Quote.open_interest:type_name -> google.type.Decimal
	25, // 32: grpc.tradeapi.v1.marketdata.Quote.option:type_name -> grpc.tradeapi.v1.marketdata.Quote.Option
	26, // 33: grpc.tradeapi.v1.marketdata.OrderBook.rows:type_name -> grpc.tradeapi.v1.marketdata.OrderBook.Row
	29, // 34: grpc.tradeapi.v1.marketdata.Trade.timestamp:type_name -> google.protobuf.Timestamp
	30, // 35: grpc.tradeapi.v1.marketdata.Trade.price:type_name -> google.type.Decimal
	30, // 36: grpc.tradeapi.v1.marketdata.Trade.size:type_name -> google.type.Decimal
	31, // 37: grpc.tradeapi.v1.marketdata.Trade.side:type_name -> grpc.tradeapi.v1.Side
	30, // 38: grpc.tradeapi.v1.marketdata.Trade.open_interest:type_name -> google.type.Decimal
	27, // 39: grpc.tradeapi.v1.marketdata.StreamOrderBook.rows:type_name -> grpc.tradeapi.v1.marketdata.StreamOrderBook.Row
	20, // 40: grpc.tradeapi.v1.marketdata.SubscribeLatestTradesResponse.trades:type_name -> grpc.tradeapi.v1.marketdata.Trade
	30, // 41: grpc.tradeapi.v1.marketdata.Quote.Option.open_interest:type_name -> google.type.Decimal
	30, // 42: grpc.tradeapi.v1.marketdata.Quote.Option.implied_volatility:type_name -> google.type.Decimal
	30, // 43: grpc.tradeapi.v1.marketdata.Quote.Option.theoretical_price:type_name -> google.type.Decimal
	30, // 44: grpc.tradeapi.v1.marketdata.Quote.Option.delta:type_name -> google.type.Decimal
	30, // 45: grpc.tradeapi.v1.marketdata.Quote.Option.gamma:type_name -> google.type.Decimal
	30, // 46: grpc.tradeapi.v1.marketdata.Quote.Option.theta:type_name -> google.type.Decimal
	30, // 47: grpc.tradeapi.v1.marketdata.Quote.Option.vega:type_name -> google.type.Decimal
	30, // 48: grpc.tradeapi.v1.marketdata.Quote.Option.rho:type_name -> google.type.Decimal
	30, // 49: grpc.tradeapi.v1.marketdata.OrderBook.Row.price:type_name -> google.type.Decimal
	30, // 50: grpc.tradeapi.v1.marketdata.OrderBook.Row.sell_size:type_name -> google.type.Decimal
	30, // 51: grpc.tradeapi.v1.marketdata.OrderBook.Row.buy_size:type_name -> google.type.Decimal
	1,  // 52: grpc.tradeapi.v1.marketdata.OrderBook.Row.action:type_name -> grpc.tradeapi.v1.marketdata.OrderBook.Row.Action
	29, // 53: grpc.tradeapi.v1.marketdata.OrderBook.Row.timestamp:type_name -> google.protobuf.Timestamp
	30, // 54: grpc.tradeapi.v1.marketdata.StreamOrderBook.Row.price:type_name -> google.type.Decimal
	30, // 55: grpc.tradeapi.v1.marketdata.StreamOrderBook.Row.sell_size:type_name -> google.type.Decimal
	30, // 56: grpc.tradeapi.v1.marketdata.StreamOrderBook.Row.buy_size:type_name -> google.type.Decimal
	2,  // 57: grpc.tradeapi.v1.marketdata.StreamOrderBook.Row.action:type_name -> grpc.tradeapi.v1.marketdata.StreamOrderBook.Row.Action
	29, // 58: grpc.tradeapi.v1.marketdata.StreamOrderBook.Row.timestamp:type_name -> google.protobuf.Timestamp
	3,  // 59: grpc.tradeapi.v1.marketdata.MarketDataService.Bars:input_type -> grpc.tradeapi.v1.marketdata.BarsRequest
	5,  // 60: grpc.tradeapi.v1.marketdata.MarketDataService.LastQuote:input_type -> grpc.tradeapi.v1.marketdata.QuoteRequest
	7,  // 61: grpc.tradeapi.v1.marketdata.MarketDataService.OrderBook:input_type -> grpc.tradeapi.v1.marketdata.OrderBookRequest
	9,  // 62: grpc.tradeapi.v1.marketdata.MarketDataService.LatestTrades:input_type -> grpc.tradeapi.v1.marketdata.LatestTradesRequest
	11, // 63: grpc.tradeapi.v1.marketdata.MarketDataService.SubscribeQuote:input_type -> grpc.tradeapi.v1.marketdata.SubscribeQuoteRequest
	13, // 64: grpc.tradeapi.v1.marketdata.MarketDataService.SubscribeOrderBook:input_type -> grpc.tradeapi.v1.marketdata.SubscribeOrderBookRequest
	23, // 65: grpc.tradeapi.v1.marketdata.MarketDataService.SubscribeLatestTrades:input_type -> grpc.tradeapi.v1.marketdata.SubscribeLatestTradesRequest
	15, // 66: grpc.tradeapi.v1.marketdata.MarketDataService.SubscribeBars:input_type -> grpc.tradeapi.v1.marketdata.SubscribeBarsRequest
	4,  // 67: grpc.tradeapi.v1.marketdata.MarketDataService.Bars:output_type -> grpc.tradeapi.v1.marketdata.BarsResponse
	6,  // 68: grpc.tradeapi.v1.marketdata.MarketDataService.LastQuote:output_type -> grpc.tradeapi.v1.marketdata.QuoteResponse
	8,  // 69: grpc.tradeapi.v1.marketdata.MarketDataService.OrderBook:output_type -> grpc.tradeapi.v1.marketdata.OrderBookResponse
	10, // 70: grpc.tradeapi.v1.marketdata.MarketDataService.LatestTrades:output_type -> grpc.tradeapi.v1.marketdata.LatestTradesResponse
	12, // 71: grpc.tradeapi.v1.marketdata.MarketDataService.SubscribeQuote:output_type -> grpc.tradeapi.v1.marketdata.SubscribeQuoteResponse
	14, // 72: grpc.tradeapi.v1.marketdata.MarketDataService.SubscribeOrderBook:output_type -> grpc.tradeapi.v1.marketdata.SubscribeOrderBookResponse
	24, // 73: grpc.tradeapi.v1.marketdata.MarketDataService.SubscribeLatestTrades:output_type -> grpc.tradeapi.v1.marketdata.SubscribeLatestTradesResponse
	16, // 74: grpc.tradeapi.v1.marketdata.MarketDataService.SubscribeBars:output_type -> grpc.tradeapi.v1.marketdata.SubscribeBarsResponse
	67, // [67:75] is the sub-list for method output_type
	59, // [59:67] is the sub-list for method input_type
	59, // [59:59] is the sub-list for extension type_name
	59, // [59:59] is the sub-list for extension extendee
	0,  // [0:59] is the sub-list for field type_name
}

func init() { file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_init() }
func file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_init() {
	if File_grpc_tradeapi_v1_marketdata_marketdata_service_proto != nil {
		return
	}
	file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[15].OneofWrappers = []any{
		(*Quote_Option_)(nil),
	}
	file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[23].OneofWrappers = []any{
		(*OrderBook_Row_SellSize)(nil),
		(*OrderBook_Row_BuySize)(nil),
	}
	file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes[24].OneofWrappers = []any{
		(*StreamOrderBook_Row_SellSize)(nil),
		(*StreamOrderBook_Row_BuySize)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_rawDesc), len(file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_goTypes,
		DependencyIndexes: file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_depIdxs,
		EnumInfos:         file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_enumTypes,
		MessageInfos:      file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_msgTypes,
	}.Build()
	File_grpc_tradeapi_v1_marketdata_marketdata_service_proto = out.File
	file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_goTypes = nil
	file_grpc_tradeapi_v1_marketdata_marketdata_service_proto_depIdxs = nil
}
