// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: grpc/tradeapi/v1/corporateactions/corporate_actions_service.proto

package corporateactions

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	date "google.golang.org/genproto/googleapis/type/date"
	decimal "google.golang.org/genproto/googleapis/type/decimal"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bond event type
type BondEventType int32

const (
	BondEventType_UNSPECIFIED  BondEventType = 0
	BondEventType_COUPON       BondEventType = 1
	BondEventType_AMORTIZATION BondEventType = 2
	BondEventType_OFFER        BondEventType = 3
)

// Enum value maps for BondEventType.
var (
	BondEventType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "COUPON",
		2: "AMORTIZATION",
		3: "OFFER",
	}
	BondEventType_value = map[string]int32{
		"UNSPECIFIED":  0,
		"COUPON":       1,
		"AMORTIZATION": 2,
		"OFFER":        3,
	}
)

func (x BondEventType) Enum() *BondEventType {
	p := new(BondEventType)
	*p = x
	return p
}

func (x BondEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BondEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_enumTypes[0].Descriptor()
}

func (BondEventType) Type() protoreflect.EnumType {
	return &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_enumTypes[0]
}

func (x BondEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BondEventType.Descriptor instead.
func (BondEventType) EnumDescriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_rawDescGZIP(), []int{0}
}

// Possible event types
type ConvertationType int32

const (
	// Unknown event/conversion type. Used by default
	ConvertationType_CONVTYPE_UNKNOWN ConvertationType = 0
	// Share buyback. Acquisition by the issuing company of its own shares
	ConvertationType_BUYBACK ConvertationType = 1
	// Execution of Call offer. Early redemption (revocation) of a security at the initiative of the issuer
	ConvertationType_CALL_OPTION_EXERCISED ConvertationType = 2
	// Partial face-value redemption (amortization) or scheduled redemption without a lottery
	ConvertationType_DRAWINGS ConvertationType = 3
	// Lottery redemption. Early repayment of part of a bond issue where securities are selected by lottery
	ConvertationType_DRAWINGS_BY_LOTTERY ConvertationType = 4
	// Early conversion. Exchange of one security for another before the scheduled date (for example, convertible bonds into shares)
	ConvertationType_EARLY_CONVERSION ConvertationType = 5
	// Redemption at maturity. Scheduled full redemption when the security reaches maturity
	ConvertationType_MATURITY ConvertationType = 6
	// Planned (regular) conversion. Standard corporate action: split, consolidation or planned exchange of securities
	ConvertationType_ORDINARY ConvertationType = 7
	// Execution of the Put offer. Early repurchase of a security by the issuer at the request of the investor (owner)
	ConvertationType_PUT_OPTION_EXERCISED ConvertationType = 8
	// Tender proposal. Public offer to shareholders to buy out their securities (often during mergers/acquisitions)
	ConvertationType_TENDER_OFFER ConvertationType = 9
)

// Enum value maps for ConvertationType.
var (
	ConvertationType_name = map[int32]string{
		0: "CONVTYPE_UNKNOWN",
		1: "BUYBACK",
		2: "CALL_OPTION_EXERCISED",
		3: "DRAWINGS",
		4: "DRAWINGS_BY_LOTTERY",
		5: "EARLY_CONVERSION",
		6: "MATURITY",
		7: "ORDINARY",
		8: "PUT_OPTION_EXERCISED",
		9: "TENDER_OFFER",
	}
	ConvertationType_value = map[string]int32{
		"CONVTYPE_UNKNOWN":      0,
		"BUYBACK":               1,
		"CALL_OPTION_EXERCISED": 2,
		"DRAWINGS":              3,
		"DRAWINGS_BY_LOTTERY":   4,
		"EARLY_CONVERSION":      5,
		"MATURITY":              6,
		"ORDINARY":              7,
		"PUT_OPTION_EXERCISED":  8,
		"TENDER_OFFER":          9,
	}
)

func (x ConvertationType) Enum() *ConvertationType {
	p := new(ConvertationType)
	*p = x
	return p
}

func (x ConvertationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConvertationType) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_enumTypes[1].Descriptor()
}

func (ConvertationType) Type() protoreflect.EnumType {
	return &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_enumTypes[1]
}

func (x ConvertationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConvertationType.Descriptor instead.
func (ConvertationType) EnumDescriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_rawDescGZIP(), []int{1}
}

// Sort direction
type SortDirection int32

const (
	// Ascending
	SortDirection_ASC SortDirection = 0
	// Descending
	SortDirection_DESC SortDirection = 1
)

// Enum value maps for SortDirection.
var (
	SortDirection_name = map[int32]string{
		0: "ASC",
		1: "DESC",
	}
	SortDirection_value = map[string]int32{
		"ASC":  0,
		"DESC": 1,
	}
)

func (x SortDirection) Enum() *SortDirection {
	p := new(SortDirection)
	*p = x
	return p
}

func (x SortDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_enumTypes[2].Descriptor()
}

func (SortDirection) Type() protoreflect.EnumType {
	return &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_enumTypes[2]
}

func (x SortDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortDirection.Descriptor instead.
func (SortDirection) EnumDescriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_rawDescGZIP(), []int{2}
}

// Request upcoming split events by instrument
type GetFutureSplitsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Instrument symbol
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Sorting direction by date: asc - from old to new, desc - from new to old
	SortDirection SortDirection `protobuf:"varint,2,opt,name=sort_direction,json=sortDirection,proto3,enum=grpc.tradeapi.v1.corporateactions.SortDirection" json:"sort_direction,omitempty"`
	// Limit. Limits the number of splits returned in the list
	Limit int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// Offset. Specifies the number of splits to skip before starting to return the result
	Offset        int32 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFutureSplitsRequest) Reset() {
	*x = GetFutureSplitsRequest{}
	mi := &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFutureSplitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFutureSplitsRequest) ProtoMessage() {}

func (x *GetFutureSplitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFutureSplitsRequest.ProtoReflect.Descriptor instead.
func (*GetFutureSplitsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetFutureSplitsRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetFutureSplitsRequest) GetSortDirection() SortDirection {
	if x != nil {
		return x.SortDirection
	}
	return SortDirection_ASC
}

func (x *GetFutureSplitsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetFutureSplitsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// Upcoming split events by instrument
type GetFutureSplitsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Instrument symbol
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Pagination options
	Pagination *Pagination `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// Split information
	Splits        []*SplitInfo `protobuf:"bytes,3,rep,name=splits,proto3" json:"splits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFutureSplitsResponse) Reset() {
	*x = GetFutureSplitsResponse{}
	mi := &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFutureSplitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFutureSplitsResponse) ProtoMessage() {}

func (x *GetFutureSplitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFutureSplitsResponse.ProtoReflect.Descriptor instead.
func (*GetFutureSplitsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetFutureSplitsResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetFutureSplitsResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetFutureSplitsResponse) GetSplits() []*SplitInfo {
	if x != nil {
		return x.Splits
	}
	return nil
}

// Request for split history by instrument
type GetPastSplitsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Instrument symbol
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Start of time interval
	DateFrom *date.Date `protobuf:"bytes,2,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	// End of time interval
	DateTo *date.Date `protobuf:"bytes,3,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	// Sorting direction by date: asc - from old to new, desc - from new to old
	SortDirection SortDirection `protobuf:"varint,4,opt,name=sort_direction,json=sortDirection,proto3,enum=grpc.tradeapi.v1.corporateactions.SortDirection" json:"sort_direction,omitempty"`
	// Limit. Limits the number of splits returned in the list
	Limit int32 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	// Offset. Specifies the number of splits to skip before starting to return the result
	Offset        int32 `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPastSplitsRequest) Reset() {
	*x = GetPastSplitsRequest{}
	mi := &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPastSplitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPastSplitsRequest) ProtoMessage() {}

func (x *GetPastSplitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPastSplitsRequest.ProtoReflect.Descriptor instead.
func (*GetPastSplitsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetPastSplitsRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetPastSplitsRequest) GetDateFrom() *date.Date {
	if x != nil {
		return x.DateFrom
	}
	return nil
}

func (x *GetPastSplitsRequest) GetDateTo() *date.Date {
	if x != nil {
		return x.DateTo
	}
	return nil
}

func (x *GetPastSplitsRequest) GetSortDirection() SortDirection {
	if x != nil {
		return x.SortDirection
	}
	return SortDirection_ASC
}

func (x *GetPastSplitsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetPastSplitsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// History of splits by instrument
type GetPastSplitsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Instrument symbol
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Pagination options
	Pagination *Pagination `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// Split information
	Splits        []*SplitInfo `protobuf:"bytes,3,rep,name=splits,proto3" json:"splits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPastSplitsResponse) Reset() {
	*x = GetPastSplitsResponse{}
	mi := &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPastSplitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPastSplitsResponse) ProtoMessage() {}

func (x *GetPastSplitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPastSplitsResponse.ProtoReflect.Descriptor instead.
func (*GetPastSplitsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetPastSplitsResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetPastSplitsResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetPastSplitsResponse) GetSplits() []*SplitInfo {
	if x != nil {
		return x.Splits
	}
	return nil
}

// Request a calendar of future bond events
type GetFutureBondsEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Instrument symbol
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Start of time interval
	DateFrom *date.Date `protobuf:"bytes,2,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	// End of the time interval. By default, the response covers one year.
	DateTo *date.Date `protobuf:"bytes,3,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	// Sorting direction by date: asc - from old to new, desc - from new to old
	SortDirection SortDirection `protobuf:"varint,4,opt,name=sort_direction,json=sortDirection,proto3,enum=grpc.tradeapi.v1.corporateactions.SortDirection" json:"sort_direction,omitempty"`
	// Limit. Limits the number of events returned for bonds in the list
	Limit int32 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	// Offset. Specifies the number of bond events to skip before returning a result
	Offset        int32 `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFutureBondsEventsRequest) Reset() {
	*x = GetFutureBondsEventsRequest{}
	mi := &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFutureBondsEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFutureBondsEventsRequest) ProtoMessage() {}

func (x *GetFutureBondsEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFutureBondsEventsRequest.ProtoReflect.Descriptor instead.
func (*GetFutureBondsEventsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetFutureBondsEventsRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetFutureBondsEventsRequest) GetDateFrom() *date.Date {
	if x != nil {
		return x.DateFrom
	}
	return nil
}

func (x *GetFutureBondsEventsRequest) GetDateTo() *date.Date {
	if x != nil {
		return x.DateTo
	}
	return nil
}

func (x *GetFutureBondsEventsRequest) GetSortDirection() SortDirection {
	if x != nil {
		return x.SortDirection
	}
	return SortDirection_ASC
}

func (x *GetFutureBondsEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetFutureBondsEventsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// Calendar of future bond events
type GetFutureBondsEventsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Instrument symbol
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Pagination options. The total parameter is ignored.
	Pagination *Pagination `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// Bond events
	Events        []*BondEvent `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFutureBondsEventsResponse) Reset() {
	*x = GetFutureBondsEventsResponse{}
	mi := &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFutureBondsEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFutureBondsEventsResponse) ProtoMessage() {}

func (x *GetFutureBondsEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFutureBondsEventsResponse.ProtoReflect.Descriptor instead.
func (*GetFutureBondsEventsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetFutureBondsEventsResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetFutureBondsEventsResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetFutureBondsEventsResponse) GetEvents() []*BondEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

// Request a calendar of historical bond events
type GetPastBondsEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Instrument symbol
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Start of time interval
	DateFrom *date.Date `protobuf:"bytes,2,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	// End of the time interval. By default, the response covers one year.
	DateTo *date.Date `protobuf:"bytes,3,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	// Sorting direction by date: asc - from old to new, desc - from new to old
	SortDirection SortDirection `protobuf:"varint,4,opt,name=sort_direction,json=sortDirection,proto3,enum=grpc.tradeapi.v1.corporateactions.SortDirection" json:"sort_direction,omitempty"`
	// Limit. Limits the number of events returned for bonds in the list
	Limit int32 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	// Offset. Specifies the number of bond events to skip before returning a result
	Offset        int32 `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPastBondsEventsRequest) Reset() {
	*x = GetPastBondsEventsRequest{}
	mi := &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPastBondsEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPastBondsEventsRequest) ProtoMessage() {}

func (x *GetPastBondsEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPastBondsEventsRequest.ProtoReflect.Descriptor instead.
func (*GetPastBondsEventsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetPastBondsEventsRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetPastBondsEventsRequest) GetDateFrom() *date.Date {
	if x != nil {
		return x.DateFrom
	}
	return nil
}

func (x *GetPastBondsEventsRequest) GetDateTo() *date.Date {
	if x != nil {
		return x.DateTo
	}
	return nil
}

func (x *GetPastBondsEventsRequest) GetSortDirection() SortDirection {
	if x != nil {
		return x.SortDirection
	}
	return SortDirection_ASC
}

func (x *GetPastBondsEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetPastBondsEventsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// Calendar of historical events on bonds
type GetPastBondsEventsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Instrument symbol
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Pagination options. The total parameter is ignored.
	Pagination *Pagination `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// Bond events
	Events        []*BondEvent `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPastBondsEventsResponse) Reset() {
	*x = GetPastBondsEventsResponse{}
	mi := &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPastBondsEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPastBondsEventsResponse) ProtoMessage() {}

func (x *GetPastBondsEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPastBondsEventsResponse.ProtoReflect.Descriptor instead.
func (*GetPastBondsEventsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetPastBondsEventsResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetPastBondsEventsResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetPastBondsEventsResponse) GetEvents() []*BondEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

// Bond event
type BondEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event date
	Date *date.Date `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	// Event type
	Type BondEventType `protobuf:"varint,2,opt,name=type,proto3,enum=grpc.tradeapi.v1.corporateactions.BondEventType" json:"type,omitempty"`
	// Payment amount; may be omitted for offers where only the price is relevant
	Value *decimal.Decimal `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// Payout currency
	Currency *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	// Event specific details
	//
	// Types that are valid to be assigned to EventDetails:
	//
	//	*BondEvent_CouponDetails
	//	*BondEvent_AmortizationDetails
	//	*BondEvent_OfferDetails
	EventDetails  isBondEvent_EventDetails `protobuf_oneof:"event_details"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BondEvent) Reset() {
	*x = BondEvent{}
	mi := &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BondEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BondEvent) ProtoMessage() {}

func (x *BondEvent) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BondEvent.ProtoReflect.Descriptor instead.
func (*BondEvent) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_rawDescGZIP(), []int{8}
}

func (x *BondEvent) GetDate() *date.Date {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *BondEvent) GetType() BondEventType {
	if x != nil {
		return x.Type
	}
	return BondEventType_UNSPECIFIED
}

func (x *BondEvent) GetValue() *decimal.Decimal {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *BondEvent) GetCurrency() *wrapperspb.StringValue {
	if x != nil {
		return x.Currency
	}
	return nil
}

func (x *BondEvent) GetEventDetails() isBondEvent_EventDetails {
	if x != nil {
		return x.EventDetails
	}
	return nil
}

func (x *BondEvent) GetCouponDetails() *CouponEventDetails {
	if x != nil {
		if x, ok := x.EventDetails.(*BondEvent_CouponDetails); ok {
			return x.CouponDetails
		}
	}
	return nil
}

func (x *BondEvent) GetAmortizationDetails() *AmortizationEventDetails {
	if x != nil {
		if x, ok := x.EventDetails.(*BondEvent_AmortizationDetails); ok {
			return x.AmortizationDetails
		}
	}
	return nil
}

func (x *BondEvent) GetOfferDetails() *OfferEventDetails {
	if x != nil {
		if x, ok := x.EventDetails.(*BondEvent_OfferDetails); ok {
			return x.OfferDetails
		}
	}
	return nil
}

type isBondEvent_EventDetails interface {
	isBondEvent_EventDetails()
}

type BondEvent_CouponDetails struct {
	// Coupon payment details
	CouponDetails *CouponEventDetails `protobuf:"bytes,5,opt,name=coupon_details,json=couponDetails,proto3,oneof"`
}

type BondEvent_AmortizationDetails struct {
	// Details of amortization (partial repayment of bond par value)
	AmortizationDetails *AmortizationEventDetails `protobuf:"bytes,6,opt,name=amortization_details,json=amortizationDetails,proto3,oneof"`
}

type BondEvent_OfferDetails struct {
	// Offer details (early repurchase or repayment event)
	OfferDetails *OfferEventDetails `protobuf:"bytes,7,opt,name=offer_details,json=offerDetails,proto3,oneof"`
}

func (*BondEvent_CouponDetails) isBondEvent_EventDetails() {}

func (*BondEvent_AmortizationDetails) isBondEvent_EventDetails() {}

func (*BondEvent_OfferDetails) isBondEvent_EventDetails() {}

// Coupon payment details
type CouponEventDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Record Date
	RecordDate *date.Date `protobuf:"bytes,1,opt,name=record_date,json=recordDate,proto3" json:"record_date,omitempty"`
	// Coupon period start date
	StartDate *date.Date `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	// Face value used to calculate the coupon
	FaceValue *decimal.Decimal `protobuf:"bytes,3,opt,name=face_value,json=faceValue,proto3" json:"face_value,omitempty"`
	// Coupon rate as a percentage
	ValuePercent  *decimal.Decimal `protobuf:"bytes,4,opt,name=value_percent,json=valuePercent,proto3" json:"value_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CouponEventDetails) Reset() {
	*x = CouponEventDetails{}
	mi := &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponEventDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponEventDetails) ProtoMessage() {}

func (x *CouponEventDetails) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponEventDetails.ProtoReflect.Descriptor instead.
func (*CouponEventDetails) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_rawDescGZIP(), []int{9}
}

func (x *CouponEventDetails) GetRecordDate() *date.Date {
	if x != nil {
		return x.RecordDate
	}
	return nil
}

func (x *CouponEventDetails) GetStartDate() *date.Date {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *CouponEventDetails) GetFaceValue() *decimal.Decimal {
	if x != nil {
		return x.FaceValue
	}
	return nil
}

func (x *CouponEventDetails) GetValuePercent() *decimal.Decimal {
	if x != nil {
		return x.ValuePercent
	}
	return nil
}

// Amortization details (partial repayment of bond face value)
type AmortizationEventDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Remaining face value after amortization
	NewFaceValue *decimal.Decimal `protobuf:"bytes,1,opt,name=new_face_value,json=newFaceValue,proto3" json:"new_face_value,omitempty"`
	// Original security face value
	InitialFaceValue *decimal.Decimal `protobuf:"bytes,2,opt,name=initial_face_value,json=initialFaceValue,proto3" json:"initial_face_value,omitempty"`
	// Amortized percentage of face value
	AmortizationPercent *decimal.Decimal `protobuf:"bytes,3,opt,name=amortization_percent,json=amortizationPercent,proto3" json:"amortization_percent,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AmortizationEventDetails) Reset() {
	*x = AmortizationEventDetails{}
	mi := &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AmortizationEventDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AmortizationEventDetails) ProtoMessage() {}

func (x *AmortizationEventDetails) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AmortizationEventDetails.ProtoReflect.Descriptor instead.
func (*AmortizationEventDetails) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_rawDescGZIP(), []int{10}
}

func (x *AmortizationEventDetails) GetNewFaceValue() *decimal.Decimal {
	if x != nil {
		return x.NewFaceValue
	}
	return nil
}

func (x *AmortizationEventDetails) GetInitialFaceValue() *decimal.Decimal {
	if x != nil {
		return x.InitialFaceValue
	}
	return nil
}

func (x *AmortizationEventDetails) GetAmortizationPercent() *decimal.Decimal {
	if x != nil {
		return x.AmortizationPercent
	}
	return nil
}

// Offer details (early repurchase or repayment event)
type OfferEventDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PUT or CALL
	OfferType *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=offer_type,json=offerType,proto3" json:"offer_type,omitempty"`
	// Offer price as a percentage of face value (or in currency)
	Price *decimal.Decimal `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	// Start date of the offer submission period
	StartDate *date.Date `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	// End date of the offer submission period
	EndDate *date.Date `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	// Offer agent
	Agent         *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfferEventDetails) Reset() {
	*x = OfferEventDetails{}
	mi := &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfferEventDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferEventDetails) ProtoMessage() {}

func (x *OfferEventDetails) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferEventDetails.ProtoReflect.Descriptor instead.
func (*OfferEventDetails) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_rawDescGZIP(), []int{11}
}

func (x *OfferEventDetails) GetOfferType() *wrapperspb.StringValue {
	if x != nil {
		return x.OfferType
	}
	return nil
}

func (x *OfferEventDetails) GetPrice() *decimal.Decimal {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *OfferEventDetails) GetStartDate() *date.Date {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *OfferEventDetails) GetEndDate() *date.Date {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *OfferEventDetails) GetAgent() *wrapperspb.StringValue {
	if x != nil {
		return x.Agent
	}
	return nil
}

// Corporate Action Information
type SplitInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Effective date of the corporate action (execution date)
	ExecDate *date.Date `protobuf:"bytes,1,opt,name=exec_date,json=execDate,proto3" json:"exec_date,omitempty"`
	// Number of securities before conversion (numerator of the coefficient)
	OldRatio *decimal.Decimal `protobuf:"bytes,2,opt,name=old_ratio,json=oldRatio,proto3" json:"old_ratio,omitempty"`
	// Number of securities after conversion (coefficient denominator)
	NewRatio *decimal.Decimal `protobuf:"bytes,3,opt,name=new_ratio,json=newRatio,proto3" json:"new_ratio,omitempty"`
	// New instrument lot size after execution of a corporate action
	NewLot *wrapperspb.Int32Value `protobuf:"bytes,4,opt,name=new_lot,json=newLot,proto3" json:"new_lot,omitempty"`
	// Event type (split/consolidation, etc.)
	ConvertationType ConvertationType `protobuf:"varint,5,opt,name=convertation_type,json=convertationType,proto3,enum=grpc.tradeapi.v1.corporateactions.ConvertationType" json:"convertation_type,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SplitInfo) Reset() {
	*x = SplitInfo{}
	mi := &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitInfo) ProtoMessage() {}

func (x *SplitInfo) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitInfo.ProtoReflect.Descriptor instead.
func (*SplitInfo) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_rawDescGZIP(), []int{12}
}

func (x *SplitInfo) GetExecDate() *date.Date {
	if x != nil {
		return x.ExecDate
	}
	return nil
}

func (x *SplitInfo) GetOldRatio() *decimal.Decimal {
	if x != nil {
		return x.OldRatio
	}
	return nil
}

func (x *SplitInfo) GetNewRatio() *decimal.Decimal {
	if x != nil {
		return x.NewRatio
	}
	return nil
}

func (x *SplitInfo) GetNewLot() *wrapperspb.Int32Value {
	if x != nil {
		return x.NewLot
	}
	return nil
}

func (x *SplitInfo) GetConvertationType() ConvertationType {
	if x != nil {
		return x.ConvertationType
	}
	return ConvertationType_CONVTYPE_UNKNOWN
}

// Request to receive a list of upcoming dividend payments for an instrument
type GetFutureDividendsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Instrument symbol
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Sorting direction by date: asc - from old to new, desc - from new to old.
	SortDirection SortDirection `protobuf:"varint,2,opt,name=sort_direction,json=sortDirection,proto3,enum=grpc.tradeapi.v1.corporateactions.SortDirection" json:"sort_direction,omitempty"`
	// Limit. Limits the number of elements returned
	Limit int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// Offset. Specifies how many items to skip before returning results.
	Offset        int32 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFutureDividendsRequest) Reset() {
	*x = GetFutureDividendsRequest{}
	mi := &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFutureDividendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFutureDividendsRequest) ProtoMessage() {}

func (x *GetFutureDividendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFutureDividendsRequest.ProtoReflect.Descriptor instead.
func (*GetFutureDividendsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetFutureDividendsRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetFutureDividendsRequest) GetSortDirection() SortDirection {
	if x != nil {
		return x.SortDirection
	}
	return SortDirection_ASC
}

func (x *GetFutureDividendsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetFutureDividendsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// List of upcoming dividend payments for an instrument with pagination
type GetFutureDividendsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pagination options
	Pagination *Pagination `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// List of dividends
	Dividends     []*Dividend `protobuf:"bytes,2,rep,name=dividends,proto3" json:"dividends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFutureDividendsResponse) Reset() {
	*x = GetFutureDividendsResponse{}
	mi := &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFutureDividendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFutureDividendsResponse) ProtoMessage() {}

func (x *GetFutureDividendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFutureDividendsResponse.ProtoReflect.Descriptor instead.
func (*GetFutureDividendsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetFutureDividendsResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetFutureDividendsResponse) GetDividends() []*Dividend {
	if x != nil {
		return x.Dividends
	}
	return nil
}

// Request to obtain historical data on dividends paid for an instrument
type GetPastDividendsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Instrument symbol
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Sorting direction by date: asc - from old to new, desc - from new to old.
	SortDirection SortDirection `protobuf:"varint,2,opt,name=sort_direction,json=sortDirection,proto3,enum=grpc.tradeapi.v1.corporateactions.SortDirection" json:"sort_direction,omitempty"`
	// Start of time interval
	DateFrom *date.Date `protobuf:"bytes,3,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	// End of time interval
	DateTo *date.Date `protobuf:"bytes,4,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	// Limit. Limits the number of elements returned
	Limit int32 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	// Offset. Specifies how many items to skip before returning results.
	Offset        int32 `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPastDividendsRequest) Reset() {
	*x = GetPastDividendsRequest{}
	mi := &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPastDividendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPastDividendsRequest) ProtoMessage() {}

func (x *GetPastDividendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPastDividendsRequest.ProtoReflect.Descriptor instead.
func (*GetPastDividendsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetPastDividendsRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetPastDividendsRequest) GetSortDirection() SortDirection {
	if x != nil {
		return x.SortDirection
	}
	return SortDirection_ASC
}

func (x *GetPastDividendsRequest) GetDateFrom() *date.Date {
	if x != nil {
		return x.DateFrom
	}
	return nil
}

func (x *GetPastDividendsRequest) GetDateTo() *date.Date {
	if x != nil {
		return x.DateTo
	}
	return nil
}

func (x *GetPastDividendsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetPastDividendsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// Historical data on dividends paid for an instrument with pagination
type GetPastDividendsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pagination options
	Pagination *Pagination `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// List of dividends
	Dividends     []*Dividend `protobuf:"bytes,2,rep,name=dividends,proto3" json:"dividends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPastDividendsResponse) Reset() {
	*x = GetPastDividendsResponse{}
	mi := &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPastDividendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPastDividendsResponse) ProtoMessage() {}

func (x *GetPastDividendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPastDividendsResponse.ProtoReflect.Descriptor instead.
func (*GetPastDividendsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_rawDescGZIP(), []int{16}
}

func (x *GetPastDividendsResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetPastDividendsResponse) GetDividends() []*Dividend {
	if x != nil {
		return x.Dividends
	}
	return nil
}

// Information about dividend payment
type Dividend struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Registry closing date
	Date *date.Date `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	// Dividend per share
	Amount *decimal.Decimal `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// Dividend payment currency
	Currency      string `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dividend) Reset() {
	*x = Dividend{}
	mi := &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dividend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dividend) ProtoMessage() {}

func (x *Dividend) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dividend.ProtoReflect.Descriptor instead.
func (*Dividend) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_rawDescGZIP(), []int{17}
}

func (x *Dividend) GetDate() *date.Date {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *Dividend) GetAmount() *decimal.Decimal {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Dividend) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

// Pagination options
type Pagination struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total number of elements
	Total int32 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// Limit. Limits the number of elements returned
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// Offset. Specifies how many items to skip before returning results.
	Offset int32 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	// Next page flag. Indicates whether the next page of data exists
	HasNext       bool `protobuf:"varint,4,opt,name=has_next,json=hasNext,proto3" json:"has_next,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_rawDescGZIP(), []int{18}
}

func (x *Pagination) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Pagination) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Pagination) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Pagination) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

var File_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto protoreflect.FileDescriptor

const file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_rawDesc = "" +
	"\n" +
	"Agrpc/tradeapi/v1/corporateactions/corporate_actions_service.proto\x12!grpc.tradeapi.v1.corporateactions\x1a\x1cgoogle/api/annotations.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a;grpc/gateway/protoc_gen_openapiv2/options/annotations.proto\x1a\x19google/type/decimal.proto\x1a\x16google/type/date.proto\"\xb7\x01\n" +
	"\x16GetFutureSplitsRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12W\n" +
	"\x0esort_direction\x18\x02 \x01(\x0e20.grpc.tradeapi.v1.corporateactions.SortDirectionR\rsortDirection\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"\xc6\x01\n" +
	"\x17GetFutureSplitsResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12M\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2-.grpc.tradeapi.v1.corporateactions.PaginationR\n" +
	"pagination\x12D\n" +
	"\x06splits\x18\x03 \x03(\v2,.grpc.tradeapi.v1.corporateactions.SplitInfoR\x06splits\"\x91\x02\n" +
	"\x14GetPastSplitsRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12.\n" +
	"\tdate_from\x18\x02 \x01(\v2\x11.google.type.DateR\bdateFrom\x12*\n" +
	"\adate_to\x18\x03 \x01(\v2\x11.google.type.DateR\x06dateTo\x12W\n" +
	"\x0esort_direction\x18\x04 \x01(\x0e20.grpc.tradeapi.v1.corporateactions.SortDirectionR\rsortDirection\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x05R\x06offset\"\xc4\x01\n" +
	"\x15GetPastSplitsResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12M\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2-.grpc.tradeapi.v1.corporateactions.PaginationR\n" +
	"pagination\x12D\n" +
	"\x06splits\x18\x03 \x03(\v2,.grpc.tradeapi.v1.corporateactions.SplitInfoR\x06splits\"\x98\x02\n" +
	"\x1bGetFutureBondsEventsRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12.\n" +
	"\tdate_from\x18\x02 \x01(\v2\x11.google.type.DateR\bdateFrom\x12*\n" +
	"\adate_to\x18\x03 \x01(\v2\x11.google.type.DateR\x06dateTo\x12W\n" +
	"\x0esort_direction\x18\x04 \x01(\x0e20.grpc.tradeapi.v1.corporateactions.SortDirectionR\rsortDirection\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x05R\x06offset\"\xcb\x01\n" +
	"\x1cGetFutureBondsEventsResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12M\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2-.grpc.tradeapi.v1.corporateactions.PaginationR\n" +
	"pagination\x12D\n" +
	"\x06events\x18\x03 \x03(\v2,.grpc.tradeapi.v1.corporateactions.BondEventR\x06events\"\x96\x02\n" +
	"\x19GetPastBondsEventsRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12.\n" +
	"\tdate_from\x18\x02 \x01(\v2\x11.google.type.DateR\bdateFrom\x12*\n" +
	"\adate_to\x18\x03 \x01(\v2\x11.google.type.DateR\x06dateTo\x12W\n" +
	"\x0esort_direction\x18\x04 \x01(\x0e20.grpc.tradeapi.v1.corporateactions.SortDirectionR\rsortDirection\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x05R\x06offset\"\xc9\x01\n" +
	"\x1aGetPastBondsEventsResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12M\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2-.grpc.tradeapi.v1.corporateactions.PaginationR\n" +
	"pagination\x12D\n" +
	"\x06events\x18\x03 \x03(\v2,.grpc.tradeapi.v1.corporateactions.BondEventR\x06events\"\x9e\x04\n" +
	"\tBondEvent\x12%\n" +
	"\x04date\x18\x01 \x01(\v2\x11.google.type.DateR\x04date\x12D\n" +
	"\x04type\x18\x02 \x01(\x0e20.grpc.tradeapi.v1.corporateactions.BondEventTypeR\x04type\x12*\n" +
	"\x05value\x18\x03 \x01(\v2\x14.google.type.DecimalR\x05value\x128\n" +
	"\bcurrency\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\bcurrency\x12^\n" +
	"\x0ecoupon_details\x18\x05 \x01(\v25.grpc.tradeapi.v1.corporateactions.CouponEventDetailsH\x00R\rcouponDetails\x12p\n" +
	"\x14amortization_details\x18\x06 \x01(\v2;.grpc.tradeapi.v1.corporateactions.AmortizationEventDetailsH\x00R\x13amortizationDetails\x12[\n" +
	"\roffer_details\x18\a \x01(\v24.grpc.tradeapi.v1.corporateactions.OfferEventDetailsH\x00R\fofferDetailsB\x0f\n" +
	"\revent_details\"\xea\x01\n" +
	"\x12CouponEventDetails\x122\n" +
	"\vrecord_date\x18\x01 \x01(\v2\x11.google.type.DateR\n" +
	"recordDate\x120\n" +
	"\n" +
	"start_date\x18\x02 \x01(\v2\x11.google.type.DateR\tstartDate\x123\n" +
	"\n" +
	"face_value\x18\x03 \x01(\v2\x14.google.type.DecimalR\tfaceValue\x129\n" +
	"\rvalue_percent\x18\x04 \x01(\v2\x14.google.type.DecimalR\fvaluePercent\"\xe3\x01\n" +
	"\x18AmortizationEventDetails\x12:\n" +
	"\x0enew_face_value\x18\x01 \x01(\v2\x14.google.type.DecimalR\fnewFaceValue\x12B\n" +
	"\x12initial_face_value\x18\x02 \x01(\v2\x14.google.type.DecimalR\x10initialFaceValue\x12G\n" +
	"\x14amortization_percent\x18\x03 \x01(\v2\x14.google.type.DecimalR\x13amortizationPercent\"\x90\x02\n" +
	"\x11OfferEventDetails\x12;\n" +
	"\n" +
	"offer_type\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\tofferType\x12*\n" +
	"\x05price\x18\x02 \x01(\v2\x14.google.type.DecimalR\x05price\x120\n" +
	"\n" +
	"start_date\x18\x03 \x01(\v2\x11.google.type.DateR\tstartDate\x12,\n" +
	"\bend_date\x18\x04 \x01(\v2\x11.google.type.DateR\aendDate\x122\n" +
	"\x05agent\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\x05agent\"\xb9\x02\n" +
	"\tSplitInfo\x12.\n" +
	"\texec_date\x18\x01 \x01(\v2\x11.google.type.DateR\bexecDate\x121\n" +
	"\told_ratio\x18\x02 \x01(\v2\x14.google.type.DecimalR\boldRatio\x121\n" +
	"\tnew_ratio\x18\x03 \x01(\v2\x14.google.type.DecimalR\bnewRatio\x124\n" +
	"\anew_lot\x18\x04 \x01(\v2\x1b.google.protobuf.Int32ValueR\x06newLot\x12`\n" +
	"\x11convertation_type\x18\x05 \x01(\x0e23.grpc.tradeapi.v1.corporateactions.ConvertationTypeR\x10convertationType\"\xba\x01\n" +
	"\x19GetFutureDividendsRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12W\n" +
	"\x0esort_direction\x18\x02 \x01(\x0e20.grpc.tradeapi.v1.corporateactions.SortDirectionR\rsortDirection\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"\xb6\x01\n" +
	"\x1aGetFutureDividendsResponse\x12M\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2-.grpc.tradeapi.v1.corporateactions.PaginationR\n" +
	"pagination\x12I\n" +
	"\tdividends\x18\x02 \x03(\v2+.grpc.tradeapi.v1.corporateactions.DividendR\tdividends\"\x94\x02\n" +
	"\x17GetPastDividendsRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12W\n" +
	"\x0esort_direction\x18\x02 \x01(\x0e20.grpc.tradeapi.v1.corporateactions.SortDirectionR\rsortDirection\x12.\n" +
	"\tdate_from\x18\x03 \x01(\v2\x11.google.type.DateR\bdateFrom\x12*\n" +
	"\adate_to\x18\x04 \x01(\v2\x11.google.type.DateR\x06dateTo\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x05R\x06offset\"\xb4\x01\n" +
	"\x18GetPastDividendsResponse\x12M\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2-.grpc.tradeapi.v1.corporateactions.PaginationR\n" +
	"pagination\x12I\n" +
	"\tdividends\x18\x02 \x03(\v2+.grpc.tradeapi.v1.corporateactions.DividendR\tdividends\"{\n" +
	"\bDividend\x12%\n" +
	"\x04date\x18\x01 \x01(\v2\x11.google.type.DateR\x04date\x12,\n" +
	"\x06amount\x18\x02 \x01(\v2\x14.google.type.DecimalR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\"k\n" +
	"\n" +
	"Pagination\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x19\n" +
	"\bhas_next\x18\x04 \x01(\bR\ahasNext*I\n" +
	"\rBondEventType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06COUPON\x10\x01\x12\x10\n" +
	"\fAMORTIZATION\x10\x02\x12\t\n" +
	"\x05OFFER\x10\x03*\xd5\x01\n" +
	"\x10ConvertationType\x12\x14\n" +
	"\x10CONVTYPE_UNKNOWN\x10\x00\x12\v\n" +
	"\aBUYBACK\x10\x01\x12\x19\n" +
	"\x15CALL_OPTION_EXERCISED\x10\x02\x12\f\n" +
	"\bDRAWINGS\x10\x03\x12\x17\n" +
	"\x13DRAWINGS_BY_LOTTERY\x10\x04\x12\x14\n" +
	"\x10EARLY_CONVERSION\x10\x05\x12\f\n" +
	"\bMATURITY\x10\x06\x12\f\n" +
	"\bORDINARY\x10\a\x12\x18\n" +
	"\x14PUT_OPTION_EXERCISED\x10\b\x12\x10\n" +
	"\fTENDER_OFFER\x10\t*\"\n" +
	"\rSortDirection\x12\a\n" +
	"\x03ASC\x10\x00\x12\b\n" +
	"\x04DESC\x10\x012\xe7\n" +
	"\n" +
	"\x17CorporateActionsService\x12\xbb\x01\n" +
	"\x0fGetFutureSplits\x129.grpc.tradeapi.v1.corporateactions.GetFutureSplitsRequest\x1a:.grpc.tradeapi.v1.corporateactions.GetFutureSplitsResponse\"1\x92A\x15b\x13\n" +
	"\x11\n" +
	"\rAuthorization\x12\x00\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/splits/future\x12\xb3\x01\n" +
	"\rGetPastSplits\x127.grpc.tradeapi.v1.corporateactions.GetPastSplitsRequest\x1a8.grpc.tradeapi.v1.corporateactions.GetPastSplitsResponse\"/\x92A\x15b\x13\n" +
	"\x11\n" +
	"\rAuthorization\x12\x00\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/splits/past\x12\xc9\x01\n" +
	"\x14GetFutureBondsEvents\x12>.grpc.tradeapi.v1.corporateactions.GetFutureBondsEventsRequest\x1a?.grpc.tradeapi.v1.corporateactions.GetFutureBondsEventsResponse\"0\x92A\x15b\x13\n" +
	"\x11\n" +
	"\rAuthorization\x12\x00\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/bonds/future\x12\xc1\x01\n" +
	"\x12GetPastBondsEvents\x12<.grpc.tradeapi.v1.corporateactions.GetPastBondsEventsRequest\x1a=.grpc.tradeapi.v1.corporateactions.GetPastBondsEventsResponse\".\x92A\x15b\x13\n" +
	"\x11\n" +
	"\rAuthorization\x12\x00\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/bonds/past\x12\xa0\x02\n" +
	"\x12GetFutureDividends\x12<.grpc.tradeapi.v1.corporateactions.GetFutureDividendsRequest\x1a=.grpc.tradeapi.v1.corporateactions.GetFutureDividendsResponse\"\x8c\x01\x92AmJV\n" +
	"\x03400\x12O\n" +
	"MInvalid symbol. The symbol must use ticker@mic format, for example SBER@MISX.b\x13\n" +
	"\x11\n" +
	"\rAuthorization\x12\x00\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/future-dividends\x12\xa4\x02\n" +
	"\x10GetPastDividends\x12:.grpc.tradeapi.v1.corporateactions.GetPastDividendsRequest\x1a;.grpc.tradeapi.v1.corporateactions.GetPastDividendsResponse\"\x96\x01\x92AyJb\n" +
	"\x03400\x12[\n" +
	"YInvalid symbol or interval. The symbol must use ticker@mic format, for example SBER@MISX.b\x13\n" +
	"\x11\n" +
	"\rAuthorization\x12\x00\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/past-dividendsB\x98\x04\x92A\xc5\x03\x12'\n" +
	"\tTrade API\x12\x1aAPI for trading operations*\x02\x01\x02R-\n" +
	"\x03401\x12&\n" +
	"$The token has expired or is invalid.RK\n" +
	"\x03429\x12D\n" +
	"BToo many requests. The available limit is 200 requests per minute.R1\n" +
	"\x03500\x12*\n" +
	"(Internal service error. Try again later.R?\n" +
	"\x03503\x128\n" +
	"6The service is currently unavailable. Try again later.RB\n" +
	"\x03504\x12;\n" +
	"9The deadline was exceeded before the operation completed.R!\n" +
	"\adefault\x12\x16\x12\x14\n" +
	"\x12\x1a\x10googletypeStatusZ?\n" +
	"=\n" +
	"\rAuthorization\x12,\b\x02\x12\x17JWT authorization token\x1a\rAuthorization \x02P\x01ZKgithub.com/your-organization/trade-api/go/grpc/tradeapi/v1/corporateactionsb\x06proto3"

var (
	file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_rawDescOnce sync.Once
	file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_rawDescData []byte
)

func file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_rawDescGZIP() []byte {
	file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_rawDescOnce.Do(func() {
		file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_rawDesc), len(file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_rawDesc)))
	})
	return file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_rawDescData
}

var file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_goTypes = []any{
	(BondEventType)(0),                   // 0: grpc.tradeapi.v1.corporateactions.BondEventType
	(ConvertationType)(0),                // 1: grpc.tradeapi.v1.corporateactions.ConvertationType
	(SortDirection)(0),                   // 2: grpc.tradeapi.v1.corporateactions.SortDirection
	(*GetFutureSplitsRequest)(nil),       // 3: grpc.tradeapi.v1.corporateactions.GetFutureSplitsRequest
	(*GetFutureSplitsResponse)(nil),      // 4: grpc.tradeapi.v1.corporateactions.GetFutureSplitsResponse
	(*GetPastSplitsRequest)(nil),         // 5: grpc.tradeapi.v1.corporateactions.GetPastSplitsRequest
	(*GetPastSplitsResponse)(nil),        // 6: grpc.tradeapi.v1.corporateactions.GetPastSplitsResponse
	(*GetFutureBondsEventsRequest)(nil),  // 7: grpc.tradeapi.v1.corporateactions.GetFutureBondsEventsRequest
	(*GetFutureBondsEventsResponse)(nil), // 8: grpc.tradeapi.v1.corporateactions.GetFutureBondsEventsResponse
	(*GetPastBondsEventsRequest)(nil),    // 9: grpc.tradeapi.v1.corporateactions.GetPastBondsEventsRequest
	(*GetPastBondsEventsResponse)(nil),   // 10: grpc.tradeapi.v1.corporateactions.GetPastBondsEventsResponse
	(*BondEvent)(nil),                    // 11: grpc.tradeapi.v1.corporateactions.BondEvent
	(*CouponEventDetails)(nil),           // 12: grpc.tradeapi.v1.corporateactions.CouponEventDetails
	(*AmortizationEventDetails)(nil),     // 13: grpc.tradeapi.v1.corporateactions.AmortizationEventDetails
	(*OfferEventDetails)(nil),            // 14: grpc.tradeapi.v1.corporateactions.OfferEventDetails
	(*SplitInfo)(nil),                    // 15: grpc.tradeapi.v1.corporateactions.SplitInfo
	(*GetFutureDividendsRequest)(nil),    // 16: grpc.tradeapi.v1.corporateactions.GetFutureDividendsRequest
	(*GetFutureDividendsResponse)(nil),   // 17: grpc.tradeapi.v1.corporateactions.GetFutureDividendsResponse
	(*GetPastDividendsRequest)(nil),      // 18: grpc.tradeapi.v1.corporateactions.GetPastDividendsRequest
	(*GetPastDividendsResponse)(nil),     // 19: grpc.tradeapi.v1.corporateactions.GetPastDividendsResponse
	(*Dividend)(nil),                     // 20: grpc.tradeapi.v1.corporateactions.Dividend
	(*Pagination)(nil),                   // 21: grpc.tradeapi.v1.corporateactions.Pagination
	(*date.Date)(nil),                    // 22: google.type.Date
	(*decimal.Decimal)(nil),              // 23: google.type.Decimal
	(*wrapperspb.StringValue)(nil),       // 24: google.protobuf.StringValue
	(*wrapperspb.Int32Value)(nil),        // 25: google.protobuf.Int32Value
}
var file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_depIdxs = []int32{
	2,  // 0: grpc.tradeapi.v1.corporateactions.GetFutureSplitsRequest.sort_direction:type_name -> grpc.tradeapi.v1.corporateactions.SortDirection
	21, // 1: grpc.tradeapi.v1.corporateactions.GetFutureSplitsResponse.pagination:type_name -> grpc.tradeapi.v1.corporateactions.Pagination
	15, // 2: grpc.tradeapi.v1.corporateactions.GetFutureSplitsResponse.splits:type_name -> grpc.tradeapi.v1.corporateactions.SplitInfo
	22, // 3: grpc.tradeapi.v1.corporateactions.GetPastSplitsRequest.date_from:type_name -> google.type.Date
	22, // 4: grpc.tradeapi.v1.corporateactions.GetPastSplitsRequest.date_to:type_name -> google.type.Date
	2,  // 5: grpc.tradeapi.v1.corporateactions.GetPastSplitsRequest.sort_direction:type_name -> grpc.tradeapi.v1.corporateactions.SortDirection
	21, // 6: grpc.tradeapi.v1.corporateactions.GetPastSplitsResponse.pagination:type_name -> grpc.tradeapi.v1.corporateactions.Pagination
	15, // 7: grpc.tradeapi.v1.corporateactions.GetPastSplitsResponse.splits:type_name -> grpc.tradeapi.v1.corporateactions.SplitInfo
	22, // 8: grpc.tradeapi.v1.corporateactions.GetFutureBondsEventsRequest.date_from:type_name -> google.type.Date
	22, // 9: grpc.tradeapi.v1.corporateactions.GetFutureBondsEventsRequest.date_to:type_name -> google.type.Date
	2,  // 10: grpc.tradeapi.v1.corporateactions.GetFutureBondsEventsRequest.sort_direction:type_name -> grpc.tradeapi.v1.corporateactions.SortDirection
	21, // 11: grpc.tradeapi.v1.corporateactions.GetFutureBondsEventsResponse.pagination:type_name -> grpc.tradeapi.v1.corporateactions.Pagination
	11, // 12: grpc.tradeapi.v1.corporateactions.GetFutureBondsEventsResponse.events:type_name -> grpc.tradeapi.v1.corporateactions.BondEvent
	22, // 13: grpc.tradeapi.v1.corporateactions.GetPastBondsEventsRequest.date_from:type_name -> google.type.Date
	22, // 14: grpc.tradeapi.v1.corporateactions.GetPastBondsEventsRequest.date_to:type_name -> google.type.Date
	2,  // 15: grpc.tradeapi.v1.corporateactions.GetPastBondsEventsRequest.sort_direction:type_name -> grpc.tradeapi.v1.corporateactions.SortDirection
	21, // 16: grpc.tradeapi.v1.corporateactions.GetPastBondsEventsResponse.pagination:type_name -> grpc.tradeapi.v1.corporateactions.Pagination
	11, // 17: grpc.tradeapi.v1.corporateactions.GetPastBondsEventsResponse.events:type_name -> grpc.tradeapi.v1.corporateactions.BondEvent
	22, // 18: grpc.tradeapi.v1.corporateactions.BondEvent.date:type_name -> google.type.Date
	0,  // 19: grpc.tradeapi.v1.corporateactions.BondEvent.type:type_name -> grpc.tradeapi.v1.corporateactions.BondEventType
	23, // 20: grpc.tradeapi.v1.corporateactions.BondEvent.value:type_name -> google.type.Decimal
	24, // 21: grpc.tradeapi.v1.corporateactions.BondEvent.currency:type_name -> google.protobuf.StringValue
	12, // 22: grpc.tradeapi.v1.corporateactions.BondEvent.coupon_details:type_name -> grpc.tradeapi.v1.corporateactions.CouponEventDetails
	13, // 23: grpc.tradeapi.v1.corporateactions.BondEvent.amortization_details:type_name -> grpc.tradeapi.v1.corporateactions.AmortizationEventDetails
	14, // 24: grpc.tradeapi.v1.corporateactions.BondEvent.offer_details:type_name -> grpc.tradeapi.v1.corporateactions.OfferEventDetails
	22, // 25: grpc.tradeapi.v1.corporateactions.CouponEventDetails.record_date:type_name -> google.type.Date
	22, // 26: grpc.tradeapi.v1.corporateactions.CouponEventDetails.start_date:type_name -> google.type.Date
	23, // 27: grpc.tradeapi.v1.corporateactions.CouponEventDetails.face_value:type_name -> google.type.Decimal
	23, // 28: grpc.tradeapi.v1.corporateactions.CouponEventDetails.value_percent:type_name -> google.type.Decimal
	23, // 29: grpc.tradeapi.v1.corporateactions.AmortizationEventDetails.new_face_value:type_name -> google.type.Decimal
	23, // 30: grpc.tradeapi.v1.corporateactions.AmortizationEventDetails.initial_face_value:type_name -> google.type.Decimal
	23, // 31: grpc.tradeapi.v1.corporateactions.AmortizationEventDetails.amortization_percent:type_name -> google.type.Decimal
	24, // 32: grpc.tradeapi.v1.corporateactions.OfferEventDetails.offer_type:type_name -> google.protobuf.StringValue
	23, // 33: grpc.tradeapi.v1.corporateactions.OfferEventDetails.price:type_name -> google.type.Decimal
	22, // 34: grpc.tradeapi.v1.corporateactions.OfferEventDetails.start_date:type_name -> google.type.Date
	22, // 35: grpc.tradeapi.v1.corporateactions.OfferEventDetails.end_date:type_name -> google.type.Date
	24, // 36: grpc.tradeapi.v1.corporateactions.OfferEventDetails.agent:type_name -> google.protobuf.StringValue
	22, // 37: grpc.tradeapi.v1.corporateactions.SplitInfo.exec_date:type_name -> google.type.Date
	23, // 38: grpc.tradeapi.v1.corporateactions.SplitInfo.old_ratio:type_name -> google.type.Decimal
	23, // 39: grpc.tradeapi.v1.corporateactions.SplitInfo.new_ratio:type_name -> google.type.Decimal
	25, // 40: grpc.tradeapi.v1.corporateactions.SplitInfo.new_lot:type_name -> google.protobuf.Int32Value
	1,  // 41: grpc.tradeapi.v1.corporateactions.SplitInfo.convertation_type:type_name -> grpc.tradeapi.v1.corporateactions.ConvertationType
	2,  // 42: grpc.tradeapi.v1.corporateactions.GetFutureDividendsRequest.sort_direction:type_name -> grpc.tradeapi.v1.corporateactions.SortDirection
	21, // 43: grpc.tradeapi.v1.corporateactions.GetFutureDividendsResponse.pagination:type_name -> grpc.tradeapi.v1.corporateactions.Pagination
	20, // 44: grpc.tradeapi.v1.corporateactions.GetFutureDividendsResponse.dividends:type_name -> grpc.tradeapi.v1.corporateactions.Dividend
	2,  // 45: grpc.tradeapi.v1.corporateactions.GetPastDividendsRequest.sort_direction:type_name -> grpc.tradeapi.v1.corporateactions.SortDirection
	22, // 46: grpc.tradeapi.v1.corporateactions.GetPastDividendsRequest.date_from:type_name -> google.type.Date
	22, // 47: grpc.tradeapi.v1.corporateactions.GetPastDividendsRequest.date_to:type_name -> google.type.Date
	21, // 48: grpc.tradeapi.v1.corporateactions.GetPastDividendsResponse.pagination:type_name -> grpc.tradeapi.v1.corporateactions.Pagination
	20, // 49: grpc.tradeapi.v1.corporateactions.GetPastDividendsResponse.dividends:type_name -> grpc.tradeapi.v1.corporateactions.Dividend
	22, // 50: grpc.tradeapi.v1.corporateactions.Dividend.date:type_name -> google.type.Date
	23, // 51: grpc.tradeapi.v1.corporateactions.Dividend.amount:type_name -> google.type.Decimal
	3,  // 52: grpc.tradeapi.v1.corporateactions.CorporateActionsService.GetFutureSplits:input_type -> grpc.tradeapi.v1.corporateactions.GetFutureSplitsRequest
	5,  // 53: grpc.tradeapi.v1.corporateactions.CorporateActionsService.GetPastSplits:input_type -> grpc.tradeapi.v1.corporateactions.GetPastSplitsRequest
	7,  // 54: grpc.tradeapi.v1.corporateactions.CorporateActionsService.GetFutureBondsEvents:input_type -> grpc.tradeapi.v1.corporateactions.GetFutureBondsEventsRequest
	9,  // 55: grpc.tradeapi.v1.corporateactions.CorporateActionsService.GetPastBondsEvents:input_type -> grpc.tradeapi.v1.corporateactions.GetPastBondsEventsRequest
	16, // 56: grpc.tradeapi.v1.corporateactions.CorporateActionsService.GetFutureDividends:input_type -> grpc.tradeapi.v1.corporateactions.GetFutureDividendsRequest
	18, // 57: grpc.tradeapi.v1.corporateactions.CorporateActionsService.GetPastDividends:input_type -> grpc.tradeapi.v1.corporateactions.GetPastDividendsRequest
	4,  // 58: grpc.tradeapi.v1.corporateactions.CorporateActionsService.GetFutureSplits:output_type -> grpc.tradeapi.v1.corporateactions.GetFutureSplitsResponse
	6,  // 59: grpc.tradeapi.v1.corporateactions.CorporateActionsService.GetPastSplits:output_type -> grpc.tradeapi.v1.corporateactions.GetPastSplitsResponse
	8,  // 60: grpc.tradeapi.v1.corporateactions.CorporateActionsService.GetFutureBondsEvents:output_type -> grpc.tradeapi.v1.corporateactions.GetFutureBondsEventsResponse
	10, // 61: grpc.tradeapi.v1.corporateactions.CorporateActionsService.GetPastBondsEvents:output_type -> grpc.tradeapi.v1.corporateactions.GetPastBondsEventsResponse
	17, // 62: grpc.tradeapi.v1.corporateactions.CorporateActionsService.GetFutureDividends:output_type -> grpc.tradeapi.v1.corporateactions.GetFutureDividendsResponse
	19, // 63: grpc.tradeapi.v1.corporateactions.CorporateActionsService.GetPastDividends:output_type -> grpc.tradeapi.v1.corporateactions.GetPastDividendsResponse
	58, // [58:64] is the sub-list for method output_type
	52, // [52:58] is the sub-list for method input_type
	52, // [52:52] is the sub-list for extension type_name
	52, // [52:52] is the sub-list for extension extendee
	0,  // [0:52] is the sub-list for field type_name
}

func init() { file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_init() }
func file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_init() {
	if File_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto != nil {
		return
	}
	file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes[8].OneofWrappers = []any{
		(*BondEvent_CouponDetails)(nil),
		(*BondEvent_AmortizationDetails)(nil),
		(*BondEvent_OfferDetails)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_rawDesc), len(file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_goTypes,
		DependencyIndexes: file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_depIdxs,
		EnumInfos:         file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_enumTypes,
		MessageInfos:      file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_msgTypes,
	}.Build()
	File_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto = out.File
	file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_goTypes = nil
	file_grpc_tradeapi_v1_corporateactions_corporate_actions_service_proto_depIdxs = nil
}
