syntax = "proto3";

package grpc.tradeapi.v1.auth;

import "google/api/annotations.proto";
import "google/protobuf/timestamp.proto";
import "grpc/gateway/protoc_gen_openapiv2/options/annotations.proto";

option go_package = "github.com/limeint/tradingapi/go/grpc/tradeapi/v1/auth";
option java_multiple_files = true;
option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  schemes: [
    HTTP,
    HTTPS
  ]
  info: {
    title: "REST"
    description: "Trading API"
  }
  responses: [
    {
      key: "default"
      value: {
        schema: {
          json_schema: {
            ref: "googletypeStatus"
          }
        }
      }
    },
    {
      key: "500"
      value: {
        description: "Internal service error. Please try again later."
      }
    },
    {
      key: "503"
      value: {
        description: "The service is currently unavailable. Please try again later."
      }
    },
    {
      key: "429"
      value: {
        description: "Too many requests. The available limit is 200 requests per minute."
      }
    },
    {
      key: "401"
      value: {
        description: "Token has expired or the token is invalid"
      }
    },
    {
      key: "504"
      value: {
        description: "The deadline expired before the operation could be completed."
      }
    },
    {
      key: "400"
      value: {
        description: "Token has expired or the token is invalid"
      }
    }
  ]
};

// Authentication Service
service AuthService {
  // Getting a JWT token from the token API
  // HTTP request example:
  // POST /v1/sessions
  // Content-Type: application/json
  //
  // {
  // "secret":"your-api-secret-key"
  // }
  //
  // All fields are passed in the request body
  rpc Auth(AuthRequest) returns (AuthResponse) {
    option (google.api.http) = {
      post: "/v1/sessions"
      body: "*"
    };
  };

  // Get session token information
  // HTTP request example:
  // POST /v1/sessions/details
  // Content-Type: application/json
  //
  // {
  //  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
  // }
  //
  // The token is passed in the request body for security.
  // Get token information. Also includes a list of available accounts.
  rpc TokenDetails(TokenDetailsRequest) returns (TokenDetailsResponse) {
    option (google.api.http) = {
      post: "/v1/sessions/details"
      body: "*"
    };
  };

  // Subscribe to JWT token renewal. Stream method
  rpc SubscribeJwtRenewal(SubscribeJwtRenewalRequest) returns (stream SubscribeJwtRenewalResponse);

}

// Authorization Request
message AuthRequest {
  // API token (secret key)
  string secret = 1;
  // ID of the source application sending the request
  string source_app_id = 2;
}

// Authorization Information
message AuthResponse {
  // Received JWT token
  string token = 1;
}

// Request token details
message TokenDetailsRequest {
  // JWT token
  string token = 1;
}

// Token Details
message TokenDetailsResponse {
  // Creation date and time
  google.protobuf.Timestamp created_at = 1;
  // Expiration date and time
  google.protobuf.Timestamp expires_at = 2;
  // Market Data Access Details
  repeated MDPermission md_permissions = 3;
  // Account IDs
  repeated string account_ids = 4;
  // The session and trading accounts in the token will be marked readonly
  bool readonly = 5;
}

// Market Data Access Information
message MDPermission {
  // Quote Level
  enum QuoteLevel {
    // Value not specified
    QUOTE_LEVEL_UNSPECIFIED = 0;
    // Last price
    QUOTE_LEVEL_LAST_PRICE = 1;
    // Bid ask
    QUOTE_LEVEL_BEST_BID_OFFER = 2;
    // Aggregated Order Book
    QUOTE_LEVEL_DEPTH_OF_MARKET = 3;
    // Full glass
    QUOTE_LEVEL_DEPTH_OF_BOOK = 4;
    // Access denied
    QUOTE_LEVEL_ACCESS_FORBIDDEN = 5;
  }
  // Quote Level
  QuoteLevel quote_level = 1;
  // Delay in minutes
  int32 delay_minutes = 2;

  oneof condition {
    // MIC Exchange ID
    string mic = 3;
    // Country
    string country = 4;
    // Continent
    string continent = 5;
    // The whole world
    bool worldwide = 6;
  }
}

// JWT token refresh subscription request
message SubscribeJwtRenewalRequest {
  // API token (secret key)
  string secret = 1;
  // ID of the source application sending the request
  string source_app_id = 2;
}

// Renewed token. Stream
message SubscribeJwtRenewalResponse {
  // Received JWT token
  string token = 1;
}

