syntax = "proto3";

package grpc.tradeapi.v1.accounts;

import "google/api/annotations.proto";
import "google/protobuf/timestamp.proto";
import "google/type/decimal.proto";
import "google/type/interval.proto";
import "google/type/money.proto";
import "grpc/tradeapi/v1/side.proto";
import "grpc/tradeapi/v1/trade.proto";
import "grpc/gateway/protoc_gen_openapiv2/options/annotations.proto";

option go_package = "github.com/limeint/tradingapi/go/grpc/tradeapi/v1/accounts";
option java_multiple_files = true;
option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  schemes: [
    HTTP,
    HTTPS
  ]
  info: {
    title: "REST"
    description: "Trading API"
  }
  security_definitions: {
    security: {
      key: "Authorization"
      value: {
        type: TYPE_API_KEY
        in: IN_HEADER
        name: "Authorization"
        description: "JWT authorization token"
      }
    }
  }
  responses: [
    {
      key: "default"
      value: {
        schema: {
          json_schema: {
            ref: "googletypeStatus"
          }
        }
      }
    },
    {
      key: "500"
      value: {
        description: "Internal service error. Please try again later."
      }
    },
    {
      key: "503"
      value: {
        description: "The service is currently unavailable. Please try again later."
      }
    },
    {
      key: "429"
      value: {
        description: "Too many requests. The available limit is 200 requests per minute."
      }
    },
    {
      key: "401"
      value: {
        description: "Token has expired or the token is invalid"
      }
    },
    {
      key: "504"
      value: {
        description: "The deadline expired before the operation could be completed"
      }
    },
    {
      key: "404"
      value: {
        description: "Account not found in token"
      }
    }
  ]
};

// Accounts Service
service AccountsService {
  // Get information on a specific account
  // HTTP request example:
  // GET /v1/accounts/A12345
  // Authorization: <token>
  rpc GetAccount(GetAccountRequest) returns (GetAccountResponse) {
    option (google.api.http) = {
      get: "/v1/accounts/{account_id}"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      security: [
        {
          security_requirement: {
            key: "Authorization"
          }
        }
      ]
    };
  };

  // Getting account trade history
  // HTTP request example:
  // GET /v1/accounts/A12345/trades?limit=50&interval.start_time=2023-01-01T00:00:00Z&interval.end_time=2023-01-31T23:59:59Z
  // Authorization: <token>
  //
  // Parameters:
  // - account_id - passed in the URL path
  // - limit and interval - passed as query parameters
  rpc Trades(TradesRequest) returns (TradesResponse) {
    option (google.api.http) = {
      get: "/v1/accounts/{account_id}/trades"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      security: [
        {
          security_requirement: {
            key: "Authorization"
          }
        }
      ]
      responses: {
        key: "400"
        value: {
          description: "Invalid interval passed"
        }
      }
    };
  };

  // Getting a list of account transactions
  // HTTP request example:
  // GET /v1/accounts/A12345/transactions?limit=50&interval.start_time=2023-01-01T00:00:00Z&interval.end_time=2023-01-31T23:59:59Z
  // Authorization: <token>
  //
  // Parameters:
  // - account_id - passed in the URL path
  // - limit and interval - passed as query parameters
  rpc Transactions(TransactionsRequest) returns (TransactionsResponse) {
    option (google.api.http) = {
      get: "/v1/accounts/{account_id}/transactions"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      security: [
        {
          security_requirement: {
            key: "Authorization"
          }
        }
      ]
      responses: {
        key: "400"
        value: {
          description: "Invalid interval passed"
        }
      }
    };
  };

  // Subscribe to account information. Stream method
  rpc SubscribeAccount(GetAccountRequest) returns (stream GetAccountResponse);

}

// Request to obtain information about a specific account
message GetAccountRequest {
  // Account ID
  string account_id = 1;
}

// Information about a specific account
message GetAccountResponse {
  // Account ID
  string account_id = 1;
  // Account type
  string type = 2;
  // Account Status
  string status = 3;
  // Available funds plus the value of open positions
  google.type.Decimal equity = 4;
  // Unrealized profit
  google.type.Decimal unrealized_profit = 5;
  // Positions. Open plus theoretical (for unfilled active orders)
  repeated Position positions = 6;
  // The amount of equity in the account available for trading. Does not include margin funds.
  repeated google.type.Money cash = 7;

  oneof portfolio {
    // Portfolio type for accounts in US markets.
    MCT portfolio_mct = 9;
    // Portfolio type for trading on the Moscow Exchange derivatives market.
    FORTS portfolio_forts = 10;
  }
  // Account opening date
  google.protobuf.Timestamp open_account_date = 11;
  // Date of the first trade transaction
  google.protobuf.Timestamp first_trade_date = 12;
  // Date of the first non-trade transaction
  google.protobuf.Timestamp first_non_trade_date = 13;
}

// Portfolio type for accounts on US markets.
// Provides access to US exchanges: NYSE NASDAQ CBOE CME, trades in US stocks, futures, and options.
message MCT {
}

// Portfolio type for trading on the Moscow Exchange derivatives market.
// Designed for working with derivative financial instruments: futures and options.
message FORTS {
  // The amount of equity in the account available for trading. Includes margin funds.
  google.type.Decimal available_cash = 1;
  // Minimum margin (required collateral amount for open positions)
  google.type.Decimal money_reserved = 2;
}

// Request to receive trade history
message TradesRequest {
  // Account ID
  string account_id = 1;
  // Trade limit
  int32 limit = 2;
  // Start and end of the requested Unix epoch time period
  google.type.Interval interval = 3;
}

// Trade History
message TradesResponse {
  // Account Transactions
  repeated AccountTrade trades = 1;
}

// Request to get a list of transactions
message TransactionsRequest {
  // Account ID
  string account_id = 1;
  // Transaction limit
  int32 limit = 2;
  // Start and end of the requested Unix epoch time period
  google.type.Interval interval = 3;
}

// List of transactions
message TransactionsResponse {
  // Account transactions
  repeated Transaction transactions = 1;
}

// Position Information
message Position {
  // Symbol
  string symbol = 1;
  // Quantity in units. Signed value defining (long-short)
  google.type.Decimal quantity = 2;
  // Average price. Not populated for FORTS positions.
  google.type.Decimal average_price = 3;
  // Current price
  google.type.Decimal current_price = 4;
  // Maintenance margin. Only completed for FORTS positions.
  google.type.Decimal maintenance_margin = 5;
  // Profit or loss for the current day (PnL). Not populated for FORTS positions.
  google.type.Decimal daily_pnl = 6;
  // Total unrealized profit or loss (PnL) of the current position
  google.type.Decimal unrealized_pnl = 7;
}

// Transaction Information
message Transaction {
  // Object populated for trade transaction types
  message Trade {
    // Quantity in pcs.
    google.type.Decimal size = 1;
    // Trade price per unit. Strike price/Option premium. This is the execution price; the value is taken from the trade.
    google.type.Decimal price = 2;
    // NKD. Completed if the transaction includes NKD.
    google.type.Decimal accrued_interest = 3;
  }
  // Transaction categories.
  enum TransactionCategory {
    // Other
    OTHERS = 0;
    // Money deposit
    DEPOSIT = 1;
    // Money withdraw
    WITHDRAW = 2;
    // Income
    INCOME = 5;
    // Commission
    COMMISSION = 7;
    // Tax
    TAX = 8;
    // Inheritance
    INHERITANCE = 9;
    // Money transfer
    TRANSFER = 11;
    // Contract Termination
    CONTRACT_TERMINATION = 12;
    // Expenses
    OUTCOMES = 13;
    // Fine
    FINE = 15;
    // Loan
    LOAN = 19;
  }
  // Transaction ID
  string id = 1;
  // Transaction type from TransactionCategory
  string category = 2 [deprecated = true];
  // Timestamp
  google.protobuf.Timestamp timestamp = 4;
  // Symbol
  string symbol = 5;
  // Change in money
  google.type.Money change = 6;
  // Transaction Information
  Trade trade = 7;
  // Transaction category from TransactionCategory.
  TransactionCategory transaction_category = 8;
  // Transaction name
  string transaction_name = 9;
  // Change in qty only for securities transfers (for TransactionCategory = TRANSFER)
  google.type.Decimal change_qty = 10;
}

